#!/usr/bin/env python3
"""Preview or materialize one team's whole-file Claude project contract and
the project-rendered role agents that carry each role's resolved model and
effort."""

from __future__ import annotations

import argparse
import functools
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Callable

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import atomic_file
import host_listing
import project_config
import project_instructions
import role_settings


HOST = "claude"
AGENTS_DIR = Path(".claude") / "agents"
OWNER_RE = re.compile(
    r"^# Generated by Agent Marketplace ([a-z0-9]+(?:-[a-z0-9]+)*); do not edit by hand\.$"
)
FIELD_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):")
# A project agent honours these fields and a plugin agent ignores them, so the
# rendered role drops them to run as the plugin's role does.
PLUGIN_IGNORED_FIELDS = ("hooks", "mcpServers", "permissionMode")
# A tier set to the session's model renders this, which runs the role on the
# main conversation's model.
SESSION_MODEL = "inherit"
# Apply judges every model the roles run against this Claude Code's own model
# list. A role of an unavailable model renders on the session's model with its
# own effort, and records why, so check and inspect render it the same; the
# next apply judges it again. The stamp keeps the resolved settings, so the
# session start check finds the render current.
UNAVAILABLE_RE = re.compile(r"^# Model unavailable: (\S+)$")
SESSION_PHRASE = "this session's model"
# Claude Code substitutes these in a plugin agent's body, never in a project
# agent's; the render resolves the two whose value it knows.
SUBSTITUTION_RE = re.compile(r"\$\{(CLAUDE_[A-Z_]+|user_config\.[^}]*)\}")
RESTART_NOTICE = (
    "This run created .claude/agents/, which Claude Code loads only when a session"
    " starts: restart Claude Code before the next workflow. Until then every role runs"
    " as the plugin's {team}:<role> agent with the package's models and efforts, not"
    " this project's model settings."
)

atomic_write = atomic_file.replace_text


def owner(team: str) -> str:
    return f"# Generated by Agent Marketplace {team}; do not edit by hand."


# The stamp both host generators write and their session start checks compare.
package_version = role_settings.package_version
stamp = role_settings.stamp


def agent_name(team: str, role: str) -> str:
    """Name a rendered role after its plugin: `<team>:<role>` becomes `<team>-<role>`.

    Claude Code does not load a project agent whose name contains ':', which it
    keeps for plugin-scoped names. A user names an agent after an installed
    plugin only on purpose, and the render refuses a file that takes the name.
    """
    return f"{team}-{role}"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def split_agent(text: str, where: Path) -> tuple[list[tuple[str, list[str]]], str]:
    """Return an agent's frontmatter fields, each with its lines, and its body."""
    if not text.startswith("---\n"):
        raise ValueError(f"{where}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise ValueError(f"{where}: unclosed frontmatter")
    fields: list[tuple[str, list[str]]] = []
    for line in text[4:end].splitlines():
        match = FIELD_RE.match(line)
        if match:
            fields.append((match.group(1), [line]))
        elif fields:
            fields[-1][1].append(line)
        else:
            fields.append(("", [line]))
    return fields, text[end + 5:]


def field_value(fields: list[tuple[str, list[str]]], key: str) -> str | None:
    for name, lines in fields:
        if name == key:
            return lines[0].split(":", 1)[1].strip().strip("\"'")
    return None


def declared_name(text: str) -> str | None:
    try:
        fields, _body = split_agent(text, Path())
    except ValueError:
        return None
    return field_value(fields, "name")


def read_config(project_root: Path, workspace: str) -> dict:
    path = project_root / workspace / "config.json"
    try:
        return project_config.load(path)
    except (OSError, ValueError) as exc:
        raise ValueError(f"{workspace}/config.json is unreadable: {exc}") from exc


def resolve_body(body: str, source: Path, plugin_root: Path, project_root: Path) -> str:
    values = {"CLAUDE_PLUGIN_ROOT": str(plugin_root), "CLAUDE_PROJECT_DIR": str(project_root)}

    def replace(match: re.Match) -> str:
        if match.group(1) in values:
            return values[match.group(1)]
        raise ValueError(
            f"{source}: a project agent cannot resolve ${{{match.group(1)}}}; only"
            " ${CLAUDE_PLUGIN_ROOT} and ${CLAUDE_PROJECT_DIR} render"
        )

    return SUBSTITUTION_RE.sub(replace, body)


def render_agent(
    source: Path, team: str, package: dict, setting: dict,
    plugin_root: Path, project_root: Path, version: str, unavailable: bool = False,
) -> str:
    """Render one plugin role as a project agent with its resolved ``setting``,
    on the session's model when its model is ``unavailable``."""
    fields, body = split_agent(source.read_text(encoding="utf-8"), source)
    if field_value(fields, "name") != source.stem:
        raise ValueError(f"{source}: agent name must equal its file stem")
    if field_value(fields, "model") != package.get("model", SESSION_MODEL) \
            or field_value(fields, "effort") != package.get("effort"):
        raise ValueError(
            f"{source}: its model and effort differ from the package tier map;"
            " reinstall the package"
        )
    model = SESSION_MODEL if setting["model"] == role_settings.SESSION or unavailable \
        else setting["model"]
    lines = ["---", owner(team), stamp(team, version, source, setting)]
    if unavailable:
        lines.append(f"# Model unavailable: {setting['model']}")
    for key, field_lines in fields:
        if key == "name":
            lines.append(f"name: {agent_name(team, source.stem)}")
        elif key == "model":
            lines.append(f"model: {model}")
            if setting["effort"] is not None:
                lines.append(f"effort: {setting['effort']}")
        elif key not in ("effort", *PLUGIN_IGNORED_FIELDS):
            lines.extend(field_lines)
    return "\n".join(lines) + "\n---\n" + resolve_body(body, source, plugin_root, project_root)


def project_settings(plugin_root: Path, project_root: Path, workspace: str) -> tuple[dict, dict]:
    """Return the package tier map and the project config, refusing a config the
    package does not take."""
    tier_map = role_settings.load_tier_map(plugin_root / "templates" / "tier-map.json")
    if tier_map is None or HOST not in tier_map["hosts"]:
        raise ValueError("the installed package ships no tier map for this host;"
                         " reinstall the package")
    config = read_config(project_root, workspace)
    errors = role_settings.config_errors(config, tier_map)
    if errors:
        raise ValueError("; ".join(errors))
    return tier_map, config


def cli_floor(tier_map: dict, models) -> str | None:
    """The highest min_cli_version of the catalog models among ``models``, which
    a `claude` on PATH must meet to judge them."""
    catalog = tier_map["hosts"][HOST]["models"]
    floors = [catalog[model].get("min_cli_version") for model in models if model in catalog]
    floors = [floor for floor in floors if host_listing.release(floor) is not None]
    return max(floors, key=host_listing.release, default=None)


def recorded_unavailable(project_root: Path, team: str) -> set[str]:
    """The models this team's rendered roles record as unavailable."""
    recorded: set[str] = set()
    agents_dir = project_root / AGENTS_DIR
    if agents_dir.is_symlink() or not agents_dir.is_dir():
        return recorded
    for path in sorted(agents_dir.glob(f"{team}-*.md")):
        if path.is_symlink() or not path.is_file():
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue  # plan_agents reports an unreadable file
        if lines[:2] != ["---", owner(team)]:
            continue
        for line in lines[2:]:
            if not line.startswith("#"):
                break
            match = UNAVAILABLE_RE.fullmatch(line)
            if match:
                recorded.add(match.group(1))
    return recorded


def fallen_setting(setting: dict, unavailable: set[str]) -> dict:
    """A resolved setting as rendered: `session` where its model is unavailable."""
    if setting["model"] in unavailable:
        return {**setting, "model": role_settings.SESSION, "model_source": "fallback"}
    return setting


def render_agents(
    plugin_root: Path, project_root: Path, team: str, workspace: str,
    model_listing: Callable[..., dict] | None = None,
) -> tuple[dict[str, str], dict[str, dict]]:
    """Render every role of the package, and report this host's tiers, roles and
    model check.

    ``model_listing`` reads this Claude Code's own model list; without it the
    render keeps what the rendered roles record.
    """
    tier_map, config = project_settings(plugin_root, project_root, workspace)
    rows = role_settings.resolve(tier_map, config, HOST)
    tier_settings = role_settings.tier_settings(tier_map, config, HOST)
    pins = host_listing.pinned(rows, role_settings.SESSION, role_settings.ROLE_TIER_CHOICES)
    check: dict = {"status": "not_run"}
    conflicts: list = []
    if model_listing is not None:
        listing = model_listing(min_version=cli_floor(tier_map, pins))
        check = host_listing.model_check(listing, pins)
        unavailable = host_listing.unavailable(check)
        conflicts = host_listing.effort_conflicts(listing, tier_settings,
                                                  tier_map["hosts"][HOST]["models"])
    else:
        unavailable = recorded_unavailable(project_root, team) & set(pins)
    package = role_settings.package_tiers(tier_map)
    tiers = tier_map["hosts"][HOST]["tiers"]
    sources = {path.stem: path for path in sorted((plugin_root / "agents").glob("*.md"))}
    if set(sources) != set(package):
        raise ValueError("the package's agents differ from its tier map; reinstall the package")
    version = package_version(plugin_root)
    rendered = {}
    for role, source in sources.items():
        rendered[f"{agent_name(team, role)}.md"] = render_agent(
            source, team, tiers.get(package[role], {}), rows[role], plugin_root,
            project_root, version, rows[role]["model"] in unavailable)
    report = {
        "tier_map": {tier: fallen_setting(setting, unavailable)
                     for tier, setting in tier_settings.items()},
        "roles": {role: fallen_setting(row, unavailable) for role, row in rows.items()},
        "model_check": check,
        "model_fallbacks": {model: pins[model]["roles"] for model in sorted(unavailable)},
        "model_notes": host_listing.check_notes("claude-project", check, pins, unavailable,
                                                conflicts, SESSION_PHRASE),
    }
    return rendered, report


def agent_files(agents_dir: Path) -> list[Path]:
    """Every Markdown file Claude Code would scan, without following directory links."""
    found = []
    for directory, subdirectories, filenames in os.walk(agents_dir, followlinks=False):
        subdirectories.sort()
        found.extend(Path(directory) / name for name in sorted(filenames)
                     if name.endswith(".md"))
    return found


def stale_agents(project_root: Path, plugin_root: Path) -> tuple[list[str], int]:
    """Return the rendered role agents whose stamp does not match the installed
    package and the project's settings, and how many rendered role agents the
    project holds.

    A file rendered by another package version, from another source agent,
    with another model or effort than `workspace/config.json` now resolves or
    before stamps existed still runs what it was rendered with until setup or
    a refresh renders it again; so does one whose role the package no longer
    ships. While the config cannot be resolved, no rendered file is current.
    """
    team = project_instructions.plugin_name(plugin_root)
    agents_dir = project_root / AGENTS_DIR
    if agents_dir.is_symlink() or not agents_dir.is_dir():
        return [], 0
    version = package_version(plugin_root)
    try:
        tier_map, config = project_settings(
            plugin_root, project_root, project_instructions.CANONICAL_WORKSPACE)
        rows = role_settings.resolve(tier_map, config, HOST)
    except (OSError, ValueError):
        rows = {}
    stale: list[str] = []
    held = 0
    for path in sorted(agents_dir.glob(f"{team}-*.md")):
        if path.is_symlink() or not path.is_file():
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        if lines[:2] != ["---", owner(team)]:
            continue
        held += 1
        source = plugin_root / "agents" / path.name[len(team) + 1:]
        setting = rows.get(source.stem)
        if not source.is_file() or setting is None \
                or lines[2:3] != [stamp(team, version, source, setting)]:
            stale.append(path.relative_to(project_root).as_posix())
    return stale, held


def plan_agents(
    project_root: Path, team: str, rendered: dict[str, str],
) -> tuple[dict[Path, str | None], dict[str, str], dict[str, str], list[str]]:
    """Plan the managed role files: write what differs, remove what is stale.

    The managed files are the top-level `<team>-*.md` files that carry this
    team's header. Any other file with the header, such as a user's copy of a
    rendered role, stays and is reported under ``kept``.
    """
    agents_dir = project_root / AGENTS_DIR
    for path in (agents_dir.parent, agents_dir):
        if path.is_symlink():
            raise ValueError(f"managed Claude agent directory is a symbolic link: {path}")
    names = {filename[:-len(".md")] for filename in rendered}
    changes: dict[Path, str | None] = {}
    current: dict[str, str] = {}
    kept: list[str] = []
    for path in agent_files(agents_dir) if agents_dir.is_dir() else []:
        relative = path.relative_to(project_root).as_posix()
        top = path.parent == agents_dir
        if path.is_symlink() and top and path.name in rendered:
            raise ValueError(f"managed Claude agent target is a symbolic link: {path}")
        if path.is_symlink() and not path.exists():
            continue  # a dangling link defines no agent
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            raise ValueError(f"Claude agent file is unreadable: {path}: {exc}") from exc
        lines = text.splitlines()
        header = lines[1] if len(lines) > 1 and lines[0] == "---" else ""
        match = OWNER_RE.fullmatch(header)
        if match and match.group(1) != team:
            raise ValueError(
                f"project already has Claude agents managed by team {match.group(1)!r}: {relative}"
            )
        if match and not path.is_symlink():
            if top and path.name.startswith(f"{team}-"):
                current["local:" + relative] = sha256_text(text)
                if path.name not in rendered:
                    changes[path] = None
                continue
            kept.append(relative)
        if top and path.name in rendered:
            raise ValueError(f"unmanaged Claude agent collision: {relative}")
        name = declared_name(text)
        if name in names:
            raise ValueError(
                f"{relative} declares the agent name {name}, which {team} renders;"
                " rename or remove that agent"
            )
    target: dict[str, str] = {}
    for filename, content in rendered.items():
        path = agents_dir / filename
        target["local:" + path.relative_to(project_root).as_posix()] = sha256_text(content)
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            changes[path] = content
    return changes, current, target, kept


def preview(
    project_root: Path,
    plugin_root: Path,
    workspace: str,
    *,
    choices: dict[str, str] | None = None,
    seed_user_files: bool = False,
    scope: str = "all",
    model_listing: Callable[..., dict] | None = None,
) -> dict:
    project_instructions.validate_workspace(workspace)
    if scope not in {"all", "tracked", "local"}:
        raise project_instructions.ProjectInstructionError(
            f"unsupported project generation scope: {scope}"
        )
    if scope == "local":
        result = {
            "changes": {}, "choice_requests": [],
            "current_surfaces": {}, "target_surfaces": {},
        }
    else:
        result = project_instructions.plan_portable_project_files(
            project_root,
            plugin_root,
            workspace,
            choices=choices,
            seed_user_files=seed_user_files,
        )
    result.update({"tier_map": {}, "roles": {}, "kept": [], "model_check": {"status": "not_run"},
                   "model_fallbacks": {}, "model_notes": []})
    if scope in {"all", "local"}:
        team = project_instructions.plugin_name(plugin_root)
        rendered, report = render_agents(plugin_root, project_root, team, workspace,
                                         model_listing)
        result.update(report)
        changes, current, target, result["kept"] = plan_agents(
            project_root, team, rendered)
        result["changes"] = {**result["changes"], **changes}
        result["current_surfaces"].update(current)
        result["target_surfaces"].update(target)
    return result


def materialize(
    project_root: Path,
    plugin_root: Path,
    workspace: str,
    writer: Callable[[Path, str], None] = atomic_write,
    *,
    choices: dict[str, str] | None = None,
    seed_user_files: bool = True,
    scope: str = "all",
    model_listing: Callable[..., dict] | None = None,
) -> tuple[list[Path], bool]:
    """Apply the plan; also report whether it created the agents directory."""
    result = preview(
        project_root,
        plugin_root,
        workspace,
        choices=choices,
        seed_user_files=seed_user_files, scope=scope, model_listing=model_listing,
    )
    if result["choice_requests"]:
        raise project_instructions.ProjectInstructionError(
            "project instruction reconciliation choice required: "
            + json.dumps(result["choice_requests"], sort_keys=True)
        )
    changes: dict[Path, str | None] = result["changes"]
    agents_dir = project_root / AGENTS_DIR
    agents_existed = agents_dir.is_dir()
    snapshots = {
        path: path.read_bytes() if path.is_file() else None for path in changes
    }
    created_dirs: set[Path] = set()
    for path in changes:
        parent = path.parent
        while parent != project_root and not parent.exists():
            created_dirs.add(parent)
            parent = parent.parent
    written: list[Path] = []
    try:
        for path, content in changes.items():
            if content is None:
                path.unlink()
            else:
                writer(path, content)
            written.append(path)
    except Exception:
        for path, previous in snapshots.items():
            if previous is None:
                path.unlink(missing_ok=True)
            else:
                atomic_file.replace_bytes(path, previous)
        for directory in sorted(created_dirs, key=lambda value: len(value.parts), reverse=True):
            try:
                directory.rmdir()
            except OSError:
                pass
        raise
    return written, not agents_existed and agents_dir.is_dir()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("inspect", "check", "apply"))
    parser.add_argument("--project-root", type=Path, required=True)
    parser.set_defaults(workspace=project_instructions.CANONICAL_WORKSPACE)
    parser.add_argument("--choice", action="append", default=[])
    parser.add_argument("--seed-user-files", action="store_true")
    parser.add_argument("--scope", choices=("all", "tracked", "local"), default="all")
    args = parser.parse_args()
    project = args.project_root.resolve()
    plugin_root = Path(__file__).resolve().parents[1]
    created = False
    # Only apply reads this Claude Code's own model list, once; inspect and
    # check keep what the rendered roles record.
    listing = None
    if args.action == "apply":
        import host_models
        listing = functools.lru_cache(maxsize=None)(host_models.list_models)
    try:
        choices = project_instructions.parse_choices(args.choice)
        if args.action == "inspect":
            team = project_instructions.plugin_name(plugin_root)
            surfaces = project_instructions.owned_portable_surfaces(
                project, plugin_root, team, args.workspace
            )
            report: dict = {"tier_map": {}, "roles": {}, "model_check": {"status": "not_run"},
                            "model_fallbacks": {}, "model_notes": []}
            kept: list[str] = []
            if args.scope in {"all", "local"}:
                rendered, report = render_agents(plugin_root, project, team, args.workspace)
                _changes, current, _target, kept = plan_agents(project, team, rendered)
                surfaces.update(current)
            result = {
                "changes": [],
                "choice_requests": [],
                "current_surfaces": surfaces,
                "target_surfaces": surfaces,
                "kept": kept,
                **report,
            }
            written: list[Path] = []
        else:
            result = preview(
                project,
                plugin_root,
                args.workspace,
                choices=choices,
                seed_user_files=args.seed_user_files,
                scope=args.scope,
                model_listing=listing,
            )
            written = []
            if args.action == "apply" and not result["choice_requests"]:
                written, created = materialize(
                    project,
                    plugin_root,
                    args.workspace,
                    choices=choices,
                    seed_user_files=args.seed_user_files,
                    scope=args.scope,
                    model_listing=listing,
                )
    except ValueError as exc:
        raise SystemExit(f"claude-project: {exc}") from exc
    if args.action == "apply":
        for note in result["model_notes"]:
            print(note, file=sys.stderr)
    team = project_instructions.plugin_name(plugin_root)
    print(json.dumps({
        "status": "choice_required" if result["choice_requests"] else "ok",
        "changes": sorted(
            path.relative_to(project).as_posix()
            for path in result["changes"]
        ) if isinstance(result.get("changes"), dict) else result["changes"],
        "choice_requests": result["choice_requests"],
        "current_surfaces": result["current_surfaces"],
        "target_surfaces": result["target_surfaces"],
        "tier_map": result["tier_map"],
        "roles": result["roles"],
        "model_check": result["model_check"],
        "model_fallbacks": result["model_fallbacks"],
        "kept": result["kept"],
        "written": [str(path) for path in written],
        "restart_required": created,
        "notice": RESTART_NOTICE.format(team=team) if created else "",
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
