#!/usr/bin/env python3
"""Materialize Codex project agents and the managed AGENTS.md block."""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


OWNER = "# Generated by Agentrof software-engineering-team; do not edit by hand."
AGENTS_START = "<!-- agentrof:codex:start -->"
AGENTS_END = "<!-- agentrof:codex:end -->"
MODEL_EFFORT = {"opus": "high", "sonnet": "medium", "haiku": "low"}
READ_ONLY_TOOLS = {"Read", "Grep", "Glob"}


def parse_agent(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise ValueError(f"{path}: unclosed frontmatter")
    fields: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key.strip()] = value.strip().strip("\"'")
    return fields, text[end + 5 :].strip() + "\n"


def agent_toml(fields: dict[str, str], body: str) -> str:
    name = fields.get("name", "")
    description = fields.get("description", "")
    model = fields.get("model", "inherit")
    if not name or not description:
        raise ValueError("agent requires name and description")
    instructions = (
        body
        + "\nCodex host rules:\n"
        + "- Treat the parent spawn prompt as the task boundary.\n"
        + "- Read every bound Agentrof skill from the exact canonical path in the prompt.\n"
        + "- Return only the declared output contract and the required SELF-CHECK.\n"
    )
    lines = [
        OWNER,
        f"name = {json.dumps(name)}",
        f"description = {json.dumps(description)}",
    ]
    effort = MODEL_EFFORT.get(model)
    if effort:
        lines.append(f"model_reasoning_effort = {json.dumps(effort)}")
    tools = {item.strip() for item in fields.get("tools", "").split(",") if item.strip()}
    if tools and tools <= READ_ONLY_TOOLS:
        lines.append('sandbox_mode = "read-only"')
    lines.append(f"developer_instructions = {json.dumps(instructions)}")
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def render_agents(plugin_root: Path) -> dict[str, str]:
    rendered: dict[str, str] = {}
    for source in sorted((plugin_root / "agents").glob("*.md")):
        fields, body = parse_agent(source)
        name = fields.get("name", "")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise ValueError(f"{source}: invalid Codex agent name {name!r}")
        if name != source.stem:
            raise ValueError(
                f"{source}: agent name {name!r} must equal file stem {source.stem!r}"
            )
        rendered[f"{name}.toml"] = agent_toml(fields, body)
    return rendered


def managed_agents_block(plugin_root: Path, workspace: str) -> str:
    template = (plugin_root / "templates" / "AGENTS.md").read_text(encoding="utf-8")
    return template.replace("{{workspace}}", workspace).rstrip()


def merge_agents_md(existing: str, block: str) -> str:
    managed = f"{AGENTS_START}\n{block}\n{AGENTS_END}"
    start = existing.find(AGENTS_START)
    end = existing.find(AGENTS_END)
    if start == -1 and end == -1:
        prefix = existing.rstrip()
        return (prefix + "\n\n" if prefix else "") + managed + "\n"
    if start == -1 or end == -1 or end < start:
        raise ValueError("AGENTS.md has an incomplete Agentrof managed block")
    end += len(AGENTS_END)
    return existing[:start] + managed + existing[end:]


def materialize(project_root: Path, plugin_root: Path, workspace: str) -> list[Path]:
    rendered = render_agents(plugin_root)
    agents_dir = project_root / ".codex" / "agents"
    collisions: list[Path] = []
    for filename in rendered:
        target = agents_dir / filename
        if target.is_file() and not target.read_text(
            encoding="utf-8", errors="replace"
        ).startswith(OWNER):
            collisions.append(target)
    if collisions:
        joined = ", ".join(str(path) for path in collisions)
        raise ValueError(f"unmanaged Codex agent collision: {joined}")

    written: list[Path] = []
    if agents_dir.is_dir():
        for target in sorted(agents_dir.glob("*.toml")):
            if target.name in rendered:
                continue
            if target.read_text(encoding="utf-8", errors="replace").startswith(OWNER):
                target.unlink()
                written.append(target)
    for filename, content in rendered.items():
        target = agents_dir / filename
        if not target.is_file() or target.read_text(encoding="utf-8") != content:
            atomic_write(target, content)
            written.append(target)

    agents_md = project_root / "AGENTS.md"
    existing = agents_md.read_text(encoding="utf-8") if agents_md.is_file() else ""
    merged = merge_agents_md(existing, managed_agents_block(plugin_root, workspace))
    if existing != merged:
        atomic_write(agents_md, merged)
        written.append(agents_md)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--workspace", default="workspace")
    args = parser.parse_args()
    project_root = args.project_root.resolve()
    if not (project_root / ".git").exists():
        raise SystemExit("codex-project: --project-root must be a git repository root")
    plugin_root = Path(__file__).resolve().parents[1]
    try:
        written = materialize(project_root, plugin_root, args.workspace)
    except ValueError as exc:
        raise SystemExit(f"codex-project: {exc}") from exc
    print(json.dumps({
        "status": "ok",
        "written": [str(path) for path in written],
        "restart_required": True,
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
