"""Fixture builders for the validator test suite.

Each builder takes a repository root that `make_valid_root` prepared and
plants EXACTLY ONE rule violation. The meta-test asserts that the builder
registry and the validator check registry stay in lockstep: a check without
a fixture cannot merge.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import build_distributions

REAL_MODEL_CONFIG = (Path(__file__).resolve().parents[1]
                     / "data" / "models.json")
REAL_LIMITS_CONFIG = (Path(__file__).resolve().parents[1]
                      / "data" / "limits.json")
REAL_REPOSITORY = Path(__file__).resolve().parents[2]

PLUGIN = "sample-team"

VALID_AGENT = """---
name: planner
description: Planner role for orchestrated team runs. Invoked by sample-team flows with explicit inputs.
reasoning: medium
output_contract: prose
---

# Planner

Turns an approved brief into an ordered plan of small packages.

## Principles
- Every criterion is mapped or consciously deferred with a reason.

## Boundaries
- Does: planning and ordering.
- Does not: implementation decisions.

## Approach
1. Read the inputs named in the spawn prompt.
2. Produce the plan in small verifiable increments.

## Output Contract
- Exactly one plan artifact at the given path, ending with SELF-CHECK.
"""

VALID_SKILL = """---
name: notes
description: Knowledge skill for planning notes. Loaded by sample-team agents during runs.
exposure: internal
---

# Notes

Planning notes knowledge.

## When to Use
- Loaded by the bound agent when planning.

## Core Rules
- Keep notes terse and decision-oriented.
- Respect the user's explicit theme override.
"""

VALID_FLOW = """# Develop Flow

You MUST follow these rules exactly.

1. Execute steps in order.
2. Read prior steps from files, not conversation memory.

Spawn template:

Paste {{constitution}} here, then the inputs.
"""


VALID_VAULT_POLICY = {
    "schema_version": 3,
    "vault_root_dirname": "docs",
    "home_file": "home.md",
    "maps_dir": "maps",
    "subtrees": ["notes"],
    "extra_maps": [],
    "machine_dirs": ["_generated", "_relations", "_navigation"],
    "banned_basenames": ["notes.md", "overview.md", "readme.md"],
    "community_plugins": ["sample-title-plugin"],
    "graph_search": "-path:_generated",
    "graph_color_groups": [
        {"id": "note", "query": "tag:#doc/note", "rgb": 2201331},
        {"id": "navigation", "query": "tag:#doc/moc OR tag:#doc/home",
         "rgb": 9741240},
    ],
    "hubs": [
        {"note": "notes/*/*-overview.md", "covers": "notes/*"},
    ],
    "tag_namespaces": ["doc", "status"],
    "nav_peer_min": 2,
    "nav_peer_max": 5,
    "generated_marker_prefix": "<!-- generated by",
    "decision_trees": {
        "notes": {"path": "notes/decisions", "id_prefix": "SD",
                  "id_min_width": 3, "id_source": "alias",
                  "render_index": True},
    },
    "generated_views": ["notes/decision-log.md"],
    "generated_subtrees": ["api/"],
    "attachments_dir": "_attachments",
    "attachment_extensions": [".png", ".pdf"],
    "property_types": {"type": "text", "title": "text", "status": "text",
                       "tags": "tags", "aliases": "aliases",
                       "related_to": "multitext"},
    "extra_doc_types": ["note", "moc", "home"],
    "type_path_patterns": {
        "home": [r"^home\.md$"],
        "moc": [r"^maps/[a-z0-9-]+\.md$"],
        "note": [r"^notes/.+\.md$"],
    },
    "status_values": {"note": ["draft", "approved"]},
    "relation_contract": {
        "inverse_inline_max": 100,
        "catalog_page_size": 100,
        "catalog_root": "maps/_relations",
        "keys": {
            "related_to": {"targets": ["*"],
                           "inverse_label": "Related from"},
        },
        "required_by_type_status": {},
        "cardinality_by_type": {},
    },
}

# Dynamic home: links nothing at seed; a subtree's map line is added by
# the entry that births the tree.
VALID_HOME_SEED = """# Home

Vault navigation root. Subtree maps join as their trees gain content.
"""


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def make_valid_root(root: Path) -> None:
    shutil.copyfile(
        REAL_REPOSITORY / "product.json",
        write_path(root / "product.json"),
    )
    shutil.copytree(
        REAL_REPOSITORY / "platforms" / "shared" / "_team",
        root / "platforms" / "shared" / "_team",
    )
    shutil.copytree(
        REAL_REPOSITORY / "platforms" / "codex" / "_team",
        root / "platforms" / "codex" / "_team",
    )
    write(root / ".claude-plugin" / "marketplace.json", json.dumps({
        "name": "fixture-marketplace",
        "owner": {"name": "fixture"},
        "metadata": {"description": "fixture", "version": "0.0.1"},
        "plugins": [{
            "name": PLUGIN,
            "source": build_distributions_source("claude", PLUGIN),
            "description": "fixture plugin",
            "version": "0.0.1",
            "license": "MIT",
        }],
    }, indent=2))
    write(root / "versions.json", json.dumps({
        "schema_version": 1,
        "marketplace": "0.0.1",
        "plugins": {PLUGIN: "0.0.1"},
    }, indent=2))
    write(root / ".changes" / "fixture.json", json.dumps({
        "summary": "Exercise the repository validator fixture.",
        "components": {},
    }, indent=2))
    claude_manifest = {
        "name": PLUGIN,
        "version": "0.0.1",
        "description": "fixture plugin",
        "license": "MIT",
        "dependencies": ["project-management-office"],
        "skills": "./skills/",
    }
    write(root / "platforms" / "claude" / PLUGIN / "manifest.json",
          json.dumps(claude_manifest, indent=2))
    write(root / "platforms" / "claude" / PLUGIN / "host-contract.md",
          "# Host Contract\n\n"
          "- `team_guard.py` mechanically requires"
          " `AGENT_MARKETPLACE_PMO_READY: project-management-office`; run"
          " `claude plugin list --json` and recover with"
          " `/plugin install project-management-office@agent-marketplace`"
          " or `/plugin enable project-management-office@agent-marketplace`."
          " No files or project state were changed.\n"
          "- One delivery team owns a project.\n")
    codex_manifest = {
        **{key: value for key, value in claude_manifest.items()
           if key != "dependencies"},
        "interface": {
            "displayName": "Sample Team",
            "shortDescription": "Fixture team",
            "longDescription": "Requires Project Management Office. Fixture team",
            "developerName": "Agentrof",
            "category": "Engineering",
            "capabilities": ["Read", "Write", "Interactive"],
            "websiteURL": "https://example.com",
        },
    }
    write(root / "platforms" / "codex" / PLUGIN / "manifest.json",
          json.dumps(codex_manifest, indent=2))
    write(root / "platforms" / "codex" / PLUGIN / "host-contract.md",
          "# Host Contract\n\n"
          "- `team_guard.py` mechanically requires"
          " `AGENT_MARKETPLACE_PMO_READY: project-management-office`; run"
          " `codex plugin list --json`, recover with"
          " `codex plugin add project-management-office@agent-marketplace`,"
          " enable it in Plugins when disabled, then inspect `/hooks`."
          " No files or project state were changed.\n"
          "- One delivery team owns a project; setup runs"
          " `generate_codex_project.py`.\n")
    write(root / ".agents" / "plugins" / "marketplace.json", json.dumps({
        "name": "agent-marketplace",
        "interface": {"displayName": "Agent Marketplace"},
        "plugins": [{
            "name": PLUGIN,
            "source": build_distributions_source("codex", PLUGIN),
            "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
            "category": "Engineering",
        }],
    }, indent=2))
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", VALID_AGENT)
    shutil.copyfile(
        REAL_REPOSITORY / "plugins" / "project-management-office"
        / "scripts" / "marketplace_paths.py",
        write_path(root / "plugins" / PLUGIN / "scripts" / "marketplace_paths.py"),
    )
    write(root / "plugins" / PLUGIN / "skill-content" / "notes" / "SKILL.md",
          VALID_SKILL)
    write(root / "plugins" / PLUGIN / "migrations" / "manifest.json",
          json.dumps({
              "schema_version": 1,
              "component": PLUGIN,
              "database": None,
              "project_contract": {"baseline": 1, "current": 1, "steps": []},
          }, indent=2))
    # Hook event names are the host platform's PascalCase schema and are
    # exempt from the snake_case law at exactly $.hooks in hooks/hooks.json.
    write(root / "platforms" / "claude" / PLUGIN / "overlay" / "hooks"
          / "hooks.json", json.dumps({
        "hooks": {
            "SessionStart": [{"hooks": [{"type": "command",
                "command": "python3 team_guard.py register"}]}],
            "PreToolUse": [{"matcher": "Write|Edit|Bash", "hooks": [{
                "type": "command", "command": "python3 team_guard.py pre"}]}],
        },
    }, indent=2))
    write(root / "platforms" / "codex" / PLUGIN / "overlay" / "hooks"
          / "hooks.json", json.dumps({
        "hooks": {
            "SessionStart": [{"hooks": [{"type": "command",
                "command": "python3 team_guard.py register"}]}],
            "PreToolUse": [{"matcher": "Write|Edit|apply_patch|Bash", "hooks": [{
                "type": "command", "command": "python3 team_guard.py pre"}]}],
        },
    }, indent=2))
    # Product-vault surface: the policy, the seeds and the payload describe
    # one product. They exercise the vault_policy_shape parity assertions,
    # the templates/ wikilink_ban exemption and the json_hygiene carve-out
    # for the vault app's camelCase keys.
    vault_tpl = root / "plugins" / PLUGIN / "templates" / "vault"
    write(root / "plugins" / PLUGIN / "skill-content" / "notes" / "data"
          / "vault-policy.json",
          json.dumps(VALID_VAULT_POLICY, indent=2))
    write(vault_tpl / "home.md", VALID_HOME_SEED)
    write(vault_tpl / "maps" / "notes.md", "# Notes Map\n\nSubtree hub.\n")
    write(vault_tpl / ".obsidian" / "app.json", json.dumps({
        "useMarkdownLinks": False,
        "newLinkFormat": "absolute",
        "alwaysUpdateLinks": True,
        "attachmentFolderPath": "_attachments",
    }, indent=2))
    write(vault_tpl / ".obsidian" / "graph.json", json.dumps({
        "search": VALID_VAULT_POLICY["graph_search"],
        "colorGroups": [
            {"query": group["query"],
             "color": {"a": 1, "rgb": group["rgb"]}}
            for group in VALID_VAULT_POLICY["graph_color_groups"]
        ],
        "showOrphans": True,
        "hideUnresolved": False,
        "showTags": False,
    }, indent=2))
    write(vault_tpl / ".obsidian" / "community-plugins.json",
          json.dumps(VALID_VAULT_POLICY["community_plugins"], indent=2))
    plugin_dir = vault_tpl / ".obsidian" / "plugins" / "sample-title-plugin"
    write(plugin_dir / "manifest.json", json.dumps({
        "id": "sample-title-plugin",
        "name": "Sample Title Plugin",
        "version": "0.0.1",
        "minAppVersion": "1.0.0",
    }, indent=2))
    # The {{value}} token proves the vendored-plugin exemption from the
    # template_placeholders rule: third-party bundles are never our
    # substitutions.
    write(plugin_dir / "main.js",
          "module.exports = { onload() {}, token: \"{{value}}\" };\n")
    write(plugin_dir / "data.json", json.dumps({
        "version": "0.0.1",
        "templates": {"common": {"main": "title", "fallback": None}},
    }, indent=2))
    # The policy files, so the valid root is clean under the
    # model_config_shape and limits_config_shape checks.
    shutil.copyfile(REAL_MODEL_CONFIG,
                    write_path(root / "tools" / "data" / "models.json"))
    shutil.copyfile(REAL_LIMITS_CONFIG,
                    write_path(root / "tools" / "data" / "limits.json"))
    build_distributions.replace_generated(root, root / "dist")


def build_distributions_source(host: str, plugin: str) -> dict:
    return {
        "source": "git-subdir",
        "url": "https://github.com/agentrof/agent-marketplace.git",
        "path": f"dist/{host}/{plugin}",
        "ref": "stable",
    }


def write_path(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


# --- one builder per validator check -------------------------------------


def break_frontmatter_shape(root: Path) -> None:
    text = VALID_AGENT.replace("reasoning: medium",
                               "reasoning: medium\ncolor: blue")
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", text)


def break_agent_name(root: Path) -> None:
    text = VALID_AGENT.replace("name: planner", "name: sample-team-planner")
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", text)


def break_skill_name(root: Path) -> None:
    text = VALID_SKILL.replace("name: notes", "name: memo")
    write(root / "plugins" / PLUGIN / "skill-content" / "notes" / "SKILL.md",
          text)


def break_trigger_policy(root: Path) -> None:
    text = VALID_AGENT.replace(
        "description: Planner role for orchestrated team runs. Invoked by sample-team flows with explicit inputs.",
        "description: Planner role. Use PROACTIVELY when planning work.",
    )
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", text)


def break_size_caps(root: Path) -> None:
    padding = "\n".join(f"- padding line {i}" for i in range(1, 70))
    text = VALID_AGENT.rstrip() + "\n" + padding + "\n"
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", text)


def break_section_contract(root: Path) -> None:
    text = VALID_AGENT.replace("## Boundaries", "## Limits")
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", text)


def break_agent_tech_nouns(root: Path) -> None:
    text = VALID_AGENT.replace(
        "- Does: planning and ordering.",
        "- Does: planning and ordering with python scripts.",
    )
    write(root / "plugins" / PLUGIN / "agents" / "planner.md", text)


def break_content_bans(root: Path) -> None:
    write(root / "docs" / "note.md", "A sentence with an em dash — right here.\n")


def break_handwritten_counts(root: Path) -> None:
    write(root / "docs" / "note.md", "This marketplace ships 3 agents today.\n")


def break_dead_links(root: Path) -> None:
    write(root / "docs" / "note.md", "See [the guide](missing/guide.md) for detail.\n")


def break_reference_triggers(root: Path) -> None:
    base = root / "plugins" / PLUGIN / "skill-content" / "field-notes"
    write(base / "SKILL.md", """---
name: field-notes
description: Knowledge skill for field notes. Loaded by sample-team agents during runs.
exposure: internal
---

# Field Notes

Field notes knowledge.

## When to Use
- Loaded by the bound agent when noting.

## References
- [depth](references/depth.md): deeper notes without a trigger clause.
""")
    write(base / "references" / "depth.md", "# Depth\n\nDeeper notes.\n")


def break_registration(root: Path) -> None:
    marketplace_path = root / ".claude-plugin" / "marketplace.json"
    marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    marketplace["plugins"][0]["source"]["path"] = "./dist/claude/missing-team"
    write(marketplace_path, json.dumps(marketplace, indent=2))


def break_distribution_packaging(root: Path) -> None:
    marketplace_path = root / ".agents" / "plugins" / "marketplace.json"
    marketplace = json.loads(marketplace_path.read_text(encoding="utf-8"))
    marketplace["plugins"][0]["category"] = "Wrong"
    write(marketplace_path, json.dumps(marketplace, indent=2))


def break_team_pmo_contract(root: Path) -> None:
    manifest_path = root / "platforms" / "claude" / PLUGIN / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest.pop("dependencies")
    write(manifest_path, json.dumps(manifest, indent=2))


def break_json_hygiene(root: Path) -> None:
    write(root / "plugins" / PLUGIN / "bad.json",
          json.dumps({"displayName": "Sample Team"}, indent=2))


def break_orchestrator_integrity(root: Path) -> None:
    text = VALID_FLOW.replace("{{constitution}}", "the constitution body")
    write(root / "plugins" / PLUGIN / "flows" / "develop.md", text)


def break_choice_gate(root: Path) -> None:
    write(
        root / "plugins" / PLUGIN / "flows" / "gates.md",
        VALID_FLOW
        + "\n3. Stop at every gate and wait for explicit user choice.\n",
    )


def break_stdlib_only(root: Path) -> None:
    write(
        root / "plugins" / PLUGIN / "skill-content" / "notes" / "scripts" / "tool.py",
        "import requests\n\nprint(requests.__name__)\n",
    )


def break_naive_clock(root: Path) -> None:
    write(
        root / "plugins" / PLUGIN / "skill-content" / "notes" / "scripts" / "clock.py",
        "from datetime import date\n\nprint(date.today())\n",
    )


def break_script_references(root: Path) -> None:
    write(
        root / "plugins" / PLUGIN / "flows" / "check.md",
        VALID_FLOW + "\nRun \"$RUN\" run \"$TEAM\" scripts/missing_tool.py here.\n",
    )


def break_template_placeholders(root: Path) -> None:
    write(
        root / "plugins" / PLUGIN / "templates" / "ci.yml",
        "jobs:\n  ghost:\n    run: {{ghost_command}}\n",
    )


def break_spawn_shape_constitution(root: Path) -> None:
    write(
        root / "plugins" / PLUGIN / "skill-content" / "notes" / "spawning.md",
        "# Spawning\n\n## Spawn Shape\n\n1. Identity line.\n2. Inputs.\n",
    )


def break_ba_schema_shape(root: Path) -> None:
    # Valid in every other respect (the 'note' doc type is covered by the
    # fixture policy's color groups); the single defect is a minted kind
    # ('BR') that carries no row schema.
    write(
        root / "plugins" / PLUGIN / "skill-content" / "notes" / "data" / "space-schema.json",
        json.dumps({
            "schema_version": 2,
            "statuses": ["draft", "in_review", "approved"],
            "id_format": "^(BR)-([A-Z]{2,4})-([0-9]{3,})$",
            "id_citation_columns": ["cites"],
            "challenge": {
                "round_file_format": "round-{n}-review.md",
                "space_round_file_format": "space-round-{n}-review.md",
            },
            "doc_types": {"note": {"required_sections": [], "mints": ["BR"],
                                   "gate_blocking": True}},
            "row_schemas": {"ac": {"section": "criteria",
                                   "columns": ["id", "cites"]}},
        }, indent=2),
    )


def break_wikilink_ban(root: Path) -> None:
    text = VALID_SKILL.replace(
        "- Keep notes terse and decision-oriented.",
        "- Cite the vault note [[notes/decisions|decision]] directly.",
    )
    write(root / "plugins" / PLUGIN / "skill-content" / "notes" / "SKILL.md",
          text)


def break_version_sync(root: Path) -> None:
    path = root / "dist" / "claude" / PLUGIN / ".claude-plugin" / "plugin.json"
    manifest = json.loads(path.read_text(encoding="utf-8"))
    manifest["version"] = "0.0.2"
    write(path, json.dumps(manifest, indent=2))


def break_vault_policy_shape(root: Path) -> None:
    policy = {k: v for k, v in VALID_VAULT_POLICY.items()
              if k != "schema_version"}
    write(root / "plugins" / PLUGIN / "skill-content" / "notes" / "data"
          / "vault-policy.json",
          json.dumps(policy, indent=2))


def break_vault_wiring(root: Path) -> None:
    write(root / "plugins" / PLUGIN / "skill-content" / "obsidian-vault"
          / "SKILL.md",
          """---
name: obsidian-vault
description: Knowledge skill for the vault law. Loaded by sample-team agents during runs.
exposure: internal
---

# Vault Law

Vault authoring rules.

## When to Use
- Loaded by the bound agent when writing under the docs tree.
""")
    write(root / "plugins" / PLUGIN / "flows" / "docs.md",
          VALID_FLOW + "\n3. Write the outcome under workspace/docs/notes/.\n")


def break_model_config_shape(root: Path) -> None:
    config_path = root / "tools" / "data" / "models.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    del config["reasoning_levels"]
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")


def break_limits_config_shape(root: Path) -> None:
    config_path = root / "tools" / "data" / "limits.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))
    del config["authoring_caps"]
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")


def break_product_namespace(root: Path) -> None:
    old_signal = "AGENT" + "ROF_PMO_READY"
    write(root / "namespace-defect.txt", old_signal + "\n")


BUILDERS = {
    "frontmatter_shape": break_frontmatter_shape,
    "agent_name": break_agent_name,
    "skill_name": break_skill_name,
    "trigger_policy": break_trigger_policy,
    "size_caps": break_size_caps,
    "section_contract": break_section_contract,
    "content_bans": break_content_bans,
    "agent_tech_nouns": break_agent_tech_nouns,
    "handwritten_counts": break_handwritten_counts,
    "dead_links": break_dead_links,
    "reference_triggers": break_reference_triggers,
    "registration": break_registration,
    "distribution_packaging": break_distribution_packaging,
    "team_pmo_contract": break_team_pmo_contract,
    "json_hygiene": break_json_hygiene,
    "orchestrator_integrity": break_orchestrator_integrity,
    "choice_gate": break_choice_gate,
    "stdlib_only": break_stdlib_only,
    "naive_clock": break_naive_clock,
    "script_references": break_script_references,
    "template_placeholders": break_template_placeholders,
    "spawn_shape_constitution": break_spawn_shape_constitution,
    "ba_schema_shape": break_ba_schema_shape,
    "wikilink_ban": break_wikilink_ban,
    "version_sync": break_version_sync,
    "vault_policy_shape": break_vault_policy_shape,
    "vault_wiring": break_vault_wiring,
    "model_config_shape": break_model_config_shape,
    "limits_config_shape": break_limits_config_shape,
    "product_namespace": break_product_namespace,
}


def plant_out_of_scope_violations(root: Path) -> None:
    """Violations that must NOT be caught: assets/ and memory/ are excluded."""
    write(root / "assets" / "bad.md", "Em dash — and 5 agents and /Users/nobody paths.\n")
    write(root / "memory" / "bad.md", "Another em dash — with 9 skills.\n")
