"""Unit tests for the PMO hook scripts, using payload shapes captured from a
live probe session (SessionStart/SubagentStart/SubagentStop/SessionEnd/
PreToolUse as emitted by the host)."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "plugins" / "project-management-office" / "scripts"


def utc_today() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).date().isoformat()


def run_hook(script: str, payload: dict, env: dict, args: list[str] | None = None):
    proc = subprocess.run(
        [sys.executable, str(SCRIPTS / script), *(args or [])],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        env={**os.environ, **env},
    )
    return proc.returncode, proc.stdout, proc.stderr


def run_cli(argv: list[str], env: dict):
    proc = subprocess.run(
        [sys.executable, str(SCRIPTS / "pmo_cli.py"), *argv],
        capture_output=True,
        text=True,
        env={**os.environ, **env},
    )
    return proc.returncode, proc.stdout, proc.stderr


class PmoHookTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        root = Path(self.tmp.name)
        self.env = {"AGENTROF_HOME": str(root / "agentrof")}
        self.project_root = root / "proj"
        (self.project_root / "workspace").mkdir(parents=True)
        (self.project_root / "workspace" / "config.json").write_text(
            json.dumps({"managed_by": "software-engineering-team", "project_key": "shop"}),
            encoding="utf-8",
        )
        run_cli(["init-db"], self.env)
        run_cli(["project", "register", "--key", "shop", "--team", "software-engineering-team"],
                self.env)
        backlog = root / "backlog.json"
        backlog.write_text(json.dumps({
            "epics": [{"external_id": "EP-01", "title": "Core"}],
            "stories": [{
                "external_id": "WP-01", "epic": "EP-01", "title": "Slice one",
                "scope": "s", "excludes": "x", "dor": "d", "dod": "d",
            }],
        }), encoding="utf-8")
        run_cli(["item", "import", "--project-key", "shop",
                 "--json-file", str(backlog)], self.env)
        run_cli(["work-order", "init", "--project-key", "shop",
                 "--work-order-key", "wo1",
                 "--request", "build", "--worktree", str(self.project_root),
                 "--story", "WP-01"], self.env)

    def tearDown(self):
        self.tmp.cleanup()

    def payload(self, **extra):
        base = {
            "session_id": "s1",
            "transcript_path": "/tmp/t.jsonl",
            "cwd": str(self.project_root),
            "hook_event_name": "",
        }
        base.update(extra)
        return base

    def tasks(self):
        _, out, _ = run_cli(["item", "list", "--project-key", "shop",
                             "--kind", "task", "--json"], self.env)
        return json.loads(out)

    def install_codex_agent(self, name: str):
        path = self.project_root / ".codex" / "agents" / f"{name}.toml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Generated by Agentrof software-engineering-team; do not edit by hand.\n"
            f'name = "{name}"\n',
            encoding="utf-8",
        )

    def events(self):
        _, out, _ = run_cli(["resume-info", "--project-key", "shop",
                             "--events", "50", "--json"], self.env)
        return [e["action"] for e in json.loads(out)["recent_events"]]

    def test_subagent_start_records_task(self):
        # agent_type arrives marketplace-namespaced for plugin agents
        code, out, err = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a1",
            agent_type="software-engineering-team:backend-developer",
        ), self.env, ["start"])
        self.assertEqual(code, 0, err)
        self.assertEqual(json.loads(out), {})
        tasks = self.tasks()
        self.assertEqual(len(tasks), 1)
        self.assertEqual(tasks[0]["role"], "backend_developer")
        self.assertEqual(tasks[0]["status"], "in_progress")
        self.assertTrue(tasks[0]["started_at"])

    def test_subagent_stop_stamps_finish(self):
        run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a1", agent_type="software-engineering-team:qa-engineer",
        ), self.env, ["start"])
        code, _, _ = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStop",
            agent_id="a1", agent_type="software-engineering-team:qa-engineer",
            last_assistant_message="done",
        ), self.env, ["stop"])
        self.assertEqual(code, 0)
        self.assertTrue(self.tasks()[0]["finished_at"])

    def test_owned_codex_bare_agent_is_recorded(self):
        self.install_codex_agent("backend-developer")
        code, _, err = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a1", agent_type="backend-developer",
        ), self.env, ["start"])
        self.assertEqual(code, 0, err)
        self.assertEqual(self.tasks()[0]["role"], "backend_developer")

    def test_legacy_double_prefixed_claude_agent_is_normalized(self):
        code, _, err = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a1",
            agent_type=("software-engineering-team:"
                        "software-engineering-team-backend-developer"),
        ), self.env, ["start"])
        self.assertEqual(code, 0, err)
        task = self.tasks()[0]
        self.assertEqual(task["role"], "backend_developer")
        self.assertEqual(self.attempts()[0]["agent_name"], "backend-developer")

    def test_unowned_bare_agent_is_ignored(self):
        code, _, err = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a1", agent_type="backend-developer",
        ), self.env, ["start"])
        self.assertEqual(code, 0, err)
        self.assertEqual(self.tasks(), [])

    def test_non_team_agent_is_ignored(self):
        code, _, _ = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a2", agent_type="Explore",
        ), self.env, ["start"])
        self.assertEqual(code, 0)
        self.assertEqual(self.tasks(), [])

    def test_unrelated_cwd_is_ignored(self):
        code, _, _ = run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            cwd=self.tmp.name,
            agent_id="a3", agent_type="software-engineering-team:backend-developer",
        ), self.env, ["start"])
        self.assertEqual(code, 0)
        self.assertEqual(self.tasks(), [])

    def test_session_start_injects_resume_context(self):
        code, out, err = run_hook("hook_session_start.py", self.payload(
            hook_event_name="SessionStart", source="startup",
        ), self.env)
        self.assertEqual(code, 0, err)
        data = json.loads(out)
        context = data["hookSpecificOutput"]["additionalContext"]
        self.assertIn("AGENTROF_HOOKS_ACTIVE: project-management-office", context)
        self.assertIn(f"Current UTC time at session start: {utc_today()}",
                      context)
        self.assertIn("wo1", context)
        self.assertIn("WP-01", context)
        self.assertIn("work order", context)
        launcher = Path(self.env["AGENTROF_HOME"]) / "bin" / "pmo_cli.py"
        self.assertTrue(launcher.is_file())
        dashboard_module = Path(self.env["AGENTROF_HOME"]) / "bin" / "pmo_dashboard.py"
        self.assertTrue(dashboard_module.is_file())
        dashboard_index = Path(self.env["AGENTROF_HOME"]) / "dashboard" / "index.html"
        self.assertTrue(dashboard_index.is_file())

    def test_session_start_clock_only_outside_projects(self):
        code, out, _ = run_hook("hook_session_start.py", self.payload(
            hook_event_name="SessionStart", source="startup", cwd=self.tmp.name,
        ), self.env)
        self.assertEqual(code, 0)
        context = json.loads(out)["hookSpecificOutput"]["additionalContext"]
        self.assertIn(f"Current UTC time at session start: {utc_today()}",
                      context)
        self.assertIn("never from memory", context)
        self.assertNotIn("work order", context)

    def test_session_end_flags_dangling_work_order(self):
        code, _, _ = run_hook("hook_session_end.py", self.payload(
            hook_event_name="SessionEnd", reason="other",
        ), self.env)
        self.assertEqual(code, 0)
        self.assertIn("session_ended_with_active_work_order", self.events())

    def open_second_lane(self):
        """A second project worktree with its own active work order."""
        lane_root = Path(self.tmp.name) / "lane-b"
        (lane_root / "workspace").mkdir(parents=True)
        (lane_root / "workspace" / "config.json").write_text(
            json.dumps({"managed_by": "software-engineering-team", "project_key": "shop"}),
            encoding="utf-8",
        )
        backlog = Path(self.tmp.name) / "backlog-b.json"
        backlog.write_text(json.dumps({
            "epics": [{"external_id": "EP-01", "title": "Core"}],
            "stories": [{
                "external_id": "WP-02", "epic": "EP-01", "title": "Slice two",
                "scope": "s", "excludes": "x", "dor": "d", "dod": "d",
            }],
        }), encoding="utf-8")
        run_cli(["item", "import", "--project-key", "shop",
                 "--json-file", str(backlog)], self.env)
        run_cli(["work-order", "init", "--project-key", "shop",
                 "--work-order-key", "wo-lane-b",
                 "--request", "build", "--worktree", str(lane_root),
                 "--story", "WP-02"], self.env)
        return lane_root

    def test_session_end_ignores_other_worktrees(self):
        """Closing one session flags only ITS worktree's order as dangling;
        healthy parallel lanes stay unflagged."""
        self.open_second_lane()
        code, _, _ = run_hook("hook_session_end.py", self.payload(
            hook_event_name="SessionEnd", reason="other",
        ), self.env)  # cwd = project_root (lane A)
        self.assertEqual(code, 0)
        _, out, _ = run_cli(["resume-info", "--project-key", "shop",
                             "--events", "50", "--json"], self.env)
        dangling = [e for e in json.loads(out)["recent_events"]
                    if e["action"] == "session_ended_with_active_work_order"]
        self.assertEqual(len(dangling), 1)
        self.assertEqual(dangling[0]["payload"].get("current_step"), "0")

    def test_session_start_partitions_lanes(self):
        """Resume context separates this worktree's order from parallel
        lanes elsewhere."""
        lane_root = self.open_second_lane()
        code, out, err = run_hook("hook_session_start.py", self.payload(
            hook_event_name="SessionStart", source="startup",
        ), self.env)  # cwd = project_root (lane A, holds wo1)
        self.assertEqual(code, 0, err)
        context = json.loads(out)["hookSpecificOutput"]["additionalContext"]
        self.assertIn("THIS worktree", context)
        self.assertIn("wo1", context.split("OTHER worktrees")[0])
        self.assertIn("OTHER worktrees", context)
        self.assertIn("wo-lane-b", context.split("OTHER worktrees")[1])
        self.assertIn("delivery-lanes entry", context)

    def attempts(self):
        import sqlite3
        con = sqlite3.connect(Path(self.env["AGENTROF_HOME"]) / "agentrof.db")
        con.row_factory = sqlite3.Row
        rows = [dict(r) for r in con.execute(
            "SELECT * FROM task_attempts ORDER BY attempt")]
        con.close()
        return rows

    def test_subagent_lifecycle_records_attempts(self):
        run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart",
            agent_id="a1", agent_type="software-engineering-team:backend-developer",
        ), self.env, ["start"])
        first = self.attempts()
        self.assertEqual(len(first), 1)
        self.assertEqual(first[0]["outcome"], "running")
        self.assertEqual(first[0]["session_id"], "s1")
        self.assertEqual(first[0]["agent_name"], "backend-developer")
        # a second dispatch before the first stop supersedes the dangling one
        run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStart", session_id="s2",
            agent_id="a2", agent_type="software-engineering-team:backend-developer",
        ), self.env, ["start"])
        run_hook("hook_subagent.py", self.payload(
            hook_event_name="SubagentStop", session_id="s2",
            agent_id="a2", agent_type="software-engineering-team:backend-developer",
        ), self.env, ["stop"])
        attempts = self.attempts()
        self.assertEqual(len(attempts), 2)
        self.assertEqual(attempts[0]["outcome"], "failed")
        self.assertIn("superseded", attempts[0]["failure_reason"])
        self.assertEqual(attempts[1]["outcome"], "done")
        self.assertTrue(attempts[1]["finished_at"])
        self.assertIn("attempt_started", self.events())
        self.assertIn("attempt_finished", self.events())

    def test_guard_denies_db_writes_and_allows_others(self):
        db = Path(self.env["AGENTROF_HOME"]) / "agentrof.db"
        for target in (db, Path(str(db) + "-wal")):
            code, _, err = run_hook("hook_guard_db.py", self.payload(
                hook_event_name="PreToolUse", tool_name="Write",
                tool_use_id="t1",
                tool_input={"file_path": str(target), "content": "x"},
            ), self.env)
            self.assertEqual(code, 2)
            self.assertIn("PMO CLI", err)
        code, _, _ = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write",
            tool_use_id="t2",
            tool_input={"file_path": str(self.project_root / "a.txt"),
                        "content": "x"},
        ), self.env)
        self.assertEqual(code, 0)

    def guard(self, path: Path, tool="Write"):
        return run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name=tool, tool_use_id="tg",
            tool_input={"file_path": str(path), "content": "x"},
        ), self.env)

    def guard_patch(self, patch: str):
        return run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="apply_patch", tool_use_id="tp",
            tool_input={"patch": patch},
        ), self.env)

    def test_apply_patch_enforces_generated_frozen_and_stamp_guards(self):
        docs = self.project_root / "workspace" / "docs"
        generated = docs / "generated.md"
        generated.parent.mkdir(parents=True, exist_ok=True)
        generated.write_text(
            "<!-- generated by vault_check render; do not edit by hand -->\n# View\n",
            encoding="utf-8")
        patch = "\n".join([
            "*** Begin Patch", f"*** Update File: {generated}", "@@",
            "-# View", "+# Changed", "*** End Patch",
        ])
        code, _, err = self.guard_patch(patch)
        self.assertEqual(code, 2)
        self.assertIn("GENERATED view", err)

        frozen_rel = "workspace/docs/business-analysis/core.md"
        frozen = self.project_root / frozen_rel
        frozen.parent.mkdir(parents=True)
        frozen.write_text("# Core\n", encoding="utf-8")
        orders = self.project_root / "workspace" / "work-orders" / "wo1"
        orders.mkdir(parents=True)
        (orders / "freeze.json").write_text(
            json.dumps({"frozen_paths": [frozen_rel]}), encoding="utf-8")
        patch = "\n".join([
            "*** Begin Patch", f"*** Update File: {frozen}", "@@",
            "-# Core", "+# Changed", "*** End Patch",
        ])
        code, _, err = self.guard_patch(patch)
        self.assertEqual(code, 2)
        self.assertIn("frozen", err)

        stamped = docs / "new-rule.md"
        patch = "\n".join([
            "*** Begin Patch", f"*** Add File: {stamped}", "+---",
            "+approved_at: 2026-01-01", "+---", "+# Rule", "*** End Patch",
        ])
        code, _, err = self.guard_patch(patch)
        self.assertEqual(code, 2)
        self.assertIn("clock-owned", err)

    def test_guard_denies_marker_family_and_generated_dir(self):
        """The generated-by marker is a family: any generator's views are
        protected, and everything under a _generated directory is denied
        even before the file exists."""
        docs = self.project_root / "workspace" / "docs"
        space = docs / "business-analysis" / "erp"
        generated = space / "_generated"
        generated.mkdir(parents=True)
        view = space / "compiled-elsewhere.md"
        view.write_text(
            "<!-- generated by ba_compile render; do not edit by hand -->\n# X\n",
            encoding="utf-8",
        )
        code, _, err = self.guard(view, tool="Edit")
        self.assertEqual(code, 2)
        self.assertIn("GENERATED view", err)
        self.assertIn("ba_compile", err)
        code, _, err = self.guard(generated / "registry.json")
        self.assertEqual(code, 2)
        self.assertIn("_generated", err)

    def test_guard_denies_frozen_paths_of_active_orders_only(self):
        """A freeze manifest binds while its work order is active; a manifest
        naming an unknown or inactive order does not deny."""
        frozen_rel = "workspace/docs/business-analysis/erp/rules/core.md"
        frozen = self.project_root / frozen_rel
        frozen.parent.mkdir(parents=True)
        frozen.write_text("| BR-ERP-001 |\n", encoding="utf-8")
        orders = self.project_root / "workspace" / "work-orders"
        (orders / "wo1").mkdir(parents=True)  # wo1 is active from setUp
        (orders / "wo1" / "freeze.json").write_text(
            json.dumps({"frozen_paths": [frozen_rel]}), encoding="utf-8")
        code, _, err = self.guard(frozen)
        self.assertEqual(code, 2)
        self.assertIn("frozen", err)
        self.assertIn("wo1", err)
        # a bare-list manifest for a ghost order never binds
        (orders / "wo1" / "freeze.json").unlink()
        (orders / "wo-ghost").mkdir()
        (orders / "wo-ghost" / "freeze.json").write_text(
            json.dumps([frozen_rel]), encoding="utf-8")
        code, _, _ = self.guard(frozen)
        self.assertEqual(code, 0)

    def test_guard_denies_locked_records(self):
        record = self.project_root / "workspace" / "round-1.md"
        record.write_text(
            "---\ntype: challenge_record\nlocked: true\n---\n# Round 1\n",
            encoding="utf-8",
        )
        code, _, err = self.guard(record, tool="Edit")
        self.assertEqual(code, 2)
        self.assertIn("locked", err)
        # the deny names the ONE sanctioned exception: the audited
        # designation relabel through the reconcile verb
        self.assertIn("reconcile-designations --include-locked", err)
        record.write_text(
            "---\ntype: challenge_record\nlocked: false\n---\n# Round 1\n",
            encoding="utf-8",
        )
        code, _, _ = self.guard(record, tool="Edit")
        self.assertEqual(code, 0)

    def test_guard_denies_hand_stamped_dates(self):
        """Stamp fields are script-owned: any stamp date the model
        introduces by hand is denied, today's included; stamps already in
        the on-disk file pass (rewrites, restructures)."""
        doc = self.project_root / "workspace" / "docs" / "rules.md"
        doc.parent.mkdir(parents=True, exist_ok=True)
        stale = "---\nstatus: approved\napproved_at: 2025-01-01\n---\n# R\n"
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="d1",
            tool_input={"file_path": str(doc), "content": stale},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("owning verb", err)
        # Today's date typed by hand is denied too: the value is not the
        # point, the writer is.
        fresh = stale.replace("2025-01-01", utc_today())
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="d2",
            tool_input={"file_path": str(doc), "content": fresh},
        ), self.env)
        self.assertEqual(code, 2)
        # A stamp already in the on-disk file is not "introduced": full
        # rewrites and Edits that relocate it pass.
        doc.write_text(stale, encoding="utf-8")
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="d3",
            tool_input={"file_path": str(doc), "content": stale + "\nMore.\n"},
        ), self.env)
        self.assertEqual(code, 0, err)
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Edit", tool_use_id="d4",
            tool_input={"file_path": str(doc), "old_string": "# R",
                        "new_string": "# R\napproved_at: 2025-01-01"},
        ), self.env)
        self.assertEqual(code, 0, err)
        # An Edit introducing a stamp the file does not hold is denied.
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Edit", tool_use_id="d5",
            tool_input={"file_path": str(doc), "old_string": "# R",
                        "new_string": "Status: approved 2024-12-31"},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("owning verb", err)
        # decided_at is a clock-owned field too (vault_check stamp-decision).
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Edit", tool_use_id="d6",
            tool_input={"file_path": str(doc), "old_string": "# R",
                        "new_string": "decided_at: 2026-01-05"},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("stamp-decision", err)
        # Outside a managed project the stamp family does not apply.
        outside = Path(self.tmp.name) / "elsewhere" / "workspace" / "n.md"
        outside.parent.mkdir(parents=True)
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="d6",
            cwd=str(outside.parent.parent),
            tool_input={"file_path": str(outside), "content": stale},
        ), self.env)
        self.assertEqual(code, 0, err)

    def test_guard_denies_non_ascii_workspace_paths(self):
        target = self.project_root / "workspace" / "docs" / "müşteri.md"
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="l1",
            tool_input={"file_path": str(target), "content": "x"},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("English", err)
        ascii_target = self.project_root / "workspace" / "docs" / "customer.md"
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="l2",
            tool_input={"file_path": str(ascii_target), "content": "x"},
        ), self.env)
        self.assertEqual(code, 0, err)

    def test_guard_allows_configured_language_in_md_bodies(self):
        doc = self.project_root / "workspace" / "docs" / "analysis.md"
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Write", tool_use_id="l3",
            tool_input={"file_path": str(doc),
                        "content": "# Analiz\n\nMüşteri kuralı.\n\n"
                                   "```mermaid\nflowchart TD\n"
                                   "    A[Müşteri fatura oluşturur] --> B[Onay]\n"
                                   "```\n"},
        ), self.env)
        self.assertEqual(code, 0, err)

    def test_guard_denies_non_ascii_commit_messages(self):
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b1",
            tool_input={"command":
                        'git commit -m "müşteri modülü"'},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("English", err)
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b2",
            tool_input={"command": 'git commit -m "add customer module"'},
        ), self.env)
        self.assertEqual(code, 0, err)
        # Non-ASCII in a non-commit command is not this guard's business.
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b3",
            tool_input={"command": 'echo "müşteri"'},
        ), self.env)
        self.assertEqual(code, 0, err)
        # A compound command writing configured-language .md content with
        # an English message passes: only the -m payload is judged.
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b4",
            tool_input={"command":
                        'printf "Müşteri kuralı\\n" >> workspace/docs/a.md'
                        ' && git commit -am "extend analysis"'},
        ), self.env)
        self.assertEqual(code, 0, err)
        # Global git options and combined short flags do not hide the
        # commit message from the guard.
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b5",
            tool_input={"command": 'git -C . commit -m "müşteri modülü"'},
        ), self.env)
        self.assertEqual(code, 2)
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b6",
            tool_input={"command": 'git commit -am "müşteri modülü"'},
        ), self.env)
        self.assertEqual(code, 2)

    def write_config(self, **extra):
        (self.project_root / "workspace" / "config.json").write_text(
            json.dumps({"managed_by": "software-engineering-team",
                        "project_key": "shop", **extra}),
            encoding="utf-8",
        )

    def test_guard_commit_language_follows_terminology_config(self):
        self.write_config(terminology_language="Turkish")
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b7",
            tool_input={"command": 'git commit -m "müşteri modülü"'},
        ), self.env)
        self.assertEqual(code, 0, err)

    def test_guard_commit_fail_closes_on_malformed_config(self):
        (self.project_root / "workspace" / "config.json").write_text(
            "{not json", encoding="utf-8")
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="b8",
            tool_input={"command": 'git commit -m "müşteri modülü"'},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("English", err)

    def test_guard_gh_pr_payloads_follow_terminology_config(self):
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="p1",
            tool_input={"command":
                        'gh pr create --title "müşteri modülü" --body "ok"'},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("terminology_language", err)
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="p2",
            tool_input={"command":
                        'gh pr create --title "customer module" --body "adds it"'},
        ), self.env)
        self.assertEqual(code, 0, err)
        # A non-pr gh command is not judged.
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="p3",
            tool_input={"command": 'gh issue create --title "müşteri"'},
        ), self.env)
        self.assertEqual(code, 0, err)
        self.write_config(terminology_language="Turkish")
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="p4",
            tool_input={"command": 'gh pr create --body "müşteri akışı"'},
        ), self.env)
        self.assertEqual(code, 0, err)

    def test_guard_denies_non_ascii_branch_names_always(self):
        # Branches are machine layer: a configured non-English
        # terminology_language never admits a non-ASCII branch name.
        self.write_config(terminology_language="Turkish")
        for i, command in enumerate((
                'git checkout -b wp-03-fatura-düzeltme',
                'git switch -c düzeltme',
                'git branch özellik',
                'git worktree add ../lane -b düzeltme-2')):
            code, _, err = run_hook("hook_guard_db.py", self.payload(
                hook_event_name="PreToolUse", tool_name="Bash",
                tool_use_id=f"br{i}", tool_input={"command": command},
            ), self.env)
            self.assertEqual(code, 2, command)
            self.assertIn("machine-layer", err)
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Bash", tool_use_id="br9",
            tool_input={"command": 'git checkout -b wp-03-invoice-fix'},
        ), self.env)
        self.assertEqual(code, 0, err)

    def test_guard_denies_generated_view_edits(self):
        docs = self.project_root / "workspace" / "docs"
        docs.mkdir(parents=True, exist_ok=True)
        (docs / "decision-log.md").write_text(
            "<!-- generated by vault_check render-decisions; do not edit by"
            " hand -->\n\n# Decision Log\n\n| planned |\n", encoding="utf-8")
        code, _, err = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Edit",
            tool_use_id="t3",
            tool_input={"file_path": str(docs / "decision-log.md"),
                        "old_string": "planned", "new_string": "done"},
        ), self.env)
        self.assertEqual(code, 2)
        self.assertIn("GENERATED view", err)
        (docs / "notes.md").write_text("# Notes\n", encoding="utf-8")
        code, _, _ = run_hook("hook_guard_db.py", self.payload(
            hook_event_name="PreToolUse", tool_name="Edit",
            tool_use_id="t4",
            tool_input={"file_path": str(docs / "notes.md"),
                        "old_string": "Notes", "new_string": "Team notes"},
        ), self.env)
        self.assertEqual(code, 0)


if __name__ == "__main__":
    unittest.main()
