"""Unit tests for the software-engineering-team file-facing checks."""

import importlib.util
import io
import sys
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCRIPTS = REPO / "plugins" / "software-engineering-team" / "scripts"
# Scripts import same-directory siblings (landscape_check reads
# ba_compile's frontmatter parser); running them as files gets this for
# free, the importlib loader needs the path spelled out.
sys.path.insert(0, str(SCRIPTS))


def load(name: str):
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


artifact_check = load("artifact_check")
landscape_check = load("landscape_check")
design_system_compile = load("design_system_compile")


def run(module, argv):
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        try:
            code = module.main(argv)
        except SystemExit as exc:
            code = exc.code if isinstance(exc.code, int) else 1
    return code, out.getvalue(), err.getvalue()


class ArtifactCheckTests(unittest.TestCase):
    def test_missing_sections_fail(self):
        with tempfile.TemporaryDirectory() as tmp:
            f = Path(tmp) / "a.md"
            f.write_text("# Title\n\n## Purpose\ntext\n", encoding="utf-8")
            code, _, err = run(artifact_check, [
                "--path", str(f), "--require-sections", "Purpose,Business Rules",
            ])
            self.assertEqual(code, 1)
            self.assertIn("Business Rules", err)
            code, _, _ = run(artifact_check, ["--path", str(f), "--require-sections", "Purpose"])
            self.assertEqual(code, 0)

    def test_empty_artifact_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            f = Path(tmp) / "a.md"
            f.write_text("  \n", encoding="utf-8")
            code, _, _ = run(artifact_check, ["--path", str(f)])
            self.assertEqual(code, 1)


class LandscapeCheckTests(unittest.TestCase):
    SD1 = (
        "---\ntype: decision\ntitle: Baseline decision\nstatus: accepted\n"
        "tags:\n  - doc/decision\n  - status/accepted\n"
        "aliases:\n  - SD-001\n---\n\n# Baseline decision\n"
    )
    SD2 = (
        "---\ntype: decision\ntitle: Superseded queue decision\nstatus: superseded\n"
        "tags:\n  - doc/decision\n  - status/superseded\n"
        "aliases:\n  - SD-002\n---\n\n# Superseded queue decision\n"
    )
    INDEX = (
        "<!-- generated by vault_check render-decisions; do not edit by"
        " hand -->\n\n# Decision Log\n"
    )
    LAND_OK = (
        "# Landscape\n\n## Summary\nok\n\n## Current\nx\n\n## Target\n"
        "Adopt queue (SD-001)\n\n## Transition\n\n## Components\n"
        "| component | verdict | decision | engagement | status |\n|---|---|---|---|---|\n"
        "| queue | buy | [[solution-design/decisions/baseline-decision\\|SD-001]] |"
        " [q](engagements/q.md) | decided |\n"
    )

    def _tree(self, tmp, land, engagement=None, notes=None, index=None):
        tree = Path(tmp) / "solution-design"
        (tree / "engagements").mkdir(parents=True)
        (tree / "decisions").mkdir()
        for name, text in (notes if notes is not None else {
            "baseline-decision.md": self.SD1,
            "superseded-queue-decision.md": self.SD2,
        }).items():
            (tree / "decisions" / name).write_text(text, encoding="utf-8")
        (tree / "decision-log.md").write_text(
            index if index is not None else self.INDEX, encoding="utf-8")
        (tree / "landscape.md").write_text(land, encoding="utf-8")
        if engagement is not None:
            (tree / "engagements" / "q.md").write_text(engagement, encoding="utf-8")
        return str(tree)

    def test_consistent_tree_passes(self):
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, self.LAND_OK,
                "# Q\n\n## Summary\nStatus: approved 2026-07-13\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n")
            code, _, _ = run(landscape_check, ["--tree", tree])
            self.assertEqual(code, 0)


    def test_non_ascii_component_fails(self):
        land = self.LAND_OK.replace("| queue |", "| mesaj kuyruğu |")
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(tmp, land)
            code, _, err = run(landscape_check, ["--tree", tree])
            self.assertEqual(code, 1)
            self.assertIn("non-ASCII", err)

    def test_superseded_citation_fails(self):
        land = self.LAND_OK.replace(
            "baseline-decision\\|SD-001", "superseded-queue-decision\\|SD-002")
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(tmp, land)
            code, _, err = run(landscape_check, ["--tree", tree])
            self.assertEqual(code, 1)
            self.assertIn("superseded", err)

    def test_statusless_note_and_bad_status_line_fail(self):
        notes = {
            "baseline-decision.md": self.SD1.replace("status: accepted\n", ""),
            "superseded-queue-decision.md": self.SD2,
        }
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, self.LAND_OK,
                "# Q\n\n## Summary\napproved someday\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n",
                notes=notes)
            code, _, err = run(landscape_check, ["--tree", tree])
            self.assertEqual(code, 1)
            self.assertIn("no status", err)
            self.assertIn("Status line", err)

    def test_unrendered_index_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(tmp, self.LAND_OK, index="# Decision Log\n")
            code, _, err = run(landscape_check, ["--tree", tree])
            self.assertEqual(code, 1)
            self.assertIn("generated marker", err)

    def test_stamp_engagement_writes_utc_today_and_checks(self):
        from datetime import datetime, timezone
        today = datetime.now(timezone.utc).date().isoformat()
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, self.LAND_OK,
                "# Q\n\n## Summary\nStatus: open\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n")
            code, _, err = run(landscape_check, [
                "--tree", tree, "--stamp-engagement", "q",
                "--status", "approved"])
            self.assertEqual(code, 0, err)
            text = (Path(tree) / "engagements" / "q.md").read_text(
                encoding="utf-8")
            self.assertIn(f"Status: approved {today}", text)

    def test_future_status_date_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, self.LAND_OK,
                "# Q\n\n## Summary\nStatus: approved 9999-01-01\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n")
            code, _, err = run(landscape_check, ["--tree", tree])
            self.assertEqual(code, 1)
            self.assertIn("clock", err)

    def test_stamp_missing_engagement_is_usage_error(self):
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(tmp, self.LAND_OK)
            code, _, err = run(landscape_check, [
                "--tree", tree, "--stamp-engagement", "nope",
                "--status", "approved"])
            self.assertEqual(code, 2, err)

    def test_stamp_parked_requires_reason(self):
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(tmp, self.LAND_OK)
            code, _, err = run(landscape_check, [
                "--tree", tree, "--stamp-engagement", "q",
                "--status", "parked"])
            self.assertEqual(code, 2, err)

    def test_stamp_can_reopen_approved_engagement_without_lock_state(self):
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, self.LAND_OK,
                "# Q\n\n## Summary\nStatus: approved 2026-07-01\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n")
            code, _, err = run(landscape_check, [
                "--tree", tree, "--stamp-engagement", "q",
                "--status", "open"])
            self.assertEqual(code, 0, err)
            text = (Path(tree) / "engagements" / "q.md").read_text(
                encoding="utf-8")
            self.assertIn("Status: open", text)

    def test_stamp_refuses_non_status_first_line(self):
        """The stamp replaces a Status line only; prose is never
        clobbered."""
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, self.LAND_OK,
                "# Q\n\n## Summary\nThe caching question, still framed.\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n")
            code, _, err = run(landscape_check, [
                "--tree", tree, "--stamp-engagement", "q",
                "--status", "approved"])
            self.assertEqual(code, 2, err)
            text = (Path(tree) / "engagements" / "q.md").read_text(
                encoding="utf-8")
            self.assertIn("The caching question, still framed.", text)

    def test_stamp_rolls_back_when_tree_check_fails(self):
        """A stamp never survives a failing tree: the original Status
        line is restored before the FAIL exit."""
        land_bad = self.LAND_OK.replace("Adopt queue (SD-001)",
                                        "Adopt queue with no citation")
        with tempfile.TemporaryDirectory() as tmp:
            tree = self._tree(
                tmp, land_bad,
                "# Q\n\n## Summary\nStatus: open\n\n"
                "## Framing\nf\n\n## Options\no\n\n## Verdict\nv\n")
            code, _, err = run(landscape_check, [
                "--tree", tree, "--stamp-engagement", "q",
                "--status", "approved"])
            self.assertEqual(code, 1, err)
            self.assertIn("rolled back", err)
            text = (Path(tree) / "engagements" / "q.md").read_text(
                encoding="utf-8")
            self.assertIn("Status: open", text)
            self.assertNotIn("Status: approved", text)


class DesignSystemCompileTests(unittest.TestCase):
    MASTER = (
        "---\ntype: design_master\ntitle: Product design system\n"
        "status: draft\nrevision: 1\ntags:\n"
        "  - doc/design-master\n  - status/draft\naliases:\n"
        "  - Design System\n---\n\n# Product design system\n\nBaseline.\n"
    )

    def test_approve_and_revision_keep_status_tag_and_hash_contract_aligned(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            master = root / "MASTER.md"
            master.write_text(self.MASTER, encoding="utf-8")

            code, _, err = run(
                design_system_compile, ["approve", "--root", str(root)]
            )
            self.assertEqual(code, 0, err)
            approved = master.read_text(encoding="utf-8")
            self.assertIn("status: approved", approved)
            self.assertIn("  - status/approved", approved)
            self.assertNotIn("status/draft", approved)
            code, _, err = run(
                design_system_compile, ["check", "--root", str(root)]
            )
            self.assertEqual(code, 0, err)

            code, _, err = run(
                design_system_compile,
                ["begin-revision", "--root", str(root)],
            )
            self.assertEqual(code, 0, err)
            revised = master.read_text(encoding="utf-8")
            self.assertIn("status: draft", revised)
            self.assertIn("  - status/draft", revised)
            self.assertIn("supersedes_hash: sha256:", revised)
            self.assertIn("contract_version: 3", revised)
            self.assertNotIn("baseline_hash:", revised)
            code, _, err = run(
                design_system_compile, ["check", "--root", str(root)]
            )
            self.assertEqual(code, 1, err)

    @staticmethod
    def v3_master() -> str:
        return (
            "---\ntype: design_master\ntitle: Product design system\n"
            "status: draft\nrevision: 1\ncontract_version: 3\ntags:\n"
            "  - doc/design-master\n  - status/draft\n---\n\n"
            "# Product design system\n\n"
            "## Product position\n\nPosition.\n\n"
            "## Brand and asset fidelity\n\nNo supplied identity asset.\n\n"
            "## Global rules\n\n### Catalog tokens\n\n"
            "<!-- catalog:tokens:start -->\n```css\n:root { --catalog-background: #fff; }\n"
            "```\n<!-- catalog:tokens:end -->\n\n"
            "## Component specs\n\nSpecs.\n\n## Style guidelines\n\nRules.\n\n"
            "## Anti-patterns\n\nAvoid.\n\n## Pre-delivery checklist\n\nCheck.\n\n"
            "## Navigation\n\n[[maps/design-system|Design System]]\n"
        )

    def test_catalog_init_sync_and_staleness_are_mechanical(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            master = root / "MASTER.md"
            master.write_text(self.v3_master(), encoding="utf-8")
            code, _, err = run(design_system_compile, [
                "init-catalog", "--root", str(root),
            ])
            self.assertEqual(code, 0, err)
            self.assertTrue((root / "artifacts" / "standalone.html").is_file())
            self.assertTrue(design_system_compile.catalog_findings(root))
            catalog = root / "artifacts" / "standalone.html"
            catalog.write_text(
                catalog.read_text(encoding="utf-8").replace("AUTHOR_REQUIRED", "Filled"),
                encoding="utf-8",
            )
            self.assertEqual(design_system_compile.catalog_findings(root), [])
            master.write_text(
                master.read_text(encoding="utf-8").replace("#fff", "#fefefe"),
                encoding="utf-8",
            )
            stale = design_system_compile.catalog_findings(root)
            self.assertIn("catalog token block does not match MASTER.md", stale)
            code, _, err = run(design_system_compile, [
                "sync-catalog", "--root", str(root),
            ])
            self.assertEqual(code, 0, err)
            self.assertEqual(design_system_compile.catalog_findings(root), [])

    def test_design_system_persistence_creates_master_and_catalog_skeleton_together(self):
        script_dir = REPO / "plugins/software-engineering-team/skill-content/ui-ux-design/scripts"
        sys.path.insert(0, str(script_dir))
        try:
            spec = importlib.util.spec_from_file_location(
                "ui_ux_design_system", script_dir / "design_system.py")
            module = importlib.util.module_from_spec(spec)
            assert spec.loader is not None
            spec.loader.exec_module(module)
        finally:
            sys.path.remove(str(script_dir))
        design = {
            "project_name": "Atlas", "category": "General", "colors": {},
            "colors_dark": {}, "typography": {}, "radius": {}, "motion": {},
            "pattern": {}, "style": {}, "icon_set": "Local icons",
        }
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "design-system"
            result = module.persist_design_system(design, output_dir=str(output))
            self.assertIn(str(output / "MASTER.md"), result["created_files"])
            self.assertIn(str(output / "artifacts" / "standalone.html"), result["created_files"])
            self.assertIn("contract_version: 3", (output / "MASTER.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
