"""Portable project-instruction reconciliation and workspace contracts."""

from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SHARED = ROOT / "platforms/shared/_team/overlay/scripts/project_instructions.py"
CODEX_PACKAGE = ROOT / "dist/codex/software-engineering-team"


def load_module():
    spec = importlib.util.spec_from_file_location("project_instructions_test", SHARED)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


class ProjectInstructionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.contract = load_module()

    def test_internal_workspace_api_accepts_only_canonical_path(self):
        self.assertEqual(self.contract.validate_workspace("workspace"), "workspace")
        for value in ("other", "work-space", "Workspace", "../workspace", ""):
            with self.subTest(value=value), self.assertRaisesRegex(
                self.contract.ProjectInstructionError, "use 'workspace'"
            ):
                self.contract.validate_workspace(value)

    def test_unmanaged_root_requires_an_explicit_choice_without_writes(self):
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            root = project / "AGENTS.override.md"
            root.write_text("# User instructions\n", encoding="utf-8")
            result = self.contract.plan_project_files(
                project, CODEX_PACKAGE, "codex", "workspace"
            )
            self.assertEqual(root.read_text(encoding="utf-8"), "# User instructions\n")
            self.assertEqual(len(result["choice_requests"]), 1)
            self.assertEqual(result["choice_requests"][0]["reason"], "unmanaged_content")

    def test_preserve_moves_user_content_to_companion(self):
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            (project / "AGENTS.override.md").write_text(
                "# User instructions\n\nKeep this.\n", encoding="utf-8"
            )
            request = "codex.root.agents.override"
            plan = self.contract.plan_project_files(
                project, CODEX_PACKAGE, "codex", "workspace",
                choices={request: "preserve"}, seed_user_files=True,
            )
            self.contract.apply_changes(plan["changes"])
            generated = (project / "AGENTS.override.md").read_text(encoding="utf-8")
            companion = (project / "AGENTS.user.md").read_text(encoding="utf-8")
            self.assertTrue(generated.startswith("<!-- generated by agent-marketplace"))
            self.assertIn("Keep this.", companion)
            self.assertNotIn("Keep this.", generated)

    def test_unmanaged_codex_override_is_preserved_only_after_an_explicit_choice(self):
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            override = project / "AGENTS.override.md"
            override.write_text("Reserved content\n", encoding="utf-8")
            plan = self.contract.plan_project_files(
                project, CODEX_PACKAGE, "codex", "workspace",
                choices={"codex.root.agents.override": "preserve"},
            )
            self.contract.apply_changes(plan["changes"])
            self.assertTrue(override.exists())
            self.assertTrue(override.read_text(encoding="utf-8").startswith(
                "<!-- generated by agent-marketplace"
            ))
            self.assertIn(
                "Reserved content",
                (project / "AGENTS.user.md").read_text(encoding="utf-8"),
            )

    def test_apply_changes_rolls_back_every_prior_write(self):
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            first = project / "first.md"
            second = project / "second.md"
            first.write_text("before\n", encoding="utf-8")

            def failing_writer(path: Path, content: str) -> None:
                if path == second:
                    raise OSError("injected failure")
                self.contract.atomic_write(path, content)

            with self.assertRaisesRegex(OSError, "injected failure"):
                self.contract.apply_changes(
                    {first: "after\n", second: "created\n"},
                    writer=failing_writer,
                )
            self.assertEqual(first.read_text(encoding="utf-8"), "before\n")
            self.assertFalse(second.exists())

    def test_symlinked_managed_root_is_rejected(self):
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            source = project / "source.md"
            source.write_text("user\n", encoding="utf-8")
            (project / "AGENTS.override.md").symlink_to(source)
            with self.assertRaisesRegex(
                self.contract.ProjectInstructionError, "symbolic link"
            ):
                self.contract.plan_project_files(
                    project, CODEX_PACKAGE, "codex", "workspace"
                )

    def test_portable_project_plan_renders_each_supported_host_surface(self):
        with tempfile.TemporaryDirectory() as temporary:
            project = Path(temporary)
            plan = self.contract.plan_portable_project_files(
                project, CODEX_PACKAGE, "workspace", seed_user_files=True
            )
            self.assertEqual(plan["choice_requests"], [])
            self.contract.apply_changes(plan["changes"])
            self.assertIn(
                "for claude;", (project / "CLAUDE.md").read_text(encoding="utf-8")
            )
            self.assertIn(
                "for codex;",
                (project / "AGENTS.override.md").read_text(encoding="utf-8"),
            )


if __name__ == "__main__":
    unittest.main()
