"""A real headless Requirement reaches the approved Delivery input boundary."""

import contextlib
import io
import subprocess
import unittest
from tools.tests.levels import integration

from tools.tests import backlog_fixture
from tools.tests import test_backlog_requirement_bindings as requirement_fixture
from tools.tests import test_ba_compile as ba_fixture
from tools.tests.git_fixture import init_repository

import delivery_compile
import landscape_check


compiler = backlog_fixture.backlog_compile
requirement = compiler.requirement_compile
stage_package = compiler.stage_package


@integration
class HeadlessBacklogHandoffTests(unittest.TestCase):
    setUp = requirement_fixture.RequirementBindingTests.setUp

    def commit(self, message):
        for args in (["add", "-A"], ["-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid",
                                      "commit", "-q", "-m", message]):
            subprocess.run(["git", *args], cwd=self.project, check=True, capture_output=True)

    def cli(self, *args):
        output, error = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(output), contextlib.redirect_stderr(error):
            code = compiler.main([*args, "--docs", str(self.docs)])
        return code, output.getvalue() + error.getvalue()

    def assert_cli(self, *args):
        code, output = self.cli(*args)
        self.assertEqual(code, 0, output)

    def write_note(self, relative, props, body="# Note\n"):
        path = self.docs / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(compiler.front_matter(props, body), encoding="utf-8")
        return path

    def approve_worker_solution(self):
        tree = self.docs / "solution-design"
        self.write_note("solution-design/landscape.md", {
            "type": "landscape", "package_status": "draft", "topology_selected": True,
        }, "# Landscape\n\n## Target\n\nSD-001 supplies the inventory worker runtime.\n"
           "\n## Transition\n\nDeploy the digest acquisition worker.\n\n## Components\n\n"
           "| component | verdict | decision |\n|---|---|---|\n"
           "| inventory-worker | accepted | [[solution-design/decisions/runtime-decision\\|SD-001]] "
           "and [[solution-design/decisions/environment-decision\\|SD-002]] |\n")
        self.write_note("solution-design/components/inventory-worker/component.md", {
            "type": "solution-component", "component_id": "inventory-worker",
            "component_class": "application", "sourcing": "build", "app_kind": "worker",
            "code_path": "workspace/apps/inventory-worker",
            "owned_ba_refs": sorted(landscape_check.ba_process_universe(tree)),
            "technology_bindings": ["solution-design/decisions/runtime-decision",
                                    "solution-design/decisions/environment-decision"],
            "data_store_disposition": "not_applicable",
        })
        for slug, identifier, kind, technology in (
            ("runtime", "SD-001", "technology-selection", "python"),
            ("environment", "SD-002", "environment", "docker"),
        ):
            self.write_note(f"solution-design/decisions/{slug}-decision.md", {
                "type": "decision", "status": "accepted", "aliases": [identifier],
                "decision_kind": kind, "applies_to": ["inventory-worker"],
                "selected_technology": technology, "method_skills": [],
            })
        (tree / "decision-log.md").write_text("<!-- generated by test -->\n", encoding="utf-8")
        for command in ("confirm-topology", "approve"):
            output, error = io.StringIO(), io.StringIO()
            with contextlib.redirect_stdout(output), contextlib.redirect_stderr(error):
                code = landscape_check.main([command, "--tree", str(tree)])
            self.assertEqual(code, 0, output.getvalue() + error.getvalue())

    def author_reviews(self):
        root_review = self.docs / "backlog/reviews/round-1-backlog-review.md"
        epic_review = self.docs / "backlog/epics/worker/reviews/round-1-epic-review.md"
        for path, relations, sections, coverage_rows in (
            (root_review, {"related_to": ["[[backlog/epics/worker/epic|EP-001]]"]},
             compiler.backlog_review_sections("requirement"), ("| REQ-001 | ST-001 | covered |",)),
            (epic_review, {
                "verifies": ["[[backlog/epics/worker/stories/acquire/story|ST-001]]",
                             "[[backlog/epics/worker/stories/acquire/test-plan|ST-001-TP]]"],
                "scenario_refs": ["ST-001-TS-001"],
            }, compiler.backlog_contract()["required_epic_review_sections"], ()),
        ):
            props, _body = compiler.parse_front_matter(path)
            props.update(verdict="approved", dependency_refs=[], **relations)
            path.write_text(compiler.front_matter(props, backlog_fixture._complete_review_body(
                props["title"], sections, coverage_rows)), encoding="utf-8")

    def test_real_headless_intake_approval_delivery_snapshot_and_revision(self):
        # Both packages pass their real modern compilers and Git commitment
        # gates. No receipt, approval, routing or absence check is mocked.
        space = self.docs / "business-analysis/erp"
        ba_fixture.make_valid_space(space)
        code, output, error = ba_fixture.run([
            "approve-package", "--space", str(space), "--vault-root", str(self.docs),
        ])
        self.assertEqual(code, 0, output + error)
        self.approve_worker_solution()
        req = requirement_fixture.RequirementBindingTests.requirement(self, {
            "business-analysis": "required", "solution-design": "required", "backlog": "required",
        })
        init_repository(self.project)
        self.commit("Approve headless inputs and Requirement")
        for stage, reference in (
            ("business-analysis", "business-analysis/erp/space"),
            ("solution-design", "solution-design/landscape"),
        ):
            receipt, errors = stage_package.verify(
                self.docs, stage, reference, require_committed=True, require_strict_current=True)
            self.assertEqual(errors, [])
            self.assertEqual(receipt["verification_profile"], "strict-current")
            requirement.bind_stage(req, stage, reference)
        self.commit("Bind exact approved Requirement inputs")
        self.assertEqual(compiler.requirement_route.route(self.docs, "REQ-001")["action"], "backlog")
        flags = ["--planning-mode", "requirement", "--requirement-ref", "REQ-001",
                 "--absent-input", "design-system", "--absent-input", "experience-design"]
        self.assert_cli("init", *flags)
        _props, scaffold = compiler.parse_front_matter(self.docs / "backlog/reviews/round-1-backlog-review.md")
        self.assertEqual(compiler.section(scaffold, compiler.REQUIREMENT_COVERAGE),
                         "| requirement | story_ids | disposition |\n|---|---|---|")
        self.assert_cli("stub-epic", "worker", "--id", "EP-001", "--goal",
                        "Acquire exact inventory artifact digests without a visual interface.")
        self.assert_cli("stub-story", "worker", "acquire", "--id", "ST-001",
                        "--work-kind", "technical", "--scope", "Acquire the selected artifact digest.",
                        "--evidence-ref", "[[solution-design/decisions/runtime-decision|SD-001]]",
                        "--constrained-by", "[[solution-design/landscape|Solution Landscape]]")
        story_root = self.docs / "backlog/epics/worker/stories/acquire"
        backlog_fixture._author_story(story_root / "story.md", story_root / "test-plan.md", "ST-001")
        test_plan = story_root / "test-plan.md"
        test_plan.write_text(test_plan.read_text(encoding="utf-8").replace(
            "an eligible customer supplies valid account details", "the worker receives an approved artifact digest"
        ).replace("the customer submits the account request", "the worker requests the exact digest").replace(
            "the account result and identifier are returned", "the requested digest is returned without tag substitution"
        ), encoding="utf-8")
        self.author_reviews()
        self.assert_cli("approve")
        self.assertTrue(requirement.requirement_incorporated(self.docs, "REQ-001"))
        self.commit("Approve technical backlog and review evidence")
        self.assert_cli("check", "--approved")

        sources, snapshot, errors = delivery_compile.approved_backlog_sources(self.docs, ["ST-001"])
        self.assertEqual(errors, [])
        self.assertEqual(sources["ST-001"]["work_kind"], "technical")
        self.assertTrue(sources["ST-001"]["story_source_hash"].startswith("sha256:"))
        self.assertTrue(sources["ST-001"]["test_plan_source_hash"].startswith("sha256:"))
        props, _body = compiler.parse_front_matter(self.docs / "backlog/backlog.md")
        self.assertEqual(snapshot["backlog_package_hash"], props["package_hash"])
        self.assertEqual(set(props["absent_input_stages"]), {"design-system", "experience-design"})
        self.assertEqual(delivery_compile.handoff_binding_findings(
            self.docs, {"ST-001": sources["ST-001"]["story_path"]}), [])
        self.assertFalse((self.docs / "design-system").exists())
        self.assertFalse((self.docs / "experience-design").exists())

        # Absence is never carried implicitly into another planning revision.
        root_note = self.docs / "backlog/backlog.md"
        approved_bytes = root_note.read_bytes()
        code, output = self.cli("begin-revision", "--planning-mode", "requirement", "--requirement-ref", "REQ-001")
        self.assertEqual(code, 1, output)
        self.assertIn("needs an input binding", output)
        self.assertEqual(root_note.read_bytes(), approved_bytes)
        visual = self.write_note("design-system/MASTER.md", {
            "type": "design-master", "status": "draft",
        }, "# New visual work\n")
        code, output = self.cli("begin-revision", *flags)
        self.assertEqual(code, 1, output)
        self.assertIn("existing package content", output)
        self.assertEqual(root_note.read_bytes(), approved_bytes)
        visual.unlink()
        visual.parent.rmdir()
        self.assert_cli("begin-revision", *flags)
        revised, _body = compiler.parse_front_matter(root_note)
        self.assertEqual(revised["revision"], 2)
        self.assertEqual(revised["status"], "draft")
        self.assertEqual(revised["input_bindings"], props["input_bindings"])
        self.assertEqual(revised["absent_input_stages"], props["absent_input_stages"])
        _sources, _snapshot, errors = delivery_compile.approved_backlog_sources(self.docs, ["ST-001"])
        self.assertTrue(errors, "A pending revision must not become a new Delivery input")


if __name__ == "__main__":
    unittest.main()
