#!/usr/bin/env python3
"""Fail-closed team preflight enforced before local mutation tools."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path


OWNER_RE = re.compile(
    r"^# Generated by Agentrof ([a-z0-9]+(?:-[a-z0-9]+)*); do not edit by hand\.$"
)
MUTATION_TOOLS = {"Write", "Edit", "MultiEdit", "apply_patch", "Bash",
                  "exec_command", "shell"}
READ_ONLY_DIAGNOSTICS = {
    ("claude", "plugin", "list", "--json"),
    ("codex", "plugin", "list", "--json"),
}


def data_dir() -> Path:
    override = os.environ.get("AGENTROF_HOME", "").strip()
    return Path(override) if override else Path.home() / ".agentrof"


def plugin_root() -> Path:
    return Path(__file__).resolve().parents[1]


def plugin_name() -> str:
    root = plugin_root()
    for manifest in (
        root / ".codex-plugin" / "plugin.json",
        root / ".claude-plugin" / "plugin.json",
    ):
        try:
            value = json.loads(manifest.read_text(encoding="utf-8")).get("name", "")
            if value:
                return str(value)
        except Exception:
            continue
    return "unknown-team"


def session_state_path(session_id: str) -> Path:
    digest = hashlib.sha256(session_id.encode("utf-8")).hexdigest()
    return data_dir() / "sessions" / f"{digest}.json"


def session_ready(session_id: str) -> bool:
    if not session_id:
        return False
    try:
        state = json.loads(session_state_path(session_id).read_text(encoding="utf-8"))
        return state.get("session_id") == session_id and state.get("pmo_ready") is True
    except Exception:
        return False


def project_root(cwd: str) -> Path | None:
    try:
        current = Path(cwd).resolve()
    except Exception:
        return None
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists() or (candidate / "workspace").is_dir():
            return candidate
    return None


def conflicting_team(cwd: str, current_team: str) -> str:
    root = project_root(cwd)
    if root is None:
        return ""
    config = root / "workspace" / "config.json"
    try:
        owner = json.loads(config.read_text(encoding="utf-8")).get("managed_by", "")
        if owner and owner != current_team:
            return str(owner)
    except FileNotFoundError:
        pass
    except Exception:
        return "unreadable-project-config"
    agents = root / ".codex" / "agents"
    if agents.is_dir():
        for path in sorted(agents.glob("*.toml")):
            try:
                first = path.read_text(
                    encoding="utf-8", errors="replace"
                ).splitlines()[0]
            except (OSError, IndexError):
                continue
            match = OWNER_RE.fullmatch(first)
            if match and match.group(1) != current_team:
                return match.group(1)
    return ""


def register(team: str) -> None:
    launcher = data_dir() / "bin" / "agentrof_run.py"
    if not launcher.is_file():
        return
    subprocess.run(
        [sys.executable, str(launcher), "register", "--plugin", team,
         "--root", str(plugin_root())],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )


def deny(message: str) -> int:
    print(f"agentrof team gate: {message}", file=sys.stderr)
    return 2


def is_read_only_diagnostic(payload: dict) -> bool:
    """Allow only exact plugin inventory commands through a shell hook.

    A strict argv comparison deliberately rejects redirects, pipelines,
    command chaining, environment prefixes, and extra flags.
    """
    if str(payload.get("tool_name", "")) not in {"Bash", "exec_command", "shell"}:
        return False
    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        return False
    command = tool_input.get("command", tool_input.get("cmd", ""))
    if not isinstance(command, str):
        return False
    try:
        argv = tuple(shlex.split(command, posix=True))
    except ValueError:
        return False
    return argv in READ_ONLY_DIAGNOSTICS


def preflight(payload: dict) -> int:
    tool = str(payload.get("tool_name", ""))
    if tool not in MUTATION_TOOLS:
        return 0
    if is_read_only_diagnostic(payload):
        return 0
    if str(payload.get("permission_mode", "")) == "plan":
        return deny(
            "state-changing team workflows cannot run in Plan mode. Switch to"
            " Code or Default mode; no files or project state were changed."
        )
    session_id = str(payload.get("session_id", ""))
    if not session_ready(session_id):
        root = plugin_root()
        if (root / ".codex-plugin" / "plugin.json").is_file():
            recovery = (
                "run `codex plugin add project-management-office@agent-marketplace`,"
                " inspect and trust both plugins in `/hooks`, then start a new task"
            )
        else:
            recovery = (
                "run `/plugin install project-management-office@agent-marketplace`,"
                " enable it if disabled, then restart Claude Code"
            )
        return deny(
            "Project Management Office did not mark this session ready; "
            + recovery
            + ". No files or project state were changed."
        )
    team = plugin_name()
    conflict = conflicting_team(str(payload.get("cwd", "")), team)
    if conflict:
        return deny(
            f"this project is already managed by team '{conflict}'; only one"
            " delivery team may own a project. No files or project state were changed."
        )
    register(team)
    return 0


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        payload = {}
    mode = sys.argv[1] if len(sys.argv) > 1 else "pre"
    team = plugin_name()
    if mode == "register":
        register(team)
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SessionStart",
                "additionalContext": f"AGENTROF_HOOKS_ACTIVE: {team}",
            }
        }))
        return 0
    return preflight(payload)


if __name__ == "__main__":
    raise SystemExit(main())
