#!/usr/bin/env python3
"""Compiler and checker for business-analysis spaces.

An analysis space is one topic folder under workspace/docs/business-analysis/:
a tree of typed, cross-linked markdown documents (the authored source of
truth) plus machine-generated views under _generated/. This script is the
single mechanical authority over that structure. It contains zero document
taxonomy of its own: every doc type, section token, id kind, row schema and
threshold comes from the shipped schema data file
(skills/business-analysis/data/space-schema.json).

Subcommands:
  init          create a new space skeleton
  stub          create one born-compliant typed document
  check         structural validation; --gate approval adds the gate rules
  render        (re)generate the _generated/ views deterministically
  resolve       map ids to owning docs, statuses and statement hashes
  verify-import validate a backlog import's criterion ids against the space

Stdlib only. Exit 0 on success, 1 on findings/violations, 2 on usage.
Finding format mirrors tools/validate.py: SEVERITY path:line [check]
message | Fix: remediation, sorted by (path, line, check).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import unicodedata
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

DEFAULT_SCHEMA = (Path(__file__).resolve().parent.parent
                  / "skills" / "business-analysis" / "data" / "space-schema.json")

GENERATED_DIR = "_generated"
GENERATED_MARKER = "<!-- generated by ba_compile render; do not edit by hand -->"
GENERATED_VIEWS = ("index.md", "registry.md", "registry.json", "backlinks.md",
                   "status.md", "open-questions.md")

EM_DASH = "—"
ABSOLUTE_PATH_RE = re.compile(r"(?:^|[\s\"'`(=])(?:/Users/|/home/|[A-Za-z]:\\\\|~/)")
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
SEC_RE = re.compile(r"<!--\s*sec:\s*([a-z_]+)\s*-->")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
NAMESPACED_ID_RE = re.compile(r"\b(BR|AC|AS|OQ|DEC|CH)-([A-Z]{2,4})-(\d{3,})\b")
BARE_ID_RE = re.compile(r"\b(BR|AC|AS|OQ|DEC)-(\d{3,})\b")
ROUND_FILE_RE = re.compile(r"^round-(\d+)\.md$")
SPACE_ROUND_FILE_RE = re.compile(r"^space-round-(\d+)\.md$")

# Every check id this compiler can emit. The test suite's builder registry
# stays in lockstep with this tuple: a check without a firing fixture
# cannot merge (same doctrine as tools/validate.py).
CHECK_IDS = (
    "space_layout", "frontmatter_schema", "status_legality",
    "required_sections", "summary_caps", "content_bans", "dead_links",
    "id_format", "id_unique", "id_minting", "id_links", "row_schema",
    "semantic_links", "approval_preconditions", "challenge_record",
    "br_uncited", "thresholds", "aging", "gate_approval",
    "generated_freshness",
)

STATUS_RANK = {"draft": 0, "in_review": 1, "approved": 2}


@dataclass(frozen=True)
class Finding:
    severity: str  # "error" | "warning"
    path: str
    line: int
    check: str
    message: str
    remediation: str


@dataclass
class Table:
    section: str | None
    header_line: int
    columns: list[str]
    rows: list[tuple[int, list[str]]]


@dataclass
class Doc:
    rel: str
    abs_path: Path
    fm: dict
    fm_end: int
    doc_type: str
    node: str
    lines: list[str] = field(default_factory=list)
    fenced: set = field(default_factory=set)
    headings: list = field(default_factory=list)  # (lineno, level, text)
    sections: dict = field(default_factory=dict)  # token -> (h_line, start, end)
    tables: list = field(default_factory=list)
    summary_lines: int = 0
    links: list = field(default_factory=list)  # (lineno, text, target)


@dataclass
class Space:
    root: Path
    schema: dict
    docs: dict = field(default_factory=dict)     # rel -> Doc
    nodes: dict = field(default_factory=dict)    # rel -> code ("" = root)
    ids: dict = field(default_factory=dict)      # id -> {kind, doc, row, line}
    broken: bool = False  # ambiguity class present; render must refuse


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def parse_frontmatter(text: str) -> tuple[dict, int, str | None]:
    """Minimal YAML subset: scalar `key: value` and lists of `- item` lines.
    Returns (frontmatter, body start line 1-based, error or None)."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, 1, "missing frontmatter block"
    fm: dict = {}
    current_list: str | None = None
    for i in range(1, len(lines)):
        raw = lines[i]
        stripped = raw.strip()
        if stripped == "---":
            return fm, i + 2, None
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") and current_list:
            fm[current_list].append(stripped[2:].strip().strip("\"'"))
            continue
        if ":" in stripped:
            key, _, value = stripped.partition(":")
            key = key.strip()
            value = value.strip().strip("\"'")
            if value == "":
                fm[key] = []
                current_list = key
            else:
                current_list = None
                if value in ("true", "false"):
                    fm[key] = value == "true"
                elif value.isdigit():
                    fm[key] = int(value)
                else:
                    fm[key] = value
            continue
        return fm, i + 1, f"unparseable frontmatter line: {stripped[:40]}"
    return fm, 1, "unterminated frontmatter block"


def heading_has_emoji(line: str) -> bool:
    for ch in line:
        code = ord(ch)
        if code >= 0x1F000:
            return True
        if 0x2600 <= code <= 0x27BF or 0x2B00 <= code <= 0x2BFF or code == 0xFE0F:
            return True
        if unicodedata.category(ch) == "So":
            return True
    return False


def parse_doc_body(doc: Doc) -> None:
    """Fill headings, sections, summary, tables and links from doc.lines."""
    in_fence = False
    for idx, line in enumerate(doc.lines, start=1):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            doc.fenced.add(idx)
            continue
        if in_fence:
            doc.fenced.add(idx)

    h1_line = 0
    first_h2 = 0
    for idx, line in enumerate(doc.lines, start=1):
        if idx < doc.fm_end or idx in doc.fenced:
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            level = len(m.group(1))
            doc.headings.append((idx, level, m.group(2).strip()))
            if level == 1 and not h1_line:
                h1_line = idx
            if level == 2 and not first_h2:
                first_h2 = idx

    if h1_line:
        end = first_h2 if first_h2 else len(doc.lines) + 1
        doc.summary_lines = sum(
            1 for i in range(h1_line + 1, end)
            if doc.lines[i - 1].strip() and i not in doc.fenced
        )

    h2s = [(idx, text) for idx, level, text in doc.headings if level == 2]
    for pos, (idx, text) in enumerate(h2s):
        m = SEC_RE.search(text)
        token = m.group(1) if m else None
        end = h2s[pos + 1][0] if pos + 1 < len(h2s) else len(doc.lines) + 1
        if token and token not in doc.sections:
            doc.sections[token] = (idx, idx + 1, end)

    def section_of(lineno: int) -> str | None:
        for token, (_h, start, end) in doc.sections.items():
            if start <= lineno < end:
                return token
        return None

    idx = doc.fm_end
    total = len(doc.lines)
    while idx <= total:
        line = doc.lines[idx - 1]
        if idx not in doc.fenced and line.strip().startswith("|"):
            block_start = idx
            block = []
            while idx <= total and idx not in doc.fenced \
                    and doc.lines[idx - 1].strip().startswith("|"):
                block.append((idx, doc.lines[idx - 1]))
                idx += 1
            if len(block) >= 2 and set(block[1][1].replace("|", "").strip()) <= set("-: "):
                columns = [c.strip().lower() for c in block[0][1].strip().strip("|").split("|")]
                rows = []
                for lineno, raw in block[2:]:
                    cells = [c.strip() for c in raw.strip().strip("|").split("|")]
                    rows.append((lineno, cells))
                doc.tables.append(Table(section_of(block_start), block[0][0], columns, rows))
            continue
        idx += 1

    for idx, line in enumerate(doc.lines, start=1):
        if idx < doc.fm_end or idx in doc.fenced:
            continue
        for m in LINK_RE.finditer(line):
            doc.links.append((idx, m.group(1), m.group(2)))


# ---------------------------------------------------------------------------
# Space scan
# ---------------------------------------------------------------------------


def classify_location(schema: dict, rel_parts: tuple[str, ...]) -> tuple[str, str] | None:
    """Return (node_rel, expected_type) for a markdown file path, or None
    when the location is illegal."""
    parts = list(rel_parts)
    node: list[str] = []
    while len(parts) > 2 and parts[0] == "domains":
        node.extend(parts[:2])
        parts = parts[2:]
    node_rel = "/".join(node)
    is_root = node_rel == ""
    if len(parts) == 1:
        name = parts[0]
        for type_name, spec in schema["doc_types"].items():
            loc = spec["location"]
            if loc["kind"] != "named_file" or loc["name"] != name:
                continue
            if loc.get("root_only") and not is_root:
                return None
            if loc.get("domain_only") and is_root:
                return None
            return node_rel, type_name
        if name == "domain.md" and is_root:
            return None
        return None
    if len(parts) == 2:
        folder, _name = parts
        for type_name, spec in schema["doc_types"].items():
            loc = spec["location"]
            if loc["kind"] != "folder" or loc["folder"] != folder:
                continue
            if loc.get("root_only") and not is_root:
                return None
            return node_rel, type_name
        return None
    return None


def scan_space(space_dir: Path, schema: dict) -> tuple[Space, list[Finding]]:
    space = Space(root=space_dir, schema=schema)
    findings: list[Finding] = []

    def err(path: str, line: int, check: str, message: str, fix: str) -> None:
        findings.append(Finding("error", path, line, check, message, fix))

    def warn(path: str, line: int, check: str, message: str, fix: str) -> None:
        findings.append(Finding("warning", path, line, check, message, fix))

    if not space_dir.is_dir():
        err(space_dir.as_posix(), 1, "space_layout",
            "space directory does not exist", "run the init subcommand first")
        space.broken = True
        return space, findings

    space.nodes[""] = ""
    for dir_path in sorted(space_dir.rglob("*")):
        if not dir_path.is_dir():
            continue
        rel = dir_path.relative_to(space_dir).as_posix()
        if rel.split("/")[0] == GENERATED_DIR:
            continue
        parts = rel.split("/")
        if parts[-1] == "domains":
            continue
        is_node = len(parts) % 2 == 0 and all(
            parts[i] == "domains" for i in range(0, len(parts), 2))
        if is_node:
            space.nodes[rel] = ""
            depth = len(parts) // 2
            if depth >= schema["thresholds"]["nesting_fail_depth"]:
                err(rel, 1, "space_layout",
                    f"domain nesting depth {depth} exceeds the cap",
                    "restructure: promote the subtree or merge domains")
            elif depth >= schema["thresholds"]["nesting_warn_depth"]:
                warn(rel, 1, "space_layout",
                     f"domain nesting depth {depth}; consider restructuring",
                     "deep trees hide content; prefer wider domain maps")

    for node_rel in sorted(space.nodes):
        node_dir = space_dir / node_rel if node_rel else space_dir
        overview = "space.md" if node_rel == "" else "domain.md"
        if not (node_dir / overview).is_file():
            err((Path(node_rel) / overview).as_posix() if node_rel else overview,
                1, "space_layout", f"node is missing its overview file {overview}",
                "every node carries exactly one overview document")

    for name in ("space.md", "glossary.md", "actors.md", "budgets.md"):
        if not (space_dir / name).is_file():
            err(name, 1, "space_layout",
                f"space root is missing required file {name}",
                "the five-file root skeleton is fixed; run init or add the file")
    if not (space_dir / GENERATED_DIR).is_dir():
        err(GENERATED_DIR, 1, "space_layout",
            "the _generated directory is missing",
            "create it (render will populate it)")

    for file_path in sorted(space_dir.rglob("*")):
        if not file_path.is_file():
            continue
        rel = file_path.relative_to(space_dir).as_posix()
        parts = rel.split("/")
        if parts[0] == GENERATED_DIR:
            if len(parts) != 2 or parts[1] not in GENERATED_VIEWS:
                warn(rel, 1, "space_layout",
                     "unexpected file inside _generated",
                     "render owns this directory; stray files are deleted")
            continue
        if file_path.suffix != ".md":
            if file_path.name == ".gitkeep":
                continue
            warn(rel, 1, "space_layout",
                 "non-markdown file in the authored tree",
                 "the space holds markdown documents only")
            continue
        text = file_path.read_text(encoding="utf-8", errors="replace")
        if text.lstrip().startswith("<!-- generated by"):
            err(rel, 1, "space_layout",
                "generated-marker file outside _generated",
                "generated views live only under _generated/")
            continue
        location = classify_location(schema, tuple(parts))
        if location is None:
            err(rel, 1, "space_layout",
                "file location matches no document type",
                "place docs in their type folder; see the space standard")
            continue
        node_rel, expected_type = location
        fm, fm_end, fm_error = parse_frontmatter(text)
        if fm_error:
            err(rel, 1, "frontmatter_schema", fm_error,
                "every authored doc opens with a --- frontmatter block")
            space.broken = True
            continue
        doc_type = fm.get("type", "")
        if doc_type not in schema["doc_types"]:
            err(rel, 1, "frontmatter_schema",
                f"unknown doc type '{doc_type}'",
                "type must be one of the schema's doc_types")
            space.broken = True
            continue
        if doc_type != expected_type:
            err(rel, 1, "frontmatter_schema",
                f"type '{doc_type}' does not match its location"
                f" (expected '{expected_type}')",
                "move the file or fix the type")
        doc = Doc(rel=rel, abs_path=file_path, fm=fm, fm_end=fm_end,
                  doc_type=doc_type, node=node_rel,
                  lines=text.splitlines())
        parse_doc_body(doc)
        space.docs[rel] = doc

    code_format = re.compile(schema["code_format"])
    seen_codes: dict[str, str] = {}
    for rel in sorted(space.docs):
        doc = space.docs[rel]
        if doc.doc_type not in ("space", "domain"):
            continue
        code = str(doc.fm.get("code", ""))
        if not code_format.match(code):
            findings.append(Finding("error", rel, 1, "frontmatter_schema",
                                    f"node code '{code}' does not match {schema['code_format']}",
                                    "declare a 2-4 uppercase-letter code"))
            continue
        if code in schema["reserved_codes"]:
            findings.append(Finding("error", rel, 1, "frontmatter_schema",
                                    f"node code '{code}' is reserved",
                                    "reserved codes cannot be claimed by nodes"))
            continue
        if code in seen_codes:
            findings.append(Finding("error", rel, 1, "frontmatter_schema",
                                    f"node code '{code}' is already used by {seen_codes[code]}",
                                    "codes are unique across the whole space"))
            continue
        seen_codes[code] = rel
        space.nodes[doc.node] = code

    collect_ids(space, findings)
    return space, findings


def nearest_code(space: Space, node_rel: str) -> str:
    current = node_rel
    while True:
        code = space.nodes.get(current, "")
        if code:
            return code
        if current == "":
            return ""
        current = "/".join(current.split("/")[:-2])


def collect_ids(space: Space, findings: list[Finding]) -> None:
    schema = space.schema
    for rel in sorted(space.docs):
        doc = space.docs[rel]
        spec = schema["doc_types"].get(doc.doc_type)
        if spec is None:
            continue
        code = nearest_code(space, doc.node)
        for kind in spec["mints"]:
            row_schema = schema["row_schemas"][kind.lower()]
            token = row_schema["section"]
            if token not in doc.sections:
                continue
            for table in doc.tables:
                if table.section != token:
                    continue
                if table.columns != row_schema["columns"]:
                    findings.append(Finding(
                        "error", rel, table.header_line, "row_schema",
                        f"table in section '{token}' must carry the {kind} columns"
                        f" {' | '.join(row_schema['columns'])}",
                        "row tables use the fixed English snake_case headers"))
                    continue
                for lineno, cells in table.rows:
                    if len(cells) != len(table.columns):
                        findings.append(Finding(
                            "error", rel, lineno, "row_schema",
                            f"row has {len(cells)} cells, expected {len(table.columns)}",
                            "one cell per column, in order"))
                        continue
                    row = dict(zip(table.columns, cells))
                    id_value = row["id"]
                    m = NAMESPACED_ID_RE.fullmatch(id_value)
                    if m:
                        row_kind, row_code = m.group(1), m.group(2)
                        if row_kind != kind:
                            findings.append(Finding(
                                "error", rel, lineno, "id_minting",
                                f"{id_value} minted in a {kind} table",
                                f"{row_kind} rows live in their own section"))
                            continue
                        if row_code != code:
                            findings.append(Finding(
                                "error", rel, lineno, "id_minting",
                                f"{id_value} carries code {row_code} but this"
                                f" node's code is {code}",
                                "an id is minted under its owning node's code;"
                                " moving a doc re-mints its ids"))
                            continue
                    else:
                        findings.append(Finding(
                            "error", rel, lineno, "id_format",
                            f"id '{id_value}' does not match {schema['id_format']}",
                            "mint KIND-CODE-NNN ids under the owning node's code"))
                        continue
                    if id_value in space.ids:
                        findings.append(Finding(
                            "error", rel, lineno, "id_unique",
                            f"{id_value} is already declared in"
                            f" {space.ids[id_value]['doc']}",
                            "an id is declared exactly once; numbers are never reused"))
                        continue
                    space.ids[id_value] = {"kind": kind, "doc": rel,
                                           "row": row, "line": lineno}


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------


def doc_status(doc: Doc) -> str:
    return str(doc.fm.get("status", ""))


def id_references(doc: Doc) -> list[tuple[int, str, str | None]]:
    """All id references in a doc: (line, id, link_target or None).
    Table id-column declarations are excluded (they are mints)."""
    refs: list[tuple[int, str, str | None]] = []
    mint_lines = {}
    for table in doc.tables:
        for lineno, cells in table.rows:
            mint_lines.setdefault(lineno, set())
            if cells and "id" in table.columns:
                mint_lines[lineno].add(cells[table.columns.index("id")]
                                       if len(cells) > table.columns.index("id") else "")
    for idx, line in enumerate(doc.lines, start=1):
        if idx < doc.fm_end or idx in doc.fenced:
            continue
        remaining = line
        for m in LINK_RE.finditer(line):
            text, target = m.group(1), m.group(2)
            if NAMESPACED_ID_RE.fullmatch(text) or BARE_ID_RE.fullmatch(text):
                refs.append((idx, text, target))
        remaining = LINK_RE.sub(" ", line)
        for m in list(NAMESPACED_ID_RE.finditer(remaining)) + \
                list(BARE_ID_RE.finditer(remaining)):
            token = m.group(0)
            if token in mint_lines.get(idx, set()):
                continue
            refs.append((idx, token, None))
    return refs


def run_checks(space: Space, base: list[Finding], gate: bool = False,
               gate_node: str = "", today: date | None = None) -> list[Finding]:
    schema = space.schema
    findings = list(base)
    today = today or date.today()

    def err(path, line, check, message, fix):
        findings.append(Finding("error", path, line, check, message, fix))

    def warn(path, line, check, message, fix):
        findings.append(Finding("warning", path, line, check, message, fix))

    statuses = schema["statuses"]
    fm_common = schema["frontmatter"]

    for rel in sorted(space.docs):
        doc = space.docs[rel]
        spec = schema["doc_types"][doc.doc_type]

        required = list(fm_common["required"]) + list(spec["extra_frontmatter"]["required"])
        allowed = set(required) | set(fm_common["optional"])
        for key in required:
            if key not in doc.fm:
                err(rel, 1, "frontmatter_schema",
                    f"missing frontmatter key '{key}'",
                    "the type's required keys are fixed by the schema")
        for key in doc.fm:
            if key not in allowed:
                warn(rel, 1, "frontmatter_schema",
                     f"unknown frontmatter key '{key}'",
                     "only schema-declared keys carry meaning")

        status = doc_status(doc)
        if status not in statuses:
            err(rel, 1, "status_legality",
                f"status '{status}' not in {statuses}",
                "use the schema's status enum")
        if status == "approved" and "approved_at" not in doc.fm:
            err(rel, 1, "status_legality",
                "approved doc is missing approved_at",
                "stamp approved_at: YYYY-MM-DD at the gate")
        if status != "approved" and "approved_at" in doc.fm:
            err(rel, 1, "status_legality",
                "approved_at present on a non-approved doc",
                "approved_at exists exactly when status is approved")
        if status == "superseded" and "superseded_by" not in doc.fm:
            err(rel, 1, "status_legality",
                "superseded doc is missing superseded_by",
                "name the successor documents")
        if "approved_at" in doc.fm and not DATE_RE.match(str(doc.fm["approved_at"])):
            err(rel, 1, "status_legality",
                "approved_at is not a YYYY-MM-DD date",
                "dates are ISO calendar dates")

        h1s = [h for h in doc.headings if h[1] == 1]
        if len(h1s) != 1:
            err(rel, 1, "required_sections",
                f"doc has {len(h1s)} H1 headings, expected exactly 1",
                "one H1 per document, matching its title")
        for token in spec["required_sections"]:
            if token not in doc.sections:
                err(rel, 1, "required_sections",
                    f"missing section '{token}'",
                    f"add an H2 carrying <!-- sec: {token} -->")

        cap = schema["summary_max_lines"].get(doc.doc_type,
                                              schema["summary_max_lines"]["default"])
        if doc.summary_lines > cap:
            err(rel, 1, "summary_caps",
                f"head summary is {doc.summary_lines} lines (cap {cap})",
                "the summary between the H1 and the first H2 is capped")

        for idx, line in enumerate(doc.lines, start=1):
            if EM_DASH in line:
                err(rel, idx, "content_bans", "em dash character found",
                    "replace with a hyphen, comma, or rewrite")
            if idx not in doc.fenced and line.lstrip().startswith("#") \
                    and heading_has_emoji(line):
                err(rel, idx, "content_bans", "emoji in heading",
                    "headings are plain text")
            if ABSOLUTE_PATH_RE.search(line):
                err(rel, idx, "content_bans", "absolute or home path found",
                    "workspace docs use relative paths only")

        for lineno, _text, target in doc.links:
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            clean = target.split("#", 1)[0]
            if not clean:
                continue
            resolved = (doc.abs_path.parent / clean).resolve()
            try:
                inside = resolved.relative_to(space.root.resolve())
                if str(inside).split("/")[0] == GENERATED_DIR:
                    err(rel, lineno, "dead_links",
                        f"authored doc links into {GENERATED_DIR}/",
                        "authored docs never depend on generated views")
                    continue
            except ValueError:
                warn(rel, lineno, "dead_links",
                     f"link leaves the space: {target}",
                     "cross-space links are not checked; prefer in-space links")
            if not resolved.exists():
                err(rel, lineno, "dead_links",
                    f"link target does not resolve: {target}",
                    "fix the path or restore the target")

        for lineno, id_value, target in id_references(doc):
            info = space.ids.get(id_value)
            if target is not None:
                if info is None:
                    err(rel, lineno, "id_links",
                        f"link cites unknown id {id_value}",
                        "cite only declared ids")
                else:
                    clean = target.split("#", 1)[0]
                    resolved = (doc.abs_path.parent / clean).resolve()
                    owner = (space.root / info["doc"]).resolve()
                    if resolved != owner:
                        err(rel, lineno, "id_links",
                            f"{id_value} link targets {target}, but the id is"
                            f" declared in {info['doc']}",
                            "an id link targets its owning document")
            else:
                in_table = any(any(lineno == ln for ln, _ in t.rows)
                               for t in doc.tables)
                if in_table:
                    if info is None:
                        err(rel, lineno, "id_links",
                            f"cell cites unknown id {id_value}",
                            "cite only declared ids")
                elif info is None or info["doc"] != rel:
                    err(rel, lineno, "id_links",
                        f"bare id {id_value} in prose",
                        "cite ids as links to their owning doc; bare ids are"
                        " legal only in the owning doc and in table cells")

        for kind in schema["doc_types"][doc.doc_type]["mints"]:
            row_schema = schema["row_schemas"][kind.lower()]
            enum = row_schema["status_enum"]
            for id_value, info in space.ids.items():
                if info["doc"] != rel or info["kind"] != kind:
                    continue
                row = info["row"]
                if enum and row.get("status", "") not in enum:
                    err(rel, info["line"], "row_schema",
                        f"{id_value} status '{row.get('status', '')}' not in {enum}",
                        "row statuses use the schema enum")
                if "opened_on" in row:
                    if not DATE_RE.match(row["opened_on"]):
                        err(rel, info["line"], "row_schema",
                            f"{id_value} opened_on is not a YYYY-MM-DD date",
                            "stamp the date the row was opened")
                    elif row.get("status") == "open":
                        age = (today - date.fromisoformat(row["opened_on"])).days
                        limit = schema["thresholds"]["open_row_age_days_warn"]
                        if age > limit:
                            warn(rel, info["line"], "aging",
                                 f"{id_value} has been open for {age} days"
                                 f" (threshold {limit})",
                                 "force it to an answer or defer it explicitly"
                                 " with a revisit trigger")
                if kind == "AC":
                    cite_ids = re.findall(r"\b[A-Z]{2,3}-[A-Z0-9]{2,4}-\d{3,}\b",
                                          row.get("cites", ""))
                    br_cites = [c for c in cite_ids if c.startswith("BR-")]
                    if not br_cites:
                        err(rel, info["line"], "row_schema",
                            f"{id_value} cites no business rule",
                            "every criterion cites the BR ids it exercises")
                    if not row.get("verify", "").strip():
                        err(rel, info["line"], "row_schema",
                            f"{id_value} has an empty verify cell",
                            "every criterion states how it is verified")

        if status == "approved":
            for id_value, info in space.ids.items():
                if info["doc"] != rel:
                    continue
                if info["row"].get("status") == "open":
                    err(rel, info["line"], "approval_preconditions",
                        f"approved doc holds open row {id_value}",
                        "answer, confirm, strike or defer every open row"
                        " before approval")

        if doc.doc_type == "challenge_record":
            check_challenge_record(space, doc, findings)

    check_semantic_links(space, findings)
    check_thresholds(space, findings, warn)
    check_br_citations(space, findings, gate=gate, gate_node=gate_node)

    if gate:
        run_gate_checks(space, findings, gate_node)
    return findings


def check_challenge_record(space: Space, doc: Doc, findings: list[Finding]) -> None:
    schema = space.schema
    rel = doc.rel

    def err(line, message, fix):
        findings.append(Finding("error", rel, line, "challenge_record", message, fix))

    scope = str(doc.fm.get("review_scope", ""))
    if scope not in schema["row_enums"]["challenge_review_scope"]:
        err(1, f"review_scope '{scope}' not in enum", "domain or space")
    verdict = str(doc.fm.get("verdict", ""))
    if verdict not in schema["row_enums"]["challenge_verdict"]:
        err(1, f"verdict '{verdict}' not in enum", "converged or continue")
    round_no = doc.fm.get("round")
    max_rounds = schema["challenge"]["max_rounds"]
    if not isinstance(round_no, int) or not 1 <= round_no <= max_rounds:
        err(1, f"round '{round_no}' outside 1..{max_rounds}",
            "the loop is capped; residue goes to the gate as open questions")
        round_no = None
    name = Path(rel).name
    m = SPACE_ROUND_FILE_RE.match(name) if scope == "space" else ROUND_FILE_RE.match(name)
    if not m:
        err(1, f"filename '{name}' does not match its review_scope '{scope}'",
            "domain records are round-N.md; space records are space-round-N.md")
    elif round_no is not None and int(m.group(1)) != round_no:
        err(1, f"filename round {m.group(1)} disagrees with frontmatter round"
            f" {round_no}", "the filename carries the round number")
    if scope == "space" and doc.node != "":
        err(1, "space-scope record outside the space root",
            "space rounds live in the root reviews/ folder")

    blocking = 0
    dispositions = schema["row_enums"]["ch_disposition"]
    severities = schema["row_enums"]["ch_severity"]
    for id_value, info in space.ids.items():
        if info["doc"] != rel or info["kind"] != "CH":
            continue
        row = info["row"]
        if row.get("severity", "") not in severities:
            err(info["line"], f"{id_value} severity '{row.get('severity', '')}'"
                f" not in {severities}", "the challenger's verdict, never downgraded")
        if row.get("severity") == "blocking":
            blocking += 1
        disposition = row.get("disposition", "").strip()
        if disposition not in dispositions:
            err(info["line"], f"{id_value} disposition '{disposition}' not in"
                f" {dispositions}", "triage disposes every finding")
        elif disposition != "rejected" and not row.get("targets", "").strip():
            err(info["line"], f"{id_value} disposition '{disposition}' names no"
                " target ids", "covered/fix/assumption/question cite what resolves them")
        elif disposition == "rejected" and not row.get("targets", "").strip():
            err(info["line"], f"{id_value} rejection carries no reason",
                "a rejection states its reason in the targets cell")
    if verdict == "converged" and blocking:
        err(1, f"verdict is converged but the round holds {blocking} blocking"
            " finding(s)", "converged means zero blocking findings this round")
    if doc.fm.get("locked") is True and doc_status(doc) != "approved":
        err(1, "locked record is not approved",
            "closing a round approves and locks it in the same write")
    if doc_status(doc) == "approved" and doc.fm.get("locked") is not True:
        err(1, "closed (approved) record is not locked",
            "set locked: true in the closing write; audit history is immutable")


def check_semantic_links(space: Space, findings: list[Finding]) -> None:
    for rel in sorted(space.docs):
        doc = space.docs[rel]
        for key, wanted in (("governs", ("process", "entity")),
                            ("verifies", ("process", "entity", "integration"))):
            targets = doc.fm.get(key)
            if not isinstance(targets, list):
                continue
            if not targets:
                findings.append(Finding("error", rel, 1, "semantic_links",
                                        f"{key} list is empty",
                                        f"name at least one target document"))
            for target in targets:
                resolved = (doc.abs_path.parent / str(target)).resolve()
                try:
                    target_rel = resolved.relative_to(space.root.resolve()).as_posix()
                except ValueError:
                    target_rel = None
                target_doc = space.docs.get(target_rel) if target_rel else None
                if target_doc is None:
                    findings.append(Finding("error", rel, 1, "semantic_links",
                                            f"{key} target does not resolve: {target}",
                                            "point at an existing document"))
                elif target_doc.doc_type not in wanted:
                    findings.append(Finding("error", rel, 1, "semantic_links",
                                            f"{key} target {target} is a"
                                            f" {target_doc.doc_type}",
                                            f"{key} points at {' or '.join(wanted)} docs"))

    for node_rel in sorted(space.nodes):
        overview_rel = (f"{node_rel}/domain.md" if node_rel else "space.md")
        overview = space.docs.get(overview_rel)
        if overview is None:
            continue
        linked = set()
        for _lineno, _text, target in overview.links:
            clean = target.split("#", 1)[0]
            resolved = (overview.abs_path.parent / clean).resolve()
            try:
                linked.add(resolved.relative_to(space.root.resolve()).as_posix())
            except ValueError:
                pass
        prefix = f"{node_rel}/" if node_rel else ""
        children = [r for r in space.nodes
                    if r.startswith(f"{prefix}domains/") and
                    r.count("/") == (node_rel.count("/") + 2 if node_rel else 1)]
        for child in sorted(children):
            child_overview = f"{child}/domain.md"
            if child_overview in space.docs and child_overview not in linked:
                findings.append(Finding(
                    "error", overview_rel, 1, "semantic_links",
                    f"domain_map does not link child domain {child}",
                    "the overview's domain map links every direct child"))
        own_processes = [r for r in space.docs
                         if space.docs[r].node == node_rel
                         and space.docs[r].doc_type == "process"]
        for proc in sorted(own_processes):
            if proc not in linked:
                findings.append(Finding(
                    "error", overview_rel, 1, "semantic_links",
                    f"process_map does not link {proc}",
                    "the overview's process map links every process it owns"))


def check_thresholds(space: Space, findings: list[Finding], warn) -> None:
    th = space.schema["thresholds"]
    total_docs = len(space.docs)
    total_bytes = sum(len("\n".join(d.lines).encode("utf-8"))
                      for d in space.docs.values())
    if total_docs > th["space_docs_warn"]:
        warn("space.md", 1, "thresholds",
             f"space holds {total_docs} docs (threshold {th['space_docs_warn']})",
             "consider splitting the topic into multiple spaces")
    if total_bytes > th["space_bytes_warn"]:
        warn("space.md", 1, "thresholds",
             f"space totals {total_bytes} bytes (threshold {th['space_bytes_warn']})",
             "review the decomposition; snapshot size follows space size")

    for node_rel in sorted(space.nodes):
        own = [d for d in space.docs.values() if d.node == node_rel]
        direct = [d for d in own if d.doc_type not in
                  ("space", "domain", "challenge_record")]
        overview_rel = f"{node_rel}/domain.md" if node_rel else "space.md"
        if len(direct) > th["node_direct_docs_warn"]:
            warn(overview_rel, 1, "thresholds",
                 f"node owns {len(direct)} content docs"
                 f" (threshold {th['node_direct_docs_warn']})",
                 "a split signal: consider a child domain")
        rule_sets = [d for d in own if d.doc_type == "rule_set"]
        if len(rule_sets) > th["rule_sets_per_node_warn"]:
            warn(overview_rel, 1, "thresholds",
                 f"node owns {len(rule_sets)} rule sets"
                 f" (threshold {th['rule_sets_per_node_warn']})",
                 "a split signal: consider a child domain")
        active_br = sum(1 for i in space.ids.values()
                        if i["kind"] == "BR" and i["row"].get("status") == "active"
                        and space.docs[i["doc"]].node == node_rel)
        if active_br > th["active_br_per_node_warn"]:
            warn(overview_rel, 1, "thresholds",
                 f"node holds {active_br} active business rules"
                 f" (threshold {th['active_br_per_node_warn']})",
                 "a split signal: consider a child domain")
        for d in own:
            if d.doc_type == "process" and len(d.lines) > th["process_doc_lines_warn"]:
                warn(d.rel, 1, "thresholds",
                     f"process doc is {len(d.lines)} lines"
                     f" (threshold {th['process_doc_lines_warn']})",
                     "split by workflow stage or variant")
            if d.doc_type == "rule_set":
                count = sum(1 for i in space.ids.values()
                            if i["doc"] == d.rel and i["kind"] == "BR"
                            and i["row"].get("status") == "active")
                if count > th["rules_per_set_warn"]:
                    warn(d.rel, 1, "thresholds",
                         f"rule set holds {count} active rules"
                         f" (threshold {th['rules_per_set_warn']})",
                         "split by governed target")
            if d.doc_type == "acceptance_set":
                count = sum(1 for i in space.ids.values()
                            if i["doc"] == d.rel and i["kind"] == "AC"
                            and i["row"].get("status") == "active")
                if count > th["criteria_per_set_warn"]:
                    warn(d.rel, 1, "thresholds",
                         f"acceptance set holds {count} active criteria"
                         f" (threshold {th['criteria_per_set_warn']})",
                         "split by flow: main versus exceptions")

        processes = [d for d in own if d.doc_type == "process"]
        if len(processes) >= 2:
            entity_links: dict[str, set] = {}
            for proc in processes:
                touched = set()
                for _l, _t, target in proc.links:
                    clean = target.split("#", 1)[0]
                    resolved = (proc.abs_path.parent / clean).resolve()
                    try:
                        target_rel = resolved.relative_to(space.root.resolve()).as_posix()
                    except ValueError:
                        continue
                    tdoc = space.docs.get(target_rel)
                    if tdoc is not None and tdoc.doc_type == "entity":
                        touched.add(target_rel)
                entity_links[proc.rel] = touched
            groups = [{"procs": {proc_rel}, "entities": set(touched)}
                      for proc_rel, touched in sorted(entity_links.items())]
            changed = True
            while changed:
                changed = False
                for a in range(len(groups)):
                    for b in range(a + 1, len(groups)):
                        if groups[a]["entities"] & groups[b]["entities"]:
                            groups[a]["procs"] |= groups[b]["procs"]
                            groups[a]["entities"] |= groups[b]["entities"]
                            del groups[b]
                            changed = True
                            break
                    if changed:
                        break
            real = [g for g in groups if g["entities"]]
            if len(real) >= 2 and all(len(g["procs"]) >= 2 for g in real):
                warn(overview_rel, 1, "thresholds",
                     "node's processes touch disjoint entity clusters",
                     "a split signal: the clusters may be separate domains")


def check_br_citations(space: Space, findings: list[Finding],
                       gate: bool, gate_node: str) -> None:
    cited: set[str] = set()
    for id_value, info in space.ids.items():
        if info["kind"] != "AC":
            continue
        for m in NAMESPACED_ID_RE.finditer(info["row"].get("cites", "")):
            cited.add(m.group(0))
    for id_value in sorted(space.ids):
        info = space.ids[id_value]
        if info["kind"] != "BR" or info["row"].get("status") != "active":
            continue
        if id_value in cited:
            continue
        in_scope = doc_in_node(space, info["doc"], gate_node)
        severity = "error" if gate and in_scope else "warning"
        findings.append(Finding(
            severity, info["doc"], info["line"], "br_uncited",
            f"{id_value} is cited by no acceptance criterion",
            "every active rule is exercised by at least one criterion"))


def doc_in_node(space: Space, rel: str, node_rel: str) -> bool:
    if node_rel == "":
        return True
    doc = space.docs.get(rel)
    if doc is None:
        return False
    return doc.node == node_rel or doc.node.startswith(node_rel + "/")


def content_nodes(space: Space) -> list[str]:
    result = []
    for node_rel in sorted(space.nodes):
        own = [d for d in space.docs.values()
               if d.node == node_rel and d.doc_type in
               ("process", "entity", "rule_set", "acceptance_set", "integration")]
        if own:
            result.append(node_rel)
    return result


def latest_record(space: Space, node_rel: str, scope: str) -> Doc | None:
    best: Doc | None = None
    best_round = 0
    for doc in space.docs.values():
        if doc.doc_type != "challenge_record" or doc.node != node_rel:
            continue
        if str(doc.fm.get("review_scope", "")) != scope:
            continue
        round_no = doc.fm.get("round")
        if isinstance(round_no, int) and round_no > best_round:
            best, best_round = doc, round_no
    return best


def record_satisfies_gate(space: Space, record: Doc | None) -> str | None:
    """Return None when the record satisfies the gate, else the reason."""
    max_rounds = space.schema["challenge"]["max_rounds"]
    if record is None:
        return "no challenge record exists"
    if record.fm.get("locked") is not True:
        return f"{record.rel} is not closed (locked)"
    if str(record.fm.get("verdict")) != "converged" \
            and record.fm.get("round") != max_rounds:
        return (f"{record.rel} is not converged and is not the final round"
                f" {max_rounds}")
    return None


def run_gate_checks(space: Space, findings: list[Finding], gate_node: str) -> None:
    def err(path, line, message, fix):
        findings.append(Finding("error", path, line, "gate_approval", message, fix))

    for name in ("space.md", "glossary.md", "actors.md", "budgets.md"):
        doc = space.docs.get(name)
        if doc is None:
            continue
        if doc_status(doc) != "approved":
            err(name, 1, f"foundation doc is {doc_status(doc)}, not approved",
                "the foundation gate precedes every domain gate")

    for rel in sorted(space.docs):
        doc = space.docs[rel]
        if not doc_in_node(space, rel, gate_node):
            continue
        spec = space.schema["doc_types"][doc.doc_type]
        if spec["gate_blocking"] and doc_status(doc) not in ("approved", "superseded"):
            err(rel, 1, f"gate-blocking doc is {doc_status(doc)}, not approved",
                "approve or supersede every gate-blocking doc in the subtree")

    subtree_nodes = [n for n in content_nodes(space)
                     if gate_node == "" or n == gate_node
                     or n.startswith(gate_node + "/")]
    for node_rel in subtree_nodes:
        overview = f"{node_rel}/domain.md" if node_rel else "space.md"
        reason = record_satisfies_gate(space, latest_record(space, node_rel, "domain"))
        if reason:
            err(overview, 1, f"challenge gate unsatisfied: {reason}",
                "run the challenge loop and close a converged (or final) round")

    has_domains = len(space.nodes) > 1
    if gate_node == "" and has_domains:
        reason = record_satisfies_gate(space, latest_record(space, "", "space"))
        if reason:
            err("space.md", 1, f"space-level challenge gate unsatisfied: {reason}",
                "run the cross-domain round before closing the space")

    for folder, type_name in (("processes", "process"), ("rules", "rule_set"),
                              ("acceptance", "acceptance_set")):
        exists = any(doc_in_node(space, rel, gate_node)
                     and space.docs[rel].doc_type == type_name
                     for rel in space.docs)
        if not exists:
            anchor = f"{gate_node}/domain.md" if gate_node else "space.md"
            err(anchor, 1, f"subtree holds no {type_name} document",
                "the distributed brief contract requires processes, rules"
                " and acceptance criteria")

    if gate_node:
        for rel in sorted(space.docs):
            doc = space.docs[rel]
            if not doc_in_node(space, rel, gate_node):
                continue
            for _lineno, id_value, _target in id_references(doc):
                info = space.ids.get(id_value)
                if info is None or doc_in_node(space, info["doc"], gate_node):
                    continue
                owner = space.docs[info["doc"]]
                if doc_status(owner) != "approved":
                    err(rel, _lineno,
                        f"cites {id_value} whose owning doc {info['doc']} is"
                        f" {doc_status(owner)}",
                        "cross-domain citation closure: cited owners are approved")


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------


def statement_of(space: Space, id_value: str) -> str:
    info = space.ids[id_value]
    row = info["row"]
    for column in ("statement", "criterion", "question", "ruling", "finding"):
        if column in row:
            return row[column]
    return ""


def id_sort_key(id_value: str):
    m = NAMESPACED_ID_RE.fullmatch(id_value)
    if m:
        return (m.group(1), m.group(2), int(m.group(3)))
    return ("ZZ", "ZZZZ", 0)


def node_rollup(space: Space, node_rel: str) -> str:
    ranks = []
    for rel in space.docs:
        if not doc_in_node(space, rel, node_rel):
            continue
        status = doc_status(space.docs[rel])
        if status == "superseded":
            continue
        ranks.append(STATUS_RANK.get(status, 0))
    if not ranks:
        return "draft"
    for name, rank in STATUS_RANK.items():
        if rank == min(ranks):
            return name
    return "draft"


def foundation_approved(space: Space) -> bool:
    return all(doc_status(space.docs[n]) == "approved"
               for n in ("space.md", "glossary.md", "actors.md", "budgets.md")
               if n in space.docs)


def node_buildable(space: Space, node_rel: str) -> bool:
    probe = run_gate_checks_collect(space, node_rel)
    return foundation_approved(space) and not probe


def run_gate_checks_collect(space: Space, node_rel: str) -> list[Finding]:
    collected: list[Finding] = []
    run_gate_checks(space, collected, node_rel)
    return [f for f in collected if f.severity == "error"]


def cited_by_map(space: Space) -> dict[str, list[str]]:
    cited: dict[str, list[str]] = {}
    for ac_id in sorted((i for i in space.ids
                         if space.ids[i]["kind"] == "AC"), key=id_sort_key):
        cites = space.ids[ac_id]["row"].get("cites", "")
        for m in NAMESPACED_ID_RE.finditer(cites):
            cited.setdefault(m.group(0), []).append(ac_id)
    return cited


def render_views(space: Space, warnings: list[Finding]) -> dict[str, str]:
    """Pure function of the authored tree (plus stable warnings): returns
    {relpath under _generated: content}."""
    docs_sorted = sorted(space.docs)
    cited = cited_by_map(space)
    title = str(space.docs.get("space.md").fm.get("title", "")) \
        if "space.md" in space.docs else ""
    stable_warnings = [w for w in warnings
                       if w.severity == "warning" and w.check != "aging"]

    lines = [GENERATED_MARKER, f"# Index: {title}", ""]
    lines.append(f"Foundation approved: {'yes' if foundation_approved(space) else 'no'}")
    lines.append(f"Space status: {node_rollup(space, '')}")
    lines += ["", "## Nodes", "",
              "| node | code | status | buildable | docs |",
              "|---|---|---|---|---|"]
    for node_rel in sorted(space.nodes):
        count = sum(1 for r in space.docs if space.docs[r].node == node_rel)
        lines.append(
            f"| {node_rel or '(root)'} | {space.nodes[node_rel]} |"
            f" {node_rollup(space, node_rel)} |"
            f" {'yes' if node_buildable(space, node_rel) else 'no'} | {count} |")
    lines += ["", "## Documents", "",
              "| doc | type | status | summary |",
              "|---|---|---|---|"]
    for rel in docs_sorted:
        doc = space.docs[rel]
        summary = ""
        for h_idx, level, _text in doc.headings:
            if level == 1:
                for i in range(h_idx + 1, len(doc.lines) + 1):
                    candidate = doc.lines[i - 1].strip()
                    if candidate.startswith("#"):
                        break
                    if candidate:
                        summary = candidate.replace("|", "\\|")
                        break
                break
        lines.append(f"| [{rel}]({'../' + rel}) | {doc.doc_type} |"
                     f" {doc_status(doc)} | {summary} |")
    if stable_warnings:
        lines += ["", "## Warnings", ""]
        for w in sorted(stable_warnings, key=lambda f: (f.path, f.line, f.check)):
            lines.append(f"- {w.path}:{w.line} [{w.check}] {w.message}")
    index_md = "\n".join(lines) + "\n"

    lines = [GENERATED_MARKER, f"# Registry: {title}", "", "## Codes", "",
             "| code | node |", "|---|---|"]
    for node_rel in sorted(space.nodes, key=lambda n: (space.nodes[n], n)):
        if space.nodes[node_rel]:
            lines.append(f"| {space.nodes[node_rel]} | {node_rel or '(root)'} |")
    for kind, heading in (("BR", "Business Rules"), ("AC", "Acceptance Criteria"),
                          ("AS", "Assumptions"), ("DEC", "Decisions"),
                          ("CH", "Challenge Findings")):
        ids = sorted((i for i in space.ids if space.ids[i]["kind"] == kind),
                     key=id_sort_key)
        if not ids:
            continue
        lines += ["", f"## {heading}", ""]
        if kind == "BR":
            lines += ["| id | statement | status | doc | cited_by |", "|---|---|---|---|---|"]
            for i in ids:
                info = space.ids[i]
                lines.append(f"| {i} | {statement_of(space, i).replace('|', chr(92) + '|')} |"
                             f" {info['row'].get('status', '')} | {info['doc']} |"
                             f" {', '.join(cited.get(i, []))} |")
        else:
            lines += ["| id | statement | status | doc |", "|---|---|---|---|"]
            for i in ids:
                info = space.ids[i]
                status = info["row"].get("status", info["row"].get("severity", ""))
                lines.append(f"| {i} | {statement_of(space, i).replace('|', chr(92) + '|')} |"
                             f" {status} | {info['doc']} |")
    registry_md = "\n".join(lines) + "\n"

    registry = {"schema_version": space.schema["schema_version"],
                "codes": {space.nodes[n]: (n or "(root)")
                          for n in space.nodes if space.nodes[n]},
                "ids": {}}
    for i in sorted(space.ids, key=id_sort_key):
        info = space.ids[i]
        statement = statement_of(space, i)
        registry["ids"][i] = {
            "kind": info["kind"],
            "doc": info["doc"],
            "row_status": info["row"].get("status",
                                          info["row"].get("severity", "")),
            "doc_status": doc_status(space.docs[info["doc"]]),
            "statement": statement,
            "statement_sha256": hashlib.sha256(statement.encode("utf-8")).hexdigest(),
            "cited_by": cited.get(i, []),
        }
    registry_json = json.dumps(registry, indent=2, sort_keys=True) + "\n"

    inbound: dict[str, list[str]] = {}
    for rel in docs_sorted:
        doc = space.docs[rel]
        for _lineno, _text, target in doc.links:
            clean = target.split("#", 1)[0]
            if not clean or target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            resolved = (doc.abs_path.parent / clean).resolve()
            try:
                target_rel = resolved.relative_to(space.root.resolve()).as_posix()
            except ValueError:
                continue
            if target_rel in space.docs and target_rel != rel:
                inbound.setdefault(target_rel, [])
                if rel not in inbound[target_rel]:
                    inbound[target_rel].append(rel)
    lines = [GENERATED_MARKER, f"# Backlinks: {title}", ""]
    for rel in docs_sorted:
        sources = sorted(inbound.get(rel, []))
        if not sources:
            continue
        lines.append(f"## {rel}")
        lines += [f"- {s}" for s in sources]
        lines.append("")
    backlinks_md = "\n".join(lines).rstrip("\n") + "\n"

    lines = [GENERATED_MARKER, f"# Status: {title}", "", "## Documents by status", "",
             "| type | draft | in_review | approved | superseded |",
             "|---|---|---|---|---|"]
    for type_name in sorted(space.schema["doc_types"]):
        counts = {s: 0 for s in space.schema["statuses"]}
        for rel in docs_sorted:
            if space.docs[rel].doc_type == type_name:
                status = doc_status(space.docs[rel])
                if status in counts:
                    counts[status] += 1
        if sum(counts.values()):
            lines.append(f"| {type_name} | {counts['draft']} | {counts['in_review']} |"
                         f" {counts['approved']} | {counts['superseded']} |")
    lines += ["", "## Challenge coverage", "",
              "| node | rounds | last_verdict | open_blocking |",
              "|---|---|---|---|"]
    for node_rel in content_nodes(space):
        records = [d for d in space.docs.values()
                   if d.doc_type == "challenge_record" and d.node == node_rel
                   and str(d.fm.get("review_scope")) == "domain"]
        last = latest_record(space, node_rel, "domain")
        open_blocking = 0
        if last is not None:
            for i, info in space.ids.items():
                if info["doc"] == last.rel and info["kind"] == "CH" \
                        and info["row"].get("severity") == "blocking":
                    open_blocking += 1
        lines.append(f"| {node_rel or '(root)'} | {len(records)} |"
                     f" {last.fm.get('verdict') if last else ''} | {open_blocking} |")
    status_md = "\n".join(lines) + "\n"

    groups = {"open": [], "deferred": [], "answered": []}
    for i in sorted((x for x in space.ids if space.ids[x]["kind"] == "OQ"),
                    key=id_sort_key):
        info = space.ids[i]
        status = info["row"].get("status", "")
        if status in groups:
            groups[status].append(i)
    lines = [GENERATED_MARKER, f"# Open Questions: {title}", ""]
    for group, heading in (("open", "Open"), ("deferred", "Deferred"),
                           ("answered", "Answered (last 20)")):
        ids = groups[group]
        if group == "answered":
            ids = ids[-20:]
        if not ids:
            continue
        lines += [f"## {heading}", "",
                  "| id | question | doc | opened_on | note |", "|---|---|---|---|---|"]
        for i in ids:
            info = space.ids[i]
            row = info["row"]
            lines.append(f"| {i} | {row.get('question', '').replace('|', chr(92) + '|')} |"
                         f" {info['doc']} | {row.get('opened_on', '')} |"
                         f" {row.get('note', '').replace('|', chr(92) + '|')} |")
        lines.append("")
    questions_md = "\n".join(lines).rstrip("\n") + "\n"

    return {"index.md": index_md, "registry.md": registry_md,
            "registry.json": registry_json, "backlinks.md": backlinks_md,
            "status.md": status_md, "open-questions.md": questions_md}


def freshness_findings(space: Space, warnings: list[Finding]) -> list[Finding]:
    rendered = render_views(space, warnings)
    findings: list[Finding] = []
    gen_dir = space.root / GENERATED_DIR
    for name, content in rendered.items():
        on_disk = gen_dir / name
        if not on_disk.is_file() or \
                on_disk.read_text(encoding="utf-8", errors="replace") != content:
            findings.append(Finding(
                "error", f"{GENERATED_DIR}/{name}", 1, "generated_freshness",
                "generated view is stale or missing",
                "run the render subcommand"))
    return findings


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def emit(findings: list[Finding], as_json: bool) -> int:
    ordered = sorted(findings, key=lambda f: (f.path, f.line, f.check, f.message))
    errors = sum(1 for f in ordered if f.severity == "error")
    warnings = len(ordered) - errors
    for f in ordered:
        if as_json:
            print(json.dumps({"severity": f.severity, "path": f.path,
                              "line": f.line, "check": f.check,
                              "message": f.message, "fix": f.remediation},
                             sort_keys=True))
        else:
            print(f"{f.severity.upper()} {f.path}:{f.line} [{f.check}]"
                  f" {f.message} | Fix: {f.remediation}")
    if not as_json:
        print(f"ba_compile: {errors} error(s), {warnings} warning(s)")
    return 1 if errors else 0


def load_schema(path: Path) -> dict:
    schema = json.loads(path.read_text(encoding="utf-8"))
    if schema.get("schema_version") != 1:
        raise SystemExit(f"ba_compile: unknown schema_version in {path}")
    return schema


# ---------------------------------------------------------------------------
# Stubs
# ---------------------------------------------------------------------------


def table_skeleton(columns: list[str]) -> list[str]:
    return ["| " + " | ".join(columns) + " |",
            "|" + "---|" * len(columns)]


def stub_lines(schema: dict, doc_type: str, title: str, **extra) -> list[str]:
    spec = schema["doc_types"][doc_type]
    fm = ["---", f"type: {doc_type}", f"title: {title}", "status: draft",
          "owner_role: business_analyst"]
    for key in spec["extra_frontmatter"]["required"]:
        value = extra.get(key)
        if isinstance(value, list):
            fm.append(f"{key}:")
            fm += [f"  - {v}" for v in value]
        else:
            fm.append(f"{key}: {value}")
    fm.append("---")
    body = ["", f"# {title}", "", f"One-line summary of {title}.", ""]
    section_titles = {token: token.replace("_", " ").title()
                      for token in spec["required_sections"]}
    row_by_section = {schema["row_schemas"][k.lower()]["section"]: k
                      for k in spec["mints"]
                      if schema["row_schemas"][k.lower()]["section"] in spec["required_sections"]}
    for token in spec["required_sections"]:
        body.append(f"## {section_titles[token]} <!-- sec: {token} -->")
        body.append("")
        kind = row_by_section.get(token)
        if kind:
            body += table_skeleton(schema["row_schemas"][kind.lower()]["columns"])
        else:
            body.append("To be analyzed.")
        body.append("")
    return fm + body


def write_stub(schema: dict, path: Path, doc_type: str, title: str, **extra) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(stub_lines(schema, doc_type, title, **extra)).rstrip("\n")
                    + "\n", encoding="utf-8")


def next_ids(space: Space, code: str) -> dict[str, str]:
    result = {}
    for kind in ("BR", "AC", "AS", "OQ", "DEC", "CH"):
        highest = 0
        for id_value, info in space.ids.items():
            m = NAMESPACED_ID_RE.fullmatch(id_value)
            if m and m.group(1) == kind and m.group(2) == code:
                highest = max(highest, int(m.group(3)))
        result[kind] = f"{kind}-{code}-{highest + 1:03d}"
    return result


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------


def cmd_init(args, schema: dict) -> int:
    space_dir = Path(args.space)
    if space_dir.is_dir() and any(space_dir.iterdir()):
        print(f"ba_compile: FAIL: {space_dir} already exists and is not empty",
              file=sys.stderr)
        return 1
    (space_dir / GENERATED_DIR).mkdir(parents=True, exist_ok=True)
    write_stub(schema, space_dir / "space.md", "space", args.title, code=args.code)
    write_stub(schema, space_dir / "glossary.md", "glossary", "Glossary")
    write_stub(schema, space_dir / "actors.md", "actor_roster", "Actors")
    write_stub(schema, space_dir / "budgets.md", "budget_set",
               "Non-Functional Budgets", scope="space")
    for name in ("glossary.md", "actors.md", "budgets.md"):
        path = space_dir / name
        text = path.read_text(encoding="utf-8")
        path.write_text(text.replace("To be analyzed.", "None stated, confirmed.")
                        if name == "budgets.md" else text, encoding="utf-8")
    print(f"ba_compile: space initialized at {space_dir} (code {args.code})")
    return 0


def cmd_stub(args, schema: dict) -> int:
    if args.type not in schema["doc_types"]:
        print(f"ba_compile: FAIL: unknown type '{args.type}'", file=sys.stderr)
        return 2
    space_dir = Path(args.space)
    spec = schema["doc_types"][args.type]
    loc = spec["location"]
    node = args.node.strip("/")
    extra: dict = {}
    if args.type == "domain":
        target = space_dir / node / "domain.md" if node else None
        if target is None or not node.split("/")[-2:][0]:
            print("ba_compile: FAIL: domain stubs need --node domains/<slug>",
                  file=sys.stderr)
            return 2
        extra["code"] = args.code or ""
    elif loc["kind"] == "named_file":
        target = space_dir / node / loc["name"] if node else space_dir / loc["name"]
        if args.type == "budget_set":
            extra["scope"] = "domain" if node else "space"
        if args.type == "space":
            extra["code"] = args.code or ""
    elif args.type == "challenge_record":
        name = (f"space-round-{args.round}.md" if args.review_scope == "space"
                else f"round-{args.round}.md")
        base = space_dir / node if node else space_dir
        target = base / loc["folder"] / name
    else:
        if not args.slug:
            print("ba_compile: FAIL: folder docs need --slug", file=sys.stderr)
            return 2
        base = space_dir / node if node else space_dir
        target = base / loc["folder"] / f"{args.slug}.md"
    if args.type == "rule_set":
        if not args.governs:
            print("ba_compile: FAIL: rule_set stubs need --governs", file=sys.stderr)
            return 2
        extra["governs"] = args.governs.split(",")
    if args.type == "acceptance_set":
        if not args.verifies:
            print("ba_compile: FAIL: acceptance_set stubs need --verifies",
                  file=sys.stderr)
            return 2
        extra["verifies"] = args.verifies.split(",")
    if args.type == "integration":
        extra["system_name"] = args.slug or ""
        extra["direction"] = args.direction
    if args.type == "challenge_record":
        extra["round"] = args.round
        extra["review_scope"] = args.review_scope
        extra["verdict"] = "continue"
    if target.exists():
        print(f"ba_compile: FAIL: {target} already exists", file=sys.stderr)
        return 1
    write_stub(schema, target, args.type, args.title, **extra)
    space, _ = scan_space(space_dir, schema)
    code = nearest_code(space, node)
    print(f"ba_compile: created {target}")
    if code:
        free = next_ids(space, code)
        print("ba_compile: next free ids: "
              + ", ".join(free[k] for k in sorted(free)))
    return 0


def cmd_check(args, schema: dict) -> int:
    space, base = scan_space(Path(args.space), schema)
    findings = run_checks(space, base, gate=args.gate == "approval",
                          gate_node=args.node)
    if not space.broken:
        warnings = [f for f in findings if f.severity == "warning"]
        findings += freshness_findings(space, warnings)
    return emit(findings, args.json)


def cmd_render(args, schema: dict) -> int:
    space, base = scan_space(Path(args.space), schema)
    if space.broken:
        emit([f for f in base if f.severity == "error"], args.json)
        print("ba_compile: FAIL: ambiguity findings block render", file=sys.stderr)
        return 1
    findings = run_checks(space, base)
    duplicate = [f for f in findings if f.check == "id_unique"]
    if duplicate:
        emit(duplicate, args.json)
        print("ba_compile: FAIL: duplicate ids block render", file=sys.stderr)
        return 1
    warnings = [f for f in findings if f.severity == "warning"]
    rendered = render_views(space, warnings)
    gen_dir = space.root / GENERATED_DIR
    if args.check_only:
        stale = freshness_findings(space, warnings)
        if stale:
            return emit(stale, args.json)
        print("ba_compile: generated views are fresh")
        return 0
    gen_dir.mkdir(parents=True, exist_ok=True)
    wrote = 0
    for name, content in rendered.items():
        target = gen_dir / name
        if target.is_file() and \
                target.read_text(encoding="utf-8", errors="replace") == content:
            continue
        target.write_text(content, encoding="utf-8")
        wrote += 1
    removed = 0
    for stray in sorted(gen_dir.iterdir()):
        if stray.name not in GENERATED_VIEWS and stray.name != ".gitkeep":
            stray.unlink()
            removed += 1
    print(f"ba_compile: rendered {wrote} view(s), removed {removed} stray file(s),"
          f" {len(rendered) - wrote} unchanged")
    return 0


def cmd_resolve(args, schema: dict) -> int:
    space, _ = scan_space(Path(args.space), schema)
    wanted = [i.strip() for i in args.ids.split(",") if i.strip()]
    result = {}
    missing = []
    for id_value in wanted:
        info = space.ids.get(id_value)
        if info is None:
            missing.append(id_value)
            continue
        statement = statement_of(space, id_value)
        result[id_value] = {
            "doc": info["doc"],
            "doc_status": doc_status(space.docs[info["doc"]]),
            "statement": statement,
            "statement_sha256": hashlib.sha256(statement.encode("utf-8")).hexdigest(),
        }
    print(json.dumps(result, indent=2, sort_keys=True))
    if missing:
        print(f"ba_compile: FAIL: unknown ids: {', '.join(missing)}", file=sys.stderr)
        return 1
    return 0


def cmd_verify_import(args, schema: dict) -> int:
    space, _ = scan_space(Path(args.space), schema)
    data = json.loads(Path(args.json_file).read_text(encoding="utf-8"))
    failures = []
    for entry in data.get("criteria", []):
        criterion = str(entry.get("criterion_id", ""))
        info = space.ids.get(criterion)
        if info is None:
            failures.append(f"{criterion}: not declared in the space")
            continue
        if str(entry.get("disposition", "")) == "deferred":
            continue
        owner_status = doc_status(space.docs[info["doc"]])
        if owner_status != "approved":
            failures.append(f"{criterion}: owning doc {info['doc']} is"
                            f" {owner_status}, not approved")
    for failure in failures:
        print(f"ba_compile: FAIL: {failure}", file=sys.stderr)
    if failures:
        return 1
    print(f"ba_compile: OK: {len(data.get('criteria', []))} criterion id(s) verified")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Compile and check a business-analysis space.")
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("init")
    p.add_argument("--space", required=True)
    p.add_argument("--title", required=True)
    p.add_argument("--code", required=True)

    p = sub.add_parser("stub")
    p.add_argument("--space", required=True)
    p.add_argument("--type", required=True)
    p.add_argument("--title", required=True)
    p.add_argument("--node", default="")
    p.add_argument("--slug", default="")
    p.add_argument("--code", default="")
    p.add_argument("--governs", default="")
    p.add_argument("--verifies", default="")
    p.add_argument("--direction", default="outbound")
    p.add_argument("--round", type=int, default=1)
    p.add_argument("--review-scope", default="domain")

    p = sub.add_parser("check")
    p.add_argument("--space", required=True)
    p.add_argument("--gate", choices=["approval"], default="")
    p.add_argument("--node", default="")
    p.add_argument("--json", action="store_true")

    p = sub.add_parser("render")
    p.add_argument("--space", required=True)
    p.add_argument("--check-only", action="store_true")
    p.add_argument("--json", action="store_true")

    p = sub.add_parser("resolve")
    p.add_argument("--space", required=True)
    p.add_argument("--ids", required=True)
    p.add_argument("--json", action="store_true")

    p = sub.add_parser("verify-import")
    p.add_argument("--space", required=True)
    p.add_argument("--json-file", required=True)

    args = parser.parse_args(argv)
    schema = load_schema(args.schema)
    handlers = {"init": cmd_init, "stub": cmd_stub, "check": cmd_check,
                "render": cmd_render, "resolve": cmd_resolve,
                "verify-import": cmd_verify_import}
    return handlers[args.command](args, schema)


if __name__ == "__main__":
    raise SystemExit(main())
