#!/usr/bin/env python3
"""Vault checker for the team's workspace docs tree (the product vault).

The consuming project's workspace/docs/ is one vault: wikilinked notes,
typed frontmatter, map hubs and a committed app payload. Every rule the
obsidian-vault skill states is enforced here; a rule without a check is
not a rule. Variation points (subtrees, map notes, tag namespaces, id
grammars, peer range, generated surfaces, property types) come from the
skill's data/vault-policy.json, never from constants.

Verbs:
  check            validate the vault (exit 0 clean/warnings, 1 errors)
  render-decisions render each decision tree's generated index
  stamp-decision   stamp a decision note's status (one clock, one write)
  migrate          apply the deterministic legacy-to-vault rewrites

Stdlib only. Findings sorted by (path, line, check). Wikilink resolution
runs against one posix-keyed file index, never the filesystem, so wrong
case or separators fail identically on every platform.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from ba_compile import (
    DATE_RE,
    INLINE_CODE_RE,
    LINK_RE,
    WIKILINK_RE,
    parse_frontmatter,
    split_wikilink,
)

DEFAULT_POLICY = (Path(__file__).resolve().parent.parent
                  / "skills" / "obsidian-vault" / "data" / "vault-policy.json")
DEFAULT_PAYLOAD = (Path(__file__).resolve().parent.parent
                   / "templates" / "vault" / ".obsidian")

GENERATED_INDEX_MARKER = (
    "<!-- generated by vault_check render-decisions; do not edit by hand -->")

# Every check id this tool can emit. The test suite's builder registry
# stays in lockstep with this tuple (same doctrine as ba_compile).
CHECK_IDS = (
    "vault_layout", "wikilink_resolution", "anchor_resolution",
    "link_policy", "table_pipe", "orphans", "moc_coverage", "nav_footer",
    "frontmatter_props", "tags_mirror", "decision_records",
    "generated_views", "home_shape", "obsidian_payload",
)

# Checks that judge the vault as a whole; --scope never silences them,
# because any session may repair their subjects (payload, layout).
GLOBAL_CHECKS = {"vault_layout", "obsidian_payload"}

PAYLOAD_FILES = ("app.json", "appearance.json", "core-plugins.json",
                 "graph.json", "types.json", "snippets/brand.css")

# app.json keys that change what the vault app WRITES; drift here makes
# the app author links against the law, so exact values are asserted.
APP_SENTINELS = {
    "useMarkdownLinks": False,
    "newLinkFormat": "absolute",
    "alwaysUpdateLinks": True,
}

# Frontmatter keys whose value cites another document; values are quoted
# vault-absolute wikilinks and draw graph edges.
DOC_REF_KEYS = ("supersedes", "superseded_by", "governs", "verifies",
                "engagement")

NAV_MARKER = "<!-- sec: nav -->"

BLOCK_ID_RE = re.compile(r"(?:^|\s)\^([a-z0-9]+(?:-[a-z0-9]+)*)\s*$")
FLOW_LIST_RE = re.compile(r"^\[.*\]$")


@dataclass(frozen=True)
class Finding:
    severity: str  # "error" | "warning"
    path: str
    line: int
    check: str
    message: str
    remediation: str


@dataclass
class Note:
    rel: str
    path: Path
    fm: dict
    fm_end: int
    fm_error: str | None
    lines: list[str]
    generated: bool
    subtree: str  # first path segment, "" for root-level notes
    wikilinks: list = field(default_factory=list)  # (line, embed, target, anchor, alias, raw_inner)
    mdlinks: list = field(default_factory=list)    # (line, text, target)
    fm_targets: list = field(default_factory=list)  # (key, target) wikilink values
    headings: list = field(default_factory=list)   # (line, text)
    block_ids: set = field(default_factory=set)


@dataclass
class Vault:
    root: Path
    policy: dict
    index: set = field(default_factory=set)   # every file, posix rel
    notes: dict = field(default_factory=dict)  # rel -> Note
    inbound: dict = field(default_factory=dict)  # rel -> set of citing rels


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_policy(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def utc_today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def rel_posix(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def is_table_row(line: str) -> bool:
    return line.lstrip().startswith("|")


def scan_note(root: Path, path: Path, marker_prefix: str) -> Note:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    generated = bool(lines) and lines[0].startswith(marker_prefix)
    fm, fm_end, fm_error = parse_frontmatter(text)
    rel = rel_posix(root, path)
    parts = rel.split("/")
    note = Note(
        rel=rel, path=path, fm=fm, fm_end=fm_end, fm_error=fm_error,
        lines=lines, generated=generated,
        subtree=parts[0] if len(parts) > 1 else "",
    )
    in_fence = False
    for lineno, line in enumerate(lines, start=1):
        if lineno < note.fm_end:
            continue
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        heading = re.match(r"^(#{1,6})\s+(.*)$", line)
        if heading:
            note.headings.append((lineno, heading.group(2).strip()))
        block = BLOCK_ID_RE.search(line)
        if block:
            note.block_ids.add(block.group(1))
        scrubbed = INLINE_CODE_RE.sub("", line)
        for match in WIKILINK_RE.finditer(scrubbed):
            target, anchor, alias = split_wikilink(match.group("inner"))
            note.wikilinks.append((lineno, match.group("embed") == "!",
                                   target, anchor, alias,
                                   match.group("inner")))
        for match in LINK_RE.finditer(scrubbed):
            note.mdlinks.append((lineno, match.group(1), match.group(2)))
    for key, value in note.fm.items():
        values = value if isinstance(value, list) else [value]
        for item in values:
            if isinstance(item, str) and item.startswith("[[") and item.endswith("]]"):
                target, _, _ = split_wikilink(item[2:-2])
                note.fm_targets.append((key, target))
    return note


def build_vault(root: Path, policy: dict) -> Vault:
    vault = Vault(root=root, policy=policy)
    marker_prefix = policy.get("generated_marker_prefix", "<!-- generated by")
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = rel_posix(root, path)
        if rel.split("/")[0] == ".trash":
            continue
        vault.index.add(rel)
        if path.suffix == ".md" and rel.split("/")[0] != ".obsidian":
            vault.notes[rel] = scan_note(root, path, marker_prefix)
    for note in vault.notes.values():
        targets = [t for (_, _, t, _, _, _) in note.wikilinks if t]
        targets.extend(t for (_, t) in note.fm_targets if t)
        for target in targets:
            vault.inbound.setdefault(f"{target}.md", set()).add(note.rel)
    return vault


def authored(vault: Vault) -> list[Note]:
    return [n for n in sorted(vault.notes.values(), key=lambda n: n.rel)
            if not n.generated]


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------


def check_vault_layout(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    home = policy["home_file"]
    maps_dir = policy["maps_dir"]
    if home not in vault.index:
        findings.append(Finding(
            "error", home, 1, "vault_layout",
            "vault has no home note",
            "materialize the vault payload (setup, or the stewardship copy"
            " rule) so navigation has a root"))
    for subtree in policy["subtrees"]:
        if not (vault.root / subtree).is_dir():
            continue
        map_rel = f"{maps_dir}/{subtree}.md"
        if map_rel not in vault.index:
            findings.append(Finding(
                "error", map_rel, 1, "vault_layout",
                f"subtree '{subtree}' has no map note",
                "seed the map from the vault payload and curate it"))
    for name in policy.get("extra_maps", []):
        map_rel = f"{maps_dir}/{name}.md"
        if map_rel not in vault.index:
            findings.append(Finding(
                "error", map_rel, 1, "vault_layout",
                f"map note '{name}' is missing",
                "seed it from the vault payload"))
    known_roots = set(policy["subtrees"]) | {
        maps_dir, ".obsidian", ".trash",
        policy.get("attachments_dir", "_attachments"),
    }
    known_roots.update(p.rstrip("/").split("/")[0]
                       for p in policy.get("generated_subtrees", []))
    known_files = {home, policy["start_here_file"]}
    known_files.update(v for v in policy.get("generated_views", [])
                       if "/" not in v)
    attachments = policy.get("attachments_dir", "_attachments")
    embedded = {t for note in vault.notes.values()
                for (_, embed, t, _, _, _) in note.wikilinks if embed}
    for rel in sorted(vault.index):
        top = rel.split("/")[0]
        if rel.rsplit("/", 1)[-1] == ".gitkeep":
            continue  # git plumbing for empty skeleton directories
        if rel.endswith(".base"):
            findings.append(Finding(
                "error", rel, 1, "vault_layout",
                "base files are not part of the vault contract",
                "views are markdown map notes and generated indexes;"
                " remove the base file"))
            continue
        if top == ".obsidian":
            continue
        if "/" not in rel:
            if rel.endswith(".md"):
                if rel not in known_files and rel not in {home}:
                    findings.append(Finding(
                        "error", rel, 1, "vault_layout",
                        f"root-level note '{rel}' is outside the vault layout",
                        "notes live inside a policy subtree; move it or"
                        " register the surface in vault-policy.json"))
            elif rel not in known_files:
                findings.append(Finding(
                    "error", rel, 1, "vault_layout",
                    f"root-level file '{rel}' is outside the vault layout",
                    "only policy-listed views and the payload live at the"
                    " vault root"))
            continue
        if top not in known_roots:
            findings.append(Finding(
                "error", rel, 1, "vault_layout",
                f"unknown top-level directory '{top}'",
                "vault subtrees are policy-listed; add it to"
                " vault-policy.json or move the content"))
        elif top == attachments:
            if rel not in embedded:
                findings.append(Finding(
                    "error", rel, 1, "vault_layout",
                    "attachment is not referenced by any embed",
                    "reference it with an embed wikilink or delete it"))
        elif not rel.endswith(".md") and top not in {
                p.rstrip("/").split("/")[0]
                for p in policy.get("generated_subtrees", [])}:
            findings.append(Finding(
                "error", rel, 1, "vault_layout",
                f"non-markdown file '{rel}' inside a note subtree",
                "attachments live under the attachments directory;"
                " transient working files leave the vault before the gate"))


def check_wikilink_resolution(vault: Vault, findings: list[Finding]) -> None:
    for note in authored(vault):
        for (lineno, embed, target, _anchor, _alias, _inner) in note.wikilinks:
            if not target:
                continue  # pure in-note anchor form is judged by anchor check
            resolved = (target in vault.index if embed
                        else f"{target}.md" in vault.index)
            if not resolved:
                findings.append(Finding(
                    "error", note.rel, lineno, "wikilink_resolution",
                    f"unresolved wikilink target '{target}'",
                    "targets are vault-absolute paths from the vault root"
                    " (no leading slash, forward slashes, exact case)"))


def check_anchor_resolution(vault: Vault, findings: list[Finding]) -> None:
    for note in authored(vault):
        for (lineno, _embed, target, anchor, _alias, _inner) in note.wikilinks:
            if not anchor:
                continue
            if not anchor.startswith("^"):
                findings.append(Finding(
                    "error", note.rel, lineno, "anchor_resolution",
                    f"heading anchor '#{anchor}' is banned",
                    "link the note itself, or a block id (#^block-id);"
                    " heading text is prose and dies silently"))
                continue
            target_note = vault.notes.get(f"{target}.md" if target else note.rel)
            if target_note and anchor[1:] not in target_note.block_ids:
                findings.append(Finding(
                    "error", note.rel, lineno, "anchor_resolution",
                    f"block anchor '{anchor}' does not exist in"
                    f" '{target or note.rel}'",
                    "add the ^block-id to the target line or fix the anchor"))


def check_link_policy(vault: Vault, findings: list[Finding]) -> None:
    for note in authored(vault):
        for (lineno, _text, target) in note.mdlinks:
            if target.startswith(("http://", "https://", "mailto:", "#", "/")):
                continue
            clean = target.split("#", 1)[0]
            if not clean:
                continue
            resolved = (note.path.parent / clean).resolve()
            try:
                resolved.relative_to(vault.root)
                inside = True
            except ValueError:
                inside = False
            if inside:
                findings.append(Finding(
                    "error", note.rel, lineno, "link_policy",
                    f"vault-internal citation uses a markdown link: {target}",
                    "cite vault content as a vault-absolute wikilink with an"
                    " alias; the migrate verb rewrites this class"))
            elif not resolved.exists():
                findings.append(Finding(
                    "warning", note.rel, lineno, "link_policy",
                    f"out-of-vault link target does not exist: {target}",
                    "fix the relative path or drop the link"))


def check_table_pipe(vault: Vault, findings: list[Finding]) -> None:
    for note in authored(vault):
        in_fence = False
        for lineno, line in enumerate(note.lines, start=1):
            if lineno < note.fm_end:
                continue
            if line.lstrip().startswith("```"):
                in_fence = not in_fence
                continue
            if in_fence or not is_table_row(line):
                continue
            for match in WIKILINK_RE.finditer(INLINE_CODE_RE.sub("", line)):
                inner = match.group("inner")
                if re.search(r"(?<!\\)\|", inner):
                    findings.append(Finding(
                        "error", note.rel, lineno, "table_pipe",
                        "unescaped alias pipe inside a table-cell wikilink",
                        "escape it as \\| or the pipe splits the row"))


def check_orphans(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    home = policy["home_file"]
    for note in authored(vault):
        if note.rel == home:
            continue  # the navigation root is exempt by definition
        if not vault.inbound.get(note.rel):
            findings.append(Finding(
                "error", note.rel, 1, "orphans",
                "note has no inbound wikilink",
                "link it from its map note or owning hub; every note is"
                " part of the graph or it does not exist"))


def check_moc_coverage(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    home = policy["home_file"]
    if home not in vault.notes:
        return  # vault_layout already reports the missing root
    reachable: set[str] = set()
    frontier = [home]
    while frontier:
        rel = frontier.pop()
        if rel in reachable:
            continue
        reachable.add(rel)
        note = vault.notes.get(rel)
        if note is None:
            continue
        targets = [t for (_, _, t, _, _, _) in note.wikilinks if t]
        targets.extend(t for (_, t) in note.fm_targets if t)
        for target in targets:
            frontier.append(f"{target}.md")
    for note in authored(vault):
        if note.rel not in reachable:
            findings.append(Finding(
                "error", note.rel, 1, "moc_coverage",
                "note is not reachable from the home note",
                "add it to its subtree map (directly or through a hub the"
                " map links)"))


def check_nav_footer(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    maps_dir = policy["maps_dir"]
    exempt = {policy["home_file"], policy["start_here_file"]}
    peer_min = policy["nav_peer_min"]
    peer_max = policy["nav_peer_max"]
    subtree_counts: dict[str, int] = {}
    for note in authored(vault):
        subtree_counts[note.subtree] = subtree_counts.get(note.subtree, 0) + 1
    for note in authored(vault):
        if note.rel in exempt or note.subtree == maps_dir or not note.subtree:
            continue
        nav_line = next((i for i, line in enumerate(note.lines, start=1)
                         if NAV_MARKER in line), None)
        if nav_line is None:
            findings.append(Finding(
                "error", note.rel, max(len(note.lines), 1), "nav_footer",
                f"note has no nav section ({NAV_MARKER})",
                "end every leaf with the nav section: first wikilink is the"
                " owning map, then the contextual peers"))
            continue
        links = [(lineno, target)
                 for (lineno, embed, target, _a, _al, _inner) in note.wikilinks
                 if lineno >= nav_line and target and not embed]
        owning_map = f"{maps_dir}/{note.subtree}"
        if not links or links[0][1] != owning_map:
            findings.append(Finding(
                "error", note.rel, nav_line, "nav_footer",
                f"nav section's first wikilink must be the owning map"
                f" '{owning_map}'",
                "the up-edge is positional: owning map first, peers after"))
            continue
        peers = [t for (_, t) in links[1:] if f"{t}.md" in vault.index]
        floor = min(peer_min, max(subtree_counts.get(note.subtree, 1) - 1, 0))
        if not floor <= len(peers) <= peer_max:
            findings.append(Finding(
                "error", note.rel, nav_line, "nav_footer",
                f"nav section has {len(peers)} resolving peer links"
                f" (policy range {floor}-{peer_max})",
                "link the contextual peers a reader would jump to next"))


def property_type_ok(value, expected: str) -> bool:
    if expected == "list":
        return isinstance(value, list)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "checkbox":
        return isinstance(value, bool)
    if expected in ("date", "datetime"):
        return isinstance(value, str) and bool(DATE_RE.match(value[:10]))
    return isinstance(value, str)


def check_frontmatter_props(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    prop_types = policy.get("property_types", {})
    for note in authored(vault):
        if note.fm_error:
            findings.append(Finding(
                "error", note.rel, 1, "frontmatter_props",
                f"frontmatter: {note.fm_error}",
                "every authored note opens with a frontmatter block"))
            continue
        for key in ("type",):
            if not note.fm.get(key):
                findings.append(Finding(
                    "error", note.rel, 1, "frontmatter_props",
                    f"frontmatter floor: '{key}' is missing",
                    "every authored note declares its type"))
        for key in ("tag", "alias", "cssclass"):
            if key in note.fm:
                findings.append(Finding(
                    "error", note.rel, 1, "frontmatter_props",
                    f"singular '{key}:' key is dead vault grammar",
                    f"use the list key '{key}s' (dash items, one per line)"))
        for key in ("tags", "aliases"):
            if key not in note.fm:
                continue
            value = note.fm[key]
            if isinstance(value, str):
                shape = ("inline flow list" if FLOW_LIST_RE.match(value)
                         else "scalar")
                findings.append(Finding(
                    "error", note.rel, 1, "frontmatter_props",
                    f"'{key}' is a {shape}; the contract is a block list",
                    f"write '{key}:' then one '- item' line per value"))
        if "tags" not in note.fm:
            findings.append(Finding(
                "error", note.rel, 1, "frontmatter_props",
                "frontmatter floor: 'tags' is missing",
                "every authored note carries its tag mirror"))
        for key, expected in sorted(prop_types.items()):
            if key in note.fm and not property_type_ok(note.fm[key], expected):
                findings.append(Finding(
                    "error", note.rel, 1, "frontmatter_props",
                    f"'{key}' does not match its vault-wide property type"
                    f" '{expected}'",
                    "one value type per key, vault-wide; dates are"
                    " YYYY-MM-DD"))
        for key, target in note.fm_targets:
            if target and f"{target}.md" not in vault.index:
                findings.append(Finding(
                    "error", note.rel, 1, "frontmatter_props",
                    f"frontmatter link '{key}' targets missing note"
                    f" '{target}'",
                    "frontmatter links are vault-absolute wikilinks to"
                    " existing notes"))
        for lineno in range(1, note.fm_end - 1):
            if lineno - 1 >= len(note.lines):
                break
            raw = note.lines[lineno - 1]
            if re.match(r"^\s*(?:- )?(?:[a-z0-9_]+:)?\s*\[\[", raw):
                findings.append(Finding(
                    "error", note.rel, lineno, "frontmatter_props",
                    "unquoted wikilink in frontmatter",
                    "quote wikilink values (\"[[...]]\") or the frontmatter"
                    " is not valid YAML to the vault app"))


def kebab(value: str) -> str:
    return str(value).replace("_", "-").lower()


def check_tags_mirror(vault: Vault, findings: list[Finding]) -> None:
    for note in authored(vault):
        tags = note.fm.get("tags")
        note_type = note.fm.get("type")
        if not isinstance(tags, list) or not note_type:
            continue  # the frontmatter floor already reports the shape
        expected = {f"doc/{kebab(note_type)}"}
        status = note.fm.get("status")
        if status:
            expected.add(f"status/{kebab(status)}")
        if set(tags) != expected:
            findings.append(Finding(
                "error", note.rel, 1, "tags_mirror",
                f"tags {sorted(tags)} must be exactly {sorted(expected)}",
                "tags are the script-stamped mirror of type and status;"
                " never hand-pick tags"))


def decision_notes(vault: Vault, tree: dict) -> list[Note]:
    prefix = tree["path"].rstrip("/") + "/"
    return [n for n in sorted(vault.notes.values(), key=lambda n: n.rel)
            if n.rel.startswith(prefix) and not n.generated]


def decision_filename_re(tree: dict) -> re.Pattern:
    return re.compile(
        rf"^{tree['id_prefix'].lower()}-(\d{{{tree['id_min_width']},}})"
        rf"-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")


def decision_id(tree: dict, note_rel: str) -> str | None:
    match = decision_filename_re(tree).match(note_rel.rsplit("/", 1)[-1])
    if not match:
        return None
    return f"{tree['id_prefix']}-{match.group(1)}"


def check_decision_records(vault: Vault, findings: list[Finding]) -> None:
    for tree_name, tree in sorted(vault.policy.get("decision_trees", {}).items()):
        seen: dict[str, str] = {}
        notes = decision_notes(vault, tree)
        for note in notes:
            rec_id = decision_id(tree, note.rel)
            if rec_id is None:
                findings.append(Finding(
                    "error", note.rel, 1, "decision_records",
                    f"filename does not match the {tree['id_prefix']} note"
                    " grammar",
                    f"decision notes are {tree['id_prefix'].lower()}-"
                    f"<{tree['id_min_width']}+ digits>-<kebab-slug>.md"))
                continue
            number = rec_id.split("-")[1]
            if number in seen:
                findings.append(Finding(
                    "error", note.rel, 1, "decision_records",
                    f"decision id number {number} already minted by"
                    f" {seen[number]}",
                    "ids are unique per tree; renumber the younger note and"
                    " rewrite its referrers in the same commit"))
            else:
                seen[number] = note.rel
            first_heading = note.headings[0][1] if note.headings else ""
            if not first_heading.startswith(f"{rec_id}: "):
                findings.append(Finding(
                    "error", note.rel,
                    note.headings[0][0] if note.headings else 1,
                    "decision_records",
                    f"first heading must read '{rec_id}: <title>'",
                    "the id leads the heading so previews and the graph"
                    " show it"))
            aliases = note.fm.get("aliases")
            if not (isinstance(aliases, list) and rec_id in aliases):
                findings.append(Finding(
                    "error", note.rel, 1, "decision_records",
                    f"aliases must contain the bare id '{rec_id}'",
                    "the alias makes the bare id searchable and linkable"))
            for key in ("supersedes", "superseded_by"):
                target = dict(note.fm_targets).get(key, "")
                raw = note.fm.get(key, "")
                if raw and not target:
                    findings.append(Finding(
                        "error", note.rel, 1, "decision_records",
                        f"'{key}' must be a quoted wikilink or empty",
                        "the supersede chain is a pair of frontmatter"
                        " wikilinks"))
            fm_map = dict(note.fm_targets)
            other_rel = (f"{fm_map['superseded_by']}.md"
                         if "superseded_by" in fm_map else None)
            if other_rel:
                other = vault.notes.get(other_rel)
                back = dict(other.fm_targets).get("supersedes", "") if other else ""
                if not other or f"{back}.md" != note.rel:
                    findings.append(Finding(
                        "error", note.rel, 1, "decision_records",
                        "supersede chain is not symmetric",
                        "stamp-decision writes both ends in one operation;"
                        " never hand-edit the chain"))
        index_rel = index_path_for(tree)
        expected = render_decision_index(vault, tree)
        actual_path = vault.root / index_rel
        actual = (actual_path.read_text(encoding="utf-8", errors="replace")
                  if actual_path.is_file() else "")
        if notes and actual != expected:
            findings.append(Finding(
                "error", index_rel, 1, "decision_records",
                f"decision index is stale for tree '{tree_name}'",
                "run the render-decisions verb; the index is generated,"
                " never merged by hand"))


def check_generated_views(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    marker_prefix = policy.get("generated_marker_prefix", "<!-- generated by")
    decision_indexes = {index_path_for(tree)
                        for tree in policy.get("decision_trees", {}).values()}
    for view in policy.get("generated_views", []):
        path = vault.root / view
        if not path.is_file():
            if view in decision_indexes:
                owners = [t for t in policy["decision_trees"].values()
                          if index_path_for(t) == view]
                if not any(decision_notes(vault, t) for t in owners):
                    continue  # an index is born with its first decision
            findings.append(Finding(
                "error", view, 1, "generated_views",
                "policy-listed generated view is missing",
                "render it with its owning verb (render backlog/ledger,"
                " render-decisions)"))
            continue
        first = path.read_text(encoding="utf-8",
                               errors="replace").splitlines()
        if not first or not first[0].startswith(marker_prefix):
            findings.append(Finding(
                "error", view, 1, "generated_views",
                "generated view lacks the first-line marker",
                "re-render it; a marker-less copy dodges the edit guard"))


def check_home_shape(vault: Vault, findings: list[Finding]) -> None:
    policy = vault.policy
    maps_dir = policy["maps_dir"]
    home = vault.notes.get(policy["home_file"])
    start_stem = policy["start_here_file"].rsplit(".", 1)[0]
    if home is not None:
        for (lineno, _e, target, _a, _al, _inner) in home.wikilinks:
            if not (target.startswith(f"{maps_dir}/") or target == start_stem):
                findings.append(Finding(
                    "error", home.rel, lineno, "home_shape",
                    f"home links '{target}'; home links only map notes",
                    "the graph star topology depends on home -> maps ->"
                    " docs; move the link into the owning map"))
        if home.fm.get("type") != "home":
            findings.append(Finding(
                "error", home.rel, 1, "home_shape",
                "home note must carry type: home",
                "home and maps are navigation, typed as such"))
    for rel, note in sorted(vault.notes.items()):
        if not rel.startswith(f"{maps_dir}/") or note.generated:
            continue
        if note.fm.get("type") != "moc":
            findings.append(Finding(
                "error", rel, 1, "home_shape",
                "map note must carry type: moc",
                "maps are navigation hubs, typed as such"))
        if "status" in note.fm:
            findings.append(Finding(
                "error", rel, 1, "home_shape",
                "map notes carry no status lifecycle",
                "navigation is never draft or approved; drop the key"))


def check_obsidian_payload(vault: Vault, findings: list[Finding],
                           payload_dir: Path | None) -> None:
    policy = vault.policy
    obsidian = vault.root / ".obsidian"
    for name in PAYLOAD_FILES:
        if not (obsidian / name).is_file():
            findings.append(Finding(
                "error", f".obsidian/{name}", 1, "obsidian_payload",
                "committed payload file is missing",
                "copy the vault payload (per-file, only where missing)"))
    app_path = obsidian / "app.json"
    if app_path.is_file():
        try:
            app = json.loads(app_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            app = None
            findings.append(Finding(
                "error", ".obsidian/app.json", 1, "obsidian_payload",
                "app.json does not parse", "restore it from the payload"))
        if isinstance(app, dict):
            sentinels = dict(APP_SENTINELS)
            sentinels["attachmentFolderPath"] = policy.get(
                "attachments_dir", "_attachments")
            for key, expected in sentinels.items():
                if app.get(key) != expected:
                    findings.append(Finding(
                        "error", ".obsidian/app.json", 1, "obsidian_payload",
                        f"app.json {key} must be {json.dumps(expected)}",
                        "these keys control what the vault app writes;"
                        " drift makes the app author against the law"))
    core_path = obsidian / "core-plugins.json"
    if core_path.is_file():
        try:
            core = json.loads(core_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            core = None
            findings.append(Finding(
                "error", ".obsidian/core-plugins.json", 1, "obsidian_payload",
                "core-plugins.json does not parse",
                "restore it from the payload"))
        bases_on = (("bases" in core) if isinstance(core, list)
                    else bool(core.get("bases")) if isinstance(core, dict)
                    else False)
        if bases_on:
            findings.append(Finding(
                "error", ".obsidian/core-plugins.json", 1, "obsidian_payload",
                "the bases plugin is off in this vault generation",
                "views are markdown maps and generated indexes; disable it"))
    types_path = obsidian / "types.json"
    if types_path.is_file():
        try:
            types = json.loads(types_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            types = {}
            findings.append(Finding(
                "error", ".obsidian/types.json", 1, "obsidian_payload",
                "types.json does not parse", "restore it from the payload"))
        declared = types.get("types", {}) if isinstance(types, dict) else {}
        for key, expected in sorted(policy.get("property_types", {}).items()):
            if declared.get(key) != expected:
                findings.append(Finding(
                    "error", ".obsidian/types.json", 1, "obsidian_payload",
                    f"property '{key}' must be typed '{expected}'",
                    "types.json is derived from vault-policy.json"
                    " property_types; restore the drifted entry"))


CHECKS = {
    "vault_layout": check_vault_layout,
    "wikilink_resolution": check_wikilink_resolution,
    "anchor_resolution": check_anchor_resolution,
    "link_policy": check_link_policy,
    "table_pipe": check_table_pipe,
    "orphans": check_orphans,
    "moc_coverage": check_moc_coverage,
    "nav_footer": check_nav_footer,
    "frontmatter_props": check_frontmatter_props,
    "tags_mirror": check_tags_mirror,
    "decision_records": check_decision_records,
    "generated_views": check_generated_views,
    "home_shape": check_home_shape,
}

# Per-file checks the --changed fast path (the per-write hook) runs.
CHANGED_CHECKS = ("wikilink_resolution", "anchor_resolution", "link_policy",
                  "table_pipe", "nav_footer", "frontmatter_props",
                  "tags_mirror", "decision_records")


# ---------------------------------------------------------------------------
# Rendering and stamping
# ---------------------------------------------------------------------------


def index_path_for(tree: dict) -> str:
    parent = tree["path"].rstrip("/").rsplit("/", 1)[0]
    return f"{parent}/decision-log.md"


def escape_pipe(text: str) -> str:
    return text.replace("|", "\\|")


def render_decision_index(vault: Vault, tree: dict) -> str:
    notes = decision_notes(vault, tree)
    rows = []
    extra = tree.get("extra_column", "territory")
    for note in sorted(
            notes,
            key=lambda n: int((decision_id(tree, n.rel) or "X-0").split("-")[1])
            if decision_id(tree, n.rel) else 0):
        rec_id = decision_id(tree, note.rel) or note.rel
        target = note.rel[:-3]
        superseded = dict(note.fm_targets).get("superseded_by", "")
        superseded_cell = (
            f"[[{superseded}\\|{(vault.notes.get(superseded + '.md') or note).fm.get('title', superseded)}]]"
            if superseded else "")
        rows.append(
            f"| [[{target}\\|{rec_id}]] "
            f"| {escape_pipe(str(note.fm.get('title', '')))} "
            f"| {note.fm.get('status', '')} "
            f"| {escape_pipe(str(note.fm.get(extra, '')))} "
            f"| {note.fm.get('decided_at', '')} "
            f"| {escape_pipe(str(note.fm.get('revisit_trigger', '')))} "
            f"| {superseded_cell} |")
    header = (f"{GENERATED_INDEX_MARKER}\n\n# Decision Log\n\n"
              f"| id | title | status | {extra} | decided "
              f"| revisit trigger | superseded by |\n"
              f"|---|---|---|---|---|---|---|\n")
    return header + "\n".join(rows) + ("\n" if rows else "")


def cmd_render_decisions(args, policy: dict) -> int:
    vault = build_vault(args.vault.resolve(), policy)
    for tree_name, tree in sorted(policy.get("decision_trees", {}).items()):
        notes = decision_notes(vault, tree)
        numbers: dict[str, str] = {}
        for note in notes:
            rec_id = decision_id(tree, note.rel)
            if rec_id is None:
                continue
            number = rec_id.split("-")[1]
            if number in numbers:
                print(f"vault_check: refuse to render '{tree_name}':"
                      f" duplicate id number {number}"
                      f" ({numbers[number]} vs {note.rel})", file=sys.stderr)
                return 1
            numbers[number] = note.rel
        if not notes:
            continue
        index_rel = index_path_for(tree)
        path = vault.root / index_rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_decision_index(vault, tree), encoding="utf-8")
        print(f"vault_check: rendered {index_rel} ({len(notes)} records)")
    return 0


def restamp(note_path: Path, stamps: dict[str, str],
            status: str | None) -> None:
    """Rewrite scalar frontmatter values and the status/ tag in one write."""
    text = note_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    out: list[str] = []
    in_fm = False
    fm_done = False
    in_tags = False
    pending = dict(stamps)
    for line in lines:
        stripped = line.strip()
        if not fm_done and stripped == "---":
            if in_fm:
                for key, value in pending.items():
                    out.append(f"{key}: {value}")
                pending.clear()
                fm_done = True
            else:
                in_fm = True
            out.append(line)
            continue
        if in_fm and not fm_done:
            if in_tags and stripped.startswith("- "):
                if status and stripped[2:].strip().startswith("status/"):
                    indent = line[:len(line) - len(line.lstrip())]
                    out.append(f"{indent}- status/{status.replace('_', '-')}")
                else:
                    out.append(line)
                continue
            in_tags = False
            key = stripped.partition(":")[0].strip()
            if key in pending and ":" in stripped:
                out.append(f"{key}: {pending.pop(key)}")
                continue
            if re.match(r"^tags:\s*$", stripped):
                in_tags = True
        out.append(line)
    note_path.write_text("\n".join(out) + ("\n" if text.endswith("\n") else ""),
                         encoding="utf-8")


def cmd_stamp_decision(args, policy: dict) -> int:
    root = args.vault.resolve()
    vault = build_vault(root, policy)
    note_rel = args.note.replace("\\", "/")
    note = vault.notes.get(note_rel)
    tree = next((t for t in policy.get("decision_trees", {}).values()
                 if note_rel.startswith(t["path"].rstrip("/") + "/")), None)
    if note is None or tree is None:
        print(f"vault_check: '{args.note}' is not a decision note",
              file=sys.stderr)
        return 2
    stamps = {"status": args.status, "decided_at": utc_today()}
    if args.supersedes:
        old_rel = args.supersedes.replace("\\", "/")
        old = vault.notes.get(old_rel)
        if old is None:
            print(f"vault_check: supersedes target '{old_rel}' not found",
                  file=sys.stderr)
            return 2
        stamps["supersedes"] = f"\"[[{old_rel[:-3]}]]\""
        restamp(old.path,
                {"status": "superseded",
                 "superseded_by": f"\"[[{note_rel[:-3]}]]\""},
                "superseded")
    restamp(note.path, stamps, args.status)
    print(f"vault_check: stamped {note_rel} status={args.status}")
    return cmd_render_decisions(args, policy)


# ---------------------------------------------------------------------------
# Migrate: the deterministic legacy-to-vault rewrites
# ---------------------------------------------------------------------------


def migrate_note(vault: Vault, note: Note) -> tuple[str, int, int]:
    """Return (new_text, rewrites, manual_left) for one note."""
    root = vault.root
    rewrites = 0
    manual = 0
    out: list[str] = []
    in_fence = False
    for lineno, line in enumerate(note.lines, start=1):
        if lineno < note.fm_end:
            new_line, n = migrate_fm_line(vault, note, line)
            rewrites += n
            out.append(new_line)
            continue
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            out.append(line)
            continue
        if in_fence:
            out.append(line)
            continue
        new_line = line
        for match in sorted(LINK_RE.finditer(line),
                            key=lambda m: -m.start()):
            text_part, target = match.group(1), match.group(2)
            if target.startswith(("http://", "https://", "mailto:", "#", "/")):
                continue
            clean, _, fragment = target.partition("#")
            if fragment and not fragment.startswith("^"):
                manual += 1  # heading anchors need judgment, not rewriting
                continue
            resolved = (note.path.parent / clean).resolve()
            try:
                rel = resolved.relative_to(root).as_posix()
            except ValueError:
                continue
            if rel not in vault.index or not rel.endswith(".md"):
                continue
            alias = text_part.replace("\\|", "|")
            inner = rel[:-3] + (f"#{fragment}" if fragment else "")
            sep = "\\|" if is_table_row(line) else "|"
            new_line = (new_line[:match.start()]
                        + f"[[{inner}{sep}{alias}]]"
                        + new_line[match.end():])
            rewrites += 1
        if is_table_row(new_line):
            fixed = fix_table_pipes(new_line)
            if fixed != new_line:
                rewrites += 1
                new_line = fixed
        out.append(new_line)
    text = "\n".join(out)
    if note.lines and note.path.read_text(encoding="utf-8").endswith("\n"):
        text += "\n"
    return text, rewrites, manual


def fix_table_pipes(line: str) -> str:
    def fix(match: re.Match) -> str:
        inner = match.group("inner")
        fixed_inner = re.sub(r"(?<!\\)\|", r"\\|", inner)
        return f"{match.group('embed')}[[{fixed_inner}]]"
    return WIKILINK_RE.sub(fix, line)


def migrate_fm_line(vault: Vault, note: Note, line: str) -> tuple[str, int]:
    stripped = line.strip()
    for key in DOC_REF_KEYS:
        if not stripped.startswith(f"{key}:"):
            continue
        value = stripped[len(key) + 1:].strip().strip("\"'")
        if not value or value.startswith("[["):
            return line, 0
        resolved = (note.path.parent / value).resolve()
        try:
            rel = resolved.relative_to(vault.root).as_posix()
        except ValueError:
            return line, 0
        if rel in vault.index and rel.endswith(".md"):
            indent = line[:len(line) - len(line.lstrip())]
            return f"{indent}{key}: \"[[{rel[:-3]}]]\"", 1
    return line, 0


def migrate_tags(note: Note) -> tuple[list[str], bool]:
    note_type = note.fm.get("type")
    if not note_type:
        return [], False
    expected = [f"doc/{kebab(note_type)}"]
    status = note.fm.get("status")
    if status:
        expected.append(f"status/{kebab(status)}")
    current = note.fm.get("tags")
    if isinstance(current, list) and set(current) == set(expected):
        return expected, False
    return expected, True


def apply_tags(text: str, tags: list[str]) -> str:
    lines = text.splitlines()
    out: list[str] = []
    in_fm = False
    fm_closed = False
    skipping = False
    wrote = False
    for line in lines:
        stripped = line.strip()
        if stripped == "---" and not fm_closed:
            if in_fm:
                if not wrote:
                    out.append("tags:")
                    out.extend(f"  - {t}" for t in tags)
                    wrote = True
                fm_closed = True
                in_fm = False
            else:
                in_fm = True
            out.append(line)
            continue
        if in_fm:
            if skipping:
                if stripped.startswith("- "):
                    continue
                skipping = False
            if stripped.startswith("tags:") or stripped.startswith("tag:"):
                out.append("tags:")
                out.extend(f"  - {t}" for t in tags)
                wrote = True
                skipping = True
                continue
        out.append(line)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def cmd_migrate(args, policy: dict) -> int:
    root = args.vault.resolve()
    vault = build_vault(root, policy)
    total_rewrites = 0
    total_manual = 0
    touched = 0
    for note in authored(vault):
        if args.scope and not (note.rel.startswith(args.scope.rstrip("/") + "/")
                               or note.subtree == ""):
            continue
        text, rewrites, manual = migrate_note(vault, note)
        tags, tags_changed = migrate_tags(note)
        if tags_changed:
            text = apply_tags(text, tags)
            rewrites += 1
        total_manual += manual
        if rewrites:
            note.path.write_text(text, encoding="utf-8")
            touched += 1
            total_rewrites += rewrites
            print(f"vault_check: migrated {note.rel} ({rewrites} rewrites)")
    print(f"vault_check: migrate touched {touched} notes,"
          f" {total_rewrites} rewrites;"
          f" {total_manual} heading-anchor links left for stewardship")
    return 0


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


def scoped(findings: list[Finding], policy: dict,
           scope: str | None) -> list[Finding]:
    if not scope:
        return findings
    keep_prefixes = (scope.rstrip("/") + "/", policy["maps_dir"] + "/",
                     ".obsidian/")
    keep_files = {policy["home_file"], policy["start_here_file"]}
    return [f for f in findings
            if f.check in GLOBAL_CHECKS
            or f.path.startswith(keep_prefixes)
            or f.path in keep_files]


def excluded(findings: list[Finding], excludes: list[str]) -> list[Finding]:
    if not excludes:
        return findings
    normalized = set()
    for raw in excludes:
        p = raw.replace("\\", "/")
        for prefix in ("workspace/docs/", "docs/"):
            if p.startswith(prefix):
                p = p[len(prefix):]
                break
        normalized.add(p)
    out: list[Finding] = []
    for f in findings:
        if f.path in normalized:
            out.append(Finding("warning", f.path, f.line, f.check,
                               f.message + " (excluded path)",
                               f.remediation))
        else:
            out.append(f)
    return out


def cmd_check(args, policy: dict) -> int:
    root = args.vault.resolve()
    if not root.is_dir():
        print(f"vault_check: vault directory not found: {args.vault}",
              file=sys.stderr)
        return 2
    vault = build_vault(root, policy)
    findings: list[Finding] = []
    if args.changed:
        changed_rel = args.changed.replace("\\", "/")
        for prefix in ("workspace/docs/", "docs/"):
            if changed_rel.startswith(prefix):
                changed_rel = changed_rel[len(prefix):]
                break
        if changed_rel in vault.notes and not vault.notes[changed_rel].generated:
            for check_id in CHANGED_CHECKS:
                sub: list[Finding] = []
                CHECKS[check_id](vault, sub)
                findings.extend(f for f in sub if f.path == changed_rel)
    else:
        for check_id, check in CHECKS.items():
            check(vault, findings)
        check_obsidian_payload(vault, findings, args.payload)
        findings = scoped(findings, policy, args.scope)
    findings = excluded(findings, args.exclude or [])
    findings.sort(key=lambda f: (f.path, f.line, f.check, f.message))
    errors = [f for f in findings if f.severity == "error"]
    warnings = [f for f in findings if f.severity == "warning"]
    for f in findings:
        if args.json:
            print(json.dumps(f.__dict__, sort_keys=True))
        else:
            print(f"{f.severity.upper():7} {f.path}:{f.line} [{f.check}]"
                  f" {f.message} | Fix: {f.remediation}")
    print(f"vault_check: {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--policy", type=Path, default=DEFAULT_POLICY)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("check")
    p.add_argument("--vault", type=Path, required=True)
    p.add_argument("--scope", default=None)
    p.add_argument("--exclude", action="append", default=[])
    p.add_argument("--payload", type=Path, default=DEFAULT_PAYLOAD)
    p.add_argument("--changed", default=None)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_check)

    p = sub.add_parser("render-decisions")
    p.add_argument("--vault", type=Path, required=True)
    p.set_defaults(func=cmd_render_decisions)

    p = sub.add_parser("stamp-decision")
    p.add_argument("--vault", type=Path, required=True)
    p.add_argument("--note", required=True)
    p.add_argument("--status", required=True,
                   choices=["proposed", "accepted", "rejected", "superseded"])
    p.add_argument("--supersedes", default=None)
    p.set_defaults(func=cmd_stamp_decision)

    p = sub.add_parser("migrate")
    p.add_argument("--vault", type=Path, required=True)
    p.add_argument("--scope", default=None)
    p.set_defaults(func=cmd_migrate)

    args = parser.parse_args(argv)
    try:
        policy = load_policy(args.policy)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"vault_check: cannot load policy {args.policy}: {exc}",
              file=sys.stderr)
        return 2
    return args.func(args, policy)


if __name__ == "__main__":
    raise SystemExit(main())
