#!/usr/bin/env python3
"""Materialize one team's Codex project agents and whole-file project contract."""

from __future__ import annotations

import argparse
import functools
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Callable, Optional

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import atomic_file
import host_listing
import project_config
import project_instructions
import marketplace_paths
import role_settings


HOST = "codex"
OWNER_RE = re.compile(
    r"^# Generated by Agent Marketplace ([a-z0-9]+(?:-[a-z0-9]+)*); do not edit by hand\.$"
)
# auto renders the package's resolved role settings; inherit omits `model` so
# every role follows the parent session's model, and keeps
# `model_reasoning_effort`, without which a role runs the parent's effort.
# Only a non-default profile is recorded, on the line after the owner header,
# so refreshes keep it.
EXECUTION_PROFILES = ("auto", "inherit")
DEFAULT_EXECUTION_PROFILE = "auto"
PROFILE_RE = re.compile(r"^# Execution profile: ([a-z0-9]+(?:-[a-z0-9]+)*)$")
ROLE_SETTINGS = ("model", "model_reasoning_effort")
SETTING_RE = re.compile(r"\S+")
READ_ONLY_TOOLS = {"Read", "Grep", "Glob"}
# Under auto, the roles of a pinned model that cannot run are rendered like
# inherit: without `model`, with their own effort, and their files record
# why. Apply judges every pinned model against this Codex's own model list
# and records an unavailable one, so check and inspect render it the same;
# the next apply judges it again. A run-time record, which --inherit-model
# writes, stays until --restore-model for that model or --execution-profile
# auto.
UNAVAILABLE_RE = re.compile(r"^# Model unavailable: (\S+)$")
FALLBACK_RE = re.compile(r"^# Model fallback: (\S+)$")
AGENTS_DIR = Path(".codex") / "agents"
FALLBACK_REASONS = {
    "requested": "is marked unavailable by --inherit-model",
    "recorded": "is recorded unavailable by --inherit-model in the managed agent files",
}
SESSION_PHRASE = "the parent session's model"
# Codex loads a role file each time it spawns the role, and the project
# instructions only when a session starts.
INSTRUCTIONS_NOTICE = (
    "Start a new Codex session before the next workflow: Codex loads the project"
    " instructions this run wrote only when a session starts."
)
ROLES_NOTICE = (
    "This run wrote only role files under .codex/agents/, which Codex loads each time it"
    " spawns a role, so the next spawn runs them."
)


def plugin_name(plugin_root: Path) -> str:
    for manifest in (
        plugin_root / ".codex-plugin" / "plugin.json",
        plugin_root / ".claude-plugin" / "plugin.json",
    ):
        try:
            value = json.loads(manifest.read_text(encoding="utf-8")).get("name", "")
            if re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", str(value)):
                return str(value)
        except Exception:
            continue
    raise ValueError("plugin manifest has no valid name")


def owner(team: str) -> str:
    return f"# Generated by Agent Marketplace {team}; do not edit by hand."


def parse_agent(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise ValueError(f"{path}: unclosed frontmatter")
    fields: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fields[key.strip()] = value.strip().strip("\"'")
    return fields, text[end + 5:].strip() + "\n"


def agent_toml(
    fields: dict[str, str], body: str, team: str,
    profile: str = DEFAULT_EXECUTION_PROFILE,
    fallbacks: frozenset = frozenset(),
    unavailable: frozenset = frozenset(),
    stamp: Optional[str] = None,
) -> str:
    """Render one role file; ``fallbacks`` are the models of a run-time record,
    ``unavailable`` those a model check judged unavailable and ``stamp`` the
    header line of the settings it renders from."""
    name = fields.get("name", "")
    description = fields.get("description", "")
    if not name or not description:
        raise ValueError("agent requires name and description")
    if "reasoning" in fields:
        raise ValueError(
            f"agent {name!r} carries an unresolved reasoning tier; rebuild the package"
        )
    if profile not in EXECUTION_PROFILES:
        raise ValueError(f"unsupported execution profile {profile!r}")
    instructions = (
        body
        + "\nCodex host rules:\n"
        + "- Treat the parent spawn prompt as the task boundary.\n"
        + "- Read every bound Agent Marketplace skill from the exact canonical path in the prompt.\n"
        + "- Return only the declared output contract and the required SELF-CHECK.\n"
    )
    model = fields.get("model")
    fallback = profile == DEFAULT_EXECUTION_PROFILE and model in fallbacks | unavailable
    lines = [owner(team)]
    if profile != DEFAULT_EXECUTION_PROFILE:
        lines.append(f"# Execution profile: {profile}")
    else:
        if model in fallbacks:
            lines.append(f"# Model fallback: {model}")
        if model in unavailable:
            lines.append(f"# Model unavailable: {model}")
    if stamp is not None:
        lines.append(stamp)
    lines.extend((
        f"name = {json.dumps(name)}",
        f"description = {json.dumps(description)}",
    ))
    for key in ROLE_SETTINGS:
        value = fields.get(key)
        if value is None:
            continue
        if SETTING_RE.fullmatch(value) is None:
            raise ValueError(f"agent {name!r} has an invalid {key} {value!r}")
        if key != "model" or (profile == DEFAULT_EXECUTION_PROFILE and not fallback):
            lines.append(f"{key} = {json.dumps(value)}")
    tools = {item.strip() for item in fields.get("tools", "").split(",") if item.strip()}
    if tools and tools <= READ_ONLY_TOOLS:
        lines.append('sandbox_mode = "read-only"')
    lines.append(f"developer_instructions = {json.dumps(instructions)}")
    return "\n".join(lines) + "\n"


atomic_write = atomic_file.replace_text


def render_agents(
    plugin_root: Path, team: str, profile: str = DEFAULT_EXECUTION_PROFILE,
    fallbacks: frozenset = frozenset(), settings: dict[str, dict] | None = None,
    *, unavailable: frozenset = frozenset(),
) -> dict[str, str]:
    """Render every role; ``settings`` maps a role to its resolved model and effort.

    The last header line of a role file with settings stamps the package
    version, the source agent and those settings, as a rendered Claude Code
    role does, so the session start check reports a file that a plugin update
    or a config change, such as a pull, left behind.
    """
    rendered: dict[str, str] = {}
    version = role_settings.package_version(plugin_root) if settings else None
    for source in sorted((plugin_root / "agents").glob("*.md")):
        fields, body = parse_agent(source)
        name = fields.get("name", "")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise ValueError(f"{source}: invalid Codex agent name {name!r}")
        if name != source.stem:
            raise ValueError(
                f"{source}: agent name {name!r} must equal file stem {source.stem!r}"
            )
        setting = (settings or {}).get(name)
        if setting is not None:
            fields = {key: value for key, value in fields.items() if key not in ROLE_SETTINGS}
            if setting["model"] != role_settings.SESSION:
                fields["model"] = setting["model"]
            if setting["effort"] is not None:
                fields["model_reasoning_effort"] = setting["effort"]
        rendered[f"{name}.toml"] = agent_toml(
            fields, body, team, profile, fallbacks, unavailable,
            role_settings.stamp(team, version, source, setting) if setting is not None else None)
    return rendered


def header(lines: list[str]) -> list[str]:
    """The comment lines between a role file's owner header and its first key."""
    comments = []
    for line in lines[1:]:
        if not line.startswith("#"):
            break
        comments.append(line)
    return comments


def stale_agents(project_root: Path, plugin_root: Path) -> tuple[list[str], int]:
    """Return the managed role files whose stamp does not match the installed
    package and the project's settings, and how many managed role files the
    project holds.

    A file rendered by another package version, from another source agent,
    with another model or effort than `workspace/config.json` now resolves or
    before stamps existed still runs what it was rendered with until setup or
    a refresh renders it again; so does one whose role the package no longer
    ships. While the config cannot be resolved, no role file is current.
    """
    team = plugin_name(plugin_root)
    agents_dir = project_root / AGENTS_DIR
    if agents_dir.is_symlink() or not agents_dir.is_dir():
        return [], 0
    version = role_settings.package_version(plugin_root)
    try:
        rows = project_settings(plugin_root, project_root,
                                project_instructions.CANONICAL_WORKSPACE)[2]
    except (OSError, ValueError):
        rows = {}
    stale: list[str] = []
    held = 0
    for path in sorted(agents_dir.glob("*.toml")):
        if path.is_symlink() or not path.is_file():
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        if not lines or lines[0] != owner(team):
            continue
        held += 1
        source = plugin_root / "agents" / f"{path.stem}.md"
        setting = rows.get(path.stem)
        if not source.is_file() or setting is None \
                or role_settings.stamp(team, version, source, setting) not in header(lines)[-1:]:
            stale.append(path.relative_to(project_root).as_posix())
    return stale, held


def project_settings(
    plugin_root: Path, project_root: Path, workspace: str,
) -> tuple[dict, dict, dict[str, dict]]:
    """Return the package tier map, the project config and each role's resolved
    model and effort, refusing a config the package does not take."""
    tier_map = role_settings.load_tier_map(plugin_root / "templates" / "tier-map.json")
    if tier_map is None or HOST not in tier_map["hosts"]:
        raise ValueError("the installed package ships no tier map for this host;"
                         " reinstall the package")
    try:
        config = project_config.load(project_root / workspace / "config.json")
    except (OSError, ValueError) as exc:
        raise ValueError(f"{workspace}/config.json is unreadable: {exc}") from exc
    errors = role_settings.config_errors(config, tier_map)
    if errors:
        raise ValueError("; ".join(errors))
    return tier_map, config, role_settings.resolve(tier_map, config, HOST)


def check_tier_map(plugin_root: Path, tier_map: dict) -> None:
    """Refuse a package whose role files disagree with its tier map."""
    roles = role_settings.package_tiers(tier_map)
    for source in sorted((plugin_root / "agents").glob("*.md")):
        fields = parse_agent(source)[0]
        spec = tier_map["hosts"][HOST]["tiers"].get(roles.get(source.stem, ""), {})
        if source.stem not in roles or fields.get("model") != spec.get("model") \
                or fields.get("model_reasoning_effort") != spec.get("effort"):
            raise ValueError(
                f"{source}: its model and effort differ from the package tier map;"
                " reinstall the package"
            )


def rendered_setting(setting: dict, profile: str, fallbacks) -> dict:
    """A resolved setting as rendered: `session` with its source where the role
    follows the parent session's model under `inherit` or a model fallback."""
    if profile != DEFAULT_EXECUTION_PROFILE and setting["model"] != role_settings.SESSION:
        return {**setting, "model": role_settings.SESSION, "model_source": "profile"}
    if setting["model"] in fallbacks:
        return {**setting, "model": role_settings.SESSION, "model_source": "fallback"}
    return setting


def tier_report(
    tier_map: dict | None, config: dict, profile: str | None, fallbacks,
) -> dict[str, dict]:
    """Each tier's rendered model and effort, each with its source."""
    if tier_map is None or profile is None:
        return {}
    return {tier: rendered_setting(setting, profile, fallbacks)
            for tier, setting in role_settings.tier_settings(tier_map, config, HOST).items()}


def restart_notice(project_root: Path, written: list[Path]) -> str:
    if not written:
        return ""
    agents_dir = project_root / AGENTS_DIR
    if all(path.parent == agents_dir for path in written):
        return ROLES_NOTICE
    return INSTRUCTIONS_NOTICE


def recorded_fallbacks(agents_dir: Path, team: str) -> tuple[set[str], set[str]]:
    """Return the models this team's managed agents record: by --inherit-model,
    and as unavailable by the last model check."""
    runtime: set[str] = set()
    unavailable: set[str] = set()
    if not agents_dir.is_dir():
        return runtime, unavailable
    current_owner = owner(team)
    for target in sorted(agents_dir.glob("*.toml")):
        if target.is_symlink():
            continue
        try:
            lines = target.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue  # preview reports unreadable or colliding targets
        if not lines or lines[0] != current_owner:
            continue
        for line in header(lines):
            for pattern, found in ((FALLBACK_RE, runtime), (UNAVAILABLE_RE, unavailable)):
                match = pattern.fullmatch(line)
                if match:
                    found.add(match.group(1))
    return runtime, unavailable


def recorded_profile(agents_dir: Path, team: str) -> str | None:
    """Return the execution profile this team's managed agents were rendered with."""
    if not agents_dir.is_dir():
        return None
    current_owner = owner(team)
    recorded: set[str] = set()
    for target in sorted(agents_dir.glob("*.toml")):
        if target.is_symlink():
            continue
        try:
            lines = target.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue  # preview reports unreadable or colliding targets
        if not lines or lines[0] != current_owner:
            continue
        match = PROFILE_RE.fullmatch(lines[1]) if len(lines) > 1 else None
        recorded.add(match.group(1) if match else DEFAULT_EXECUTION_PROFILE)
    if len(recorded) > 1:
        raise ValueError(
            "managed Codex agents record different execution profiles "
            f"({', '.join(sorted(recorded))}); pass --execution-profile to converge"
        )
    profile = recorded.pop() if recorded else None
    if profile is not None and profile not in EXECUTION_PROFILES:
        raise ValueError(
            f"managed Codex agents record unsupported execution profile {profile!r};"
            " pass --execution-profile to converge"
        )
    return profile


def configured_team(project_root: Path, workspace: str) -> str:
    config = project_root / workspace / "config.json"
    try:
        data = json.loads(config.read_text(encoding="utf-8"))
        return marketplace_paths.team_from_config(data)
    except FileNotFoundError:
        return ""
    except Exception as exc:
        raise ValueError(f"{workspace}/config.json is unreadable: {exc}") from exc


def preview(
    project_root: Path,
    plugin_root: Path,
    workspace: str,
    *,
    choices: dict[str, str] | None = None,
    seed_user_files: bool = False,
    scope: str = "all",
    execution_profile: str | None = None,
    inherit_models: tuple = (),
    restore_models: tuple = (),
    model_listing: Optional[Callable[[], dict]] = None,
) -> dict:
    if scope not in {"all", "tracked", "local"}:
        raise ValueError(f"unsupported project generation scope: {scope}")
    if execution_profile is not None:
        if execution_profile not in EXECUTION_PROFILES:
            raise ValueError(f"unsupported execution profile {execution_profile!r}")
        if scope == "tracked":
            raise ValueError(
                "--execution-profile applies only to the local agent projection"
            )
    if inherit_models and scope == "tracked":
        raise ValueError("--inherit-model applies only to the local agent projection")
    if restore_models and scope == "tracked":
        raise ValueError("--restore-model applies only to the local agent projection")
    both = sorted(set(inherit_models) & set(restore_models))
    if both:
        raise ValueError(f"--inherit-model and --restore-model both name {both[0]!r}")
    project_instructions.validate_workspace(workspace)
    team = plugin_name(plugin_root)
    configured = configured_team(project_root, workspace)
    if configured and configured != team:
        raise ValueError(
            f"project is managed by team {configured!r}; only one delivery team may own it"
        )
    agents_dir = project_root / AGENTS_DIR
    profile = None
    # Each model a role is pinned to, the project's included, with its tiers and roles.
    pins: dict[str, dict] = {}
    # Each model of a run-time record with the reason that decides its warning.
    fallbacks: dict[str, str] = {}
    # The models a check of this Codex's own list judged unavailable.
    unavailable: set[str] = set()
    conflicts: list = []
    check: dict = {"status": "not_run"}
    tier_map = None
    config: dict = {}
    settings: dict[str, dict] = {}
    if scope in {"all", "local"}:
        profile = execution_profile or recorded_profile(agents_dir, team) \
            or DEFAULT_EXECUTION_PROFILE
        tier_map, config, settings = project_settings(plugin_root, project_root, workspace)
        pins = host_listing.pinned(settings, role_settings.SESSION,
                                   role_settings.ROLE_TIER_CHOICES)
        unknown = sorted((set(inherit_models) | set(restore_models)) - set(pins))
        if unknown:
            raise ValueError(
                f"no role is pinned to {unknown[0]!r}; the pinned models are"
                f" {', '.join(sorted(pins))}"
            )
    if profile == DEFAULT_EXECUTION_PROFILE:
        recorded, judged = recorded_fallbacks(agents_dir, team)
        # An explicit --execution-profile auto restores every pin it can,
        # --restore-model the pins of the models it names.
        if execution_profile is None:
            fallbacks.update((model, "recorded")
                             for model in sorted(recorded & set(pins) - set(restore_models)))
        fallbacks.update((model, "requested") for model in inherit_models)
        if model_listing is not None:
            listing = model_listing()
            check = host_listing.model_check(listing, pins)
            unavailable = host_listing.unavailable(check)
            conflicts = host_listing.effort_conflicts(
                listing, role_settings.tier_settings(tier_map, config, HOST),
                tier_map["hosts"][HOST]["models"])
        else:
            unavailable = judged & set(pins)
    rendered = render_agents(
        plugin_root, team, profile, frozenset(fallbacks), settings,
        unavailable=frozenset(unavailable),
    ) if profile is not None else {}
    if tier_map is not None:
        check_tier_map(plugin_root, tier_map)
    current_owner = owner(team)
    collisions: list[Path] = []
    if scope in {"all", "local"} and agents_dir.is_dir():
        for target in sorted(agents_dir.glob("*.toml")):
            if target.is_symlink():
                raise ValueError(f"managed Codex agent target is a symbolic link: {target}")
            try:
                first = target.read_text(
                    encoding="utf-8", errors="replace"
                ).splitlines()[0]
            except (OSError, IndexError):
                first = ""
            match = OWNER_RE.fullmatch(first)
            if match and match.group(1) != team:
                raise ValueError(
                    f"project already has Codex agents managed by team {match.group(1)!r}"
                )
            if target.name in rendered and first != current_owner:
                collisions.append(target)
    if collisions:
        joined = ", ".join(str(path) for path in collisions)
        raise ValueError(f"unmanaged Codex agent collision: {joined}")

    instructions = project_instructions.plan_portable_project_files(
        project_root, plugin_root, workspace,
        choices=choices, seed_user_files=seed_user_files,
    ) if scope in {"all", "tracked"} else {
        "changes": {}, "choice_requests": [],
        "current_surfaces": {}, "target_surfaces": {},
    }
    changes: dict[Path, str | None] = dict(instructions["changes"])
    current_agent_surfaces: dict[str, str] = {}
    if scope in {"all", "local"} and agents_dir.is_dir():
        for target in sorted(agents_dir.glob("*.toml")):
            content = target.read_text(encoding="utf-8", errors="replace")
            if content.startswith(current_owner):
                current_agent_surfaces[
                    "local:" + target.relative_to(project_root).as_posix()
                ] = hashlib.sha256(content.encode()).hexdigest()
            if scope in {"all", "local"} and target.name not in rendered \
                    and content.startswith(current_owner):
                changes[target] = None
    target_agent_surfaces = {
        "local:" + (agents_dir / filename).relative_to(project_root).as_posix():
            hashlib.sha256(content.encode()).hexdigest()
        for filename, content in rendered.items()
    }
    if scope in {"all", "local"}:
        for filename, content in rendered.items():
            target = agents_dir / filename
            if not target.is_file() or target.read_text(encoding="utf-8") != content:
                changes[target] = content
        instructions["current_surfaces"].update(current_agent_surfaces)
        instructions["target_surfaces"].update(target_agent_surfaces)
    instructions["changes"] = changes
    instructions["execution_profile"] = profile
    fallen = set(fallbacks) | unavailable
    instructions["model_check"] = check
    instructions["model_fallbacks"] = {model: pins[model]["roles"] for model in sorted(fallen)}
    instructions["model_notes"] = model_notes(pins, fallbacks, unavailable, check, conflicts)
    instructions["tier_map"] = tier_report(tier_map, config, profile, fallen)
    instructions["roles"] = {
        role: rendered_setting(setting, profile, fallen)
        for role, setting in settings.items()} if profile is not None else {}
    return instructions


def model_notes(
    pins: dict[str, dict], fallbacks: dict[str, str], unavailable: set[str], check: dict,
    conflicts: list,
) -> list[str]:
    """The warnings and notes apply prints for each run-time record and the model check."""
    notes = [
        f"codex-project: warning: {model} {FALLBACK_REASONS[reason]}, so its roles"
        f" {', '.join(pins[model]['roles'])} run on {SESSION_PHRASE} at their own reasoning"
        f" effort. Apply with --restore-model {model} or --execution-profile auto to restore"
        " the pin once the model runs."
        for model, reason in sorted(fallbacks.items())
    ]
    # A model under a run-time record neither keeps its pin nor needs the check's word.
    shown = {**check, "verdicts": {model: value for model, value in
                                   check.get("verdicts", {}).items() if model not in fallbacks}}
    notes.extend(host_listing.check_notes("codex-project", shown, pins,
                                          unavailable - set(fallbacks), conflicts,
                                          SESSION_PHRASE))
    return notes


def materialize(
    project_root: Path,
    plugin_root: Path,
    workspace: str,
    writer: Callable[[Path, str], None] = atomic_write,
    *,
    choices: dict[str, str] | None = None,
    seed_user_files: bool = True,
    scope: str = "all",
    execution_profile: str | None = None,
    inherit_models: tuple = (),
    restore_models: tuple = (),
    model_listing: Optional[Callable[[], dict]] = None,
) -> list[Path]:
    result = preview(
        project_root, plugin_root, workspace,
        choices=choices, seed_user_files=seed_user_files, scope=scope,
        execution_profile=execution_profile, inherit_models=inherit_models,
        restore_models=restore_models, model_listing=model_listing,
    )
    if result["choice_requests"]:
        raise ValueError(
            "project instruction reconciliation choice required: "
            + json.dumps(result["choice_requests"], sort_keys=True)
        )
    changes: dict[Path, str | None] = result["changes"]

    snapshots = {
        path: path.read_bytes() if path.is_file() else None for path in changes
    }
    created_dirs: set[Path] = set()
    for path in changes:
        parent = path.parent
        while parent != project_root and not parent.exists():
            created_dirs.add(parent)
            parent = parent.parent
    written: list[Path] = []
    try:
        for path, content in changes.items():
            if content is None:
                path.unlink()
            else:
                writer(path, content)
            written.append(path)
    except Exception:
        for path, previous in snapshots.items():
            if previous is None:
                path.unlink(missing_ok=True)
            else:
                atomic_write(path, previous.decode("utf-8"))
        for directory in sorted(created_dirs, key=lambda value: len(value.parts), reverse=True):
            try:
                directory.rmdir()
            except OSError:
                pass
        raise
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action", nargs="?", choices=("inspect", "check", "apply"),
        default="apply",
    )
    parser.add_argument("--project-root", type=Path, required=True)
    parser.set_defaults(workspace=project_instructions.CANONICAL_WORKSPACE)
    parser.add_argument("--choice", action="append", default=[])
    parser.add_argument("--seed-user-files", action="store_true")
    parser.add_argument("--scope", choices=("all", "tracked", "local"), default="all")
    parser.add_argument(
        "--execution-profile", choices=EXECUTION_PROFILES, default=None,
        help="role model and reasoning effort; defaults to the recorded profile, then auto",
    )
    parser.add_argument(
        "--inherit-model", action="append", default=[], metavar="MODEL",
        help="render the roles pinned to MODEL without it, so they run on the parent"
             " session's model at their own reasoning effort; repeatable",
    )
    parser.add_argument(
        "--restore-model", action="append", default=[], metavar="MODEL",
        help="render the roles pinned to MODEL with it again and drop its recorded"
             " fallback; repeatable",
    )
    args = parser.parse_args()
    project_root = args.project_root.resolve()
    if not (project_root / ".git").exists():
        raise SystemExit("codex-project: --project-root must be a git repository root")
    plugin_root = Path(__file__).resolve().parents[1]
    # Only apply reads this Codex's own model list, once; inspect and check
    # keep what the managed files record.
    listing = None
    if args.action == "apply":
        import host_models
        listing = functools.lru_cache(maxsize=None)(host_models.list_models)
    inherit_models = tuple(dict.fromkeys(args.inherit_model))
    restore_models = tuple(dict.fromkeys(args.restore_model))
    try:
        choices = project_instructions.parse_choices(args.choice)
        result = preview(
            project_root, plugin_root, args.workspace,
            choices=choices, seed_user_files=args.seed_user_files,
            scope=args.scope, execution_profile=args.execution_profile,
            inherit_models=inherit_models, restore_models=restore_models,
            model_listing=listing,
        )
        written = []
        if args.action == "apply" and not result["choice_requests"]:
            written = materialize(
                project_root, plugin_root, args.workspace,
                choices=choices, seed_user_files=args.seed_user_files,
                scope=args.scope, execution_profile=args.execution_profile,
                inherit_models=inherit_models, restore_models=restore_models,
                model_listing=listing,
            )
    except ValueError as exc:
        raise SystemExit(f"codex-project: {exc}") from exc
    if args.action == "apply":
        for note in result["model_notes"]:
            print(note, file=sys.stderr)
    print(json.dumps({
        "status": "choice_required" if result["choice_requests"] else "ok",
        "changes": sorted(
            path.relative_to(project_root).as_posix()
            for path in result["changes"]
        ),
        "choice_requests": result["choice_requests"],
        "execution_profile": result["execution_profile"],
        "model_check": result["model_check"],
        "model_fallbacks": result["model_fallbacks"],
        "current_surfaces": result["current_surfaces"],
        "target_surfaces": result["target_surfaces"],
        "tier_map": result["tier_map"],
        "roles": result["roles"],
        "written": [str(path) for path in written],
        "restart_required": bool(written),
        "notice": restart_notice(project_root, written),
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
