#!/usr/bin/env python3
"""Build deterministic host distributions from canonical plugin content.

Canonical product behavior lives under ``plugins/`` and is host-neutral.
Host manifests, contracts, overlays, and append-only fragments live under
``platforms/``.  This builder is the only writer of ``dist/``.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import re
import shutil
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from types import ModuleType


ADAPTER_API_VERSION = 1
CANONICAL_REASONING_LEVELS = {"high", "medium", "low", "inherit"}
DELIVERY_PROTOCOL_CAPABILITY = {
    "read_min": 1,
    "read_max": 1,
    "write": 1,
    "transition_writes": [1],
}
PRODUCT_CONTRACT_RELPATH = "product.json"
WRAPPER_MARKER = "<!-- generated by tools/build_distributions.py; do not edit -->"
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
DISPLAY_TOKENS = {
    "api": "API",
    "cli": "CLI",
    "devops": "DevOps",
    "fastapi": "FastAPI",
    "nosql": "NoSQL",
    "qa": "QA",
    "sql": "SQL",
    "ui": "UI",
    "ux": "UX",
}
CANONICAL_HOST_TOKENS = (
    "Claude",
    "Codex",
    "claude",
    "codex",
    "AskUserQuestion",
    "request_user_input",
    "CLAUDE.md",
    "AGENTS.md",
    "CLAUDE_PLUGIN_ROOT",
    "PLUGIN_ROOT",
    ".claude",
    ".codex",
)
SUPPORTED_HOSTS = {"claude", "codex"}
PLATFORM_ROOTS = SUPPORTED_HOSTS | {"shared"}
GENERATED_TEXT_SUFFIXES = {
    ".css", ".csv", ".html", ".js", ".json", ".md", ".ps1", ".py",
    ".sh", ".svg", ".toml", ".txt", ".xml", ".yaml", ".yml",
}
GENERATED_TEXT_NAMES = {"LICENSE", "gitignore"}
CANONICAL_COMPONENTS = {
    "agents",
    "constitution.md",
    "flows",
    "hooks",
    "scripts",
    "skill-content",
    "templates",
}
REPOSITORY_DIRECTORIES = {
    ".agentrof",
    ".changes",
    ".agents",
    ".claude",
    ".claude-plugin",
    ".git",
    ".github",
    ".release",
    "assets",
    "dist",
    "docs",
    "memory",
    "platforms",
    "plugins",
    "tools",
}
SOURCE_IGNORES = {"agents"}
PYTHON_CACHE_SUFFIXES = {".pyc", ".pyo"}


def load_product_contract(root: Path) -> dict:
    path = root / PRODUCT_CONTRACT_RELPATH
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path}: missing or invalid product contract") from exc
    try:
        vendor = data["vendor"]
        product = data["product"]
        hosts = data["hosts"]
        values = (
            data["schema_version"], vendor["id"], vendor["display_name"],
            vendor["home_env"], vendor["default_home_dir"], product["id"],
            product["display_name"], product["home_env"],
            product["home_subdir"],
        )
    except (KeyError, TypeError) as exc:
        raise ValueError(f"{path}: incomplete product contract") from exc
    expected = (
        2, "agentrof", "Agentrof", "AGENT_MARKETPLACE_HOME", ".agent-marketplace",
        "agent-marketplace", "Agent Marketplace", "AGENT_MARKETPLACE_HOME",
        "",
    )
    if values != expected:
        raise ValueError(f"{path}: product contract differs from the supported namespace")
    if not isinstance(hosts, dict) or set(hosts) != SUPPORTED_HOSTS or not all(
            isinstance(host, str) and isinstance(value, dict)
            for host, value in hosts.items()):
        raise ValueError(
            f"{path}: hosts must be exactly {sorted(SUPPORTED_HOSTS)}"
        )
    environment = data.get("project_environment", {})
    roots = environment.get("projection_roots") if isinstance(environment, dict) else None
    if environment.get("runtime_root") != ".agentrof" or not isinstance(roots, dict):
        raise ValueError(f"{path}: project environment roots are invalid")
    if set(roots) != set(hosts) or not all(
            isinstance(value, str) and value.startswith(".")
            for value in roots.values()):
        raise ValueError(f"{path}: project environment roots are invalid")
    return data


def packaging_names(root: Path) -> tuple[str, str]:
    product_id = load_product_contract(root)["product"]["id"]
    return (
        f".{product_id}-generated-distribution",
        f".{product_id}-package.json",
    )


def marketplace_paths_source(product_contract: dict) -> str:
    del product_contract
    return f'''#!/usr/bin/env python3
"""Resolve the Software Engineering Team owner from project config."""

from __future__ import annotations

from collections.abc import Mapping


def team_from_config(config: Mapping[str, object]) -> str:
    """Resolve the sole team from the current project config contract."""
    return str(config.get("team_id", "")).strip()
'''


def marketplace_paths_targets(root: Path) -> list[Path]:
    return [
        plugin / "scripts" / "marketplace_paths.py"
        for plugin in sorted((root / "plugins").iterdir())
        if plugin.is_dir()
    ]


def sync_marketplace_paths_sources(root: Path) -> None:
    expected = marketplace_paths_source(load_product_contract(root))
    for target in marketplace_paths_targets(root):
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(expected.encode("utf-8"))


def marketplace_paths_source_drift(root: Path) -> list[str]:
    expected = marketplace_paths_source(load_product_contract(root))
    problems = []
    for target in marketplace_paths_targets(root):
        try:
            actual = target.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            problems.append(
                f"generated runtime source is out of sync: {target}"
            )
    return problems


_DEFAULT_ROOT = Path(__file__).resolve().parent.parent
MARKER, PROVENANCE = packaging_names(_DEFAULT_ROOT)


@dataclass(frozen=True)
class HostAdapter:
    """A loaded platform adapter with declarative metadata."""

    host_id: str
    metadata: dict
    module: ModuleType


def _load_adapter_module(path: Path, host_id: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        f"agent_marketplace_adapter_{host_id}", path
    )
    if spec is None or spec.loader is None:
        raise ValueError(f"{path}: adapter module cannot be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_adapters(root: Path) -> dict[str, HostAdapter]:
    """Load every declared platform adapter in stable host-id order."""
    contract = load_product_contract(root)
    platforms_root = root / "platforms"
    if not platforms_root.is_dir():
        raise ValueError(f"{platforms_root}: platform source directory is missing")
    platform_entries = [
        path for path in platforms_root.iterdir()
        if path.name != "__pycache__" and path.suffix not in PYTHON_CACHE_SUFFIXES
    ]
    platform_names = {path.name for path in platform_entries}
    invalid_platform_entries = [
        path for path in platform_entries
        if path.name not in PLATFORM_ROOTS or not path.is_dir() or path.is_symlink()
    ]
    if platform_names != PLATFORM_ROOTS or invalid_platform_entries:
        raise ValueError(
            "platform roots must exactly match the supported host sources: "
            f"expected={sorted(PLATFORM_ROOTS)}, actual={sorted(platform_names)}"
        )
    result: dict[str, HostAdapter] = {}
    for path in sorted(platforms_root.glob("*/adapter.json")):
        try:
            metadata = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"{path}: invalid adapter metadata") from exc
        if not isinstance(metadata, dict):
            raise ValueError(f"{path}: adapter metadata must be an object")
        host_id = metadata.get("host_id")
        projection_root = metadata.get("projection_root")
        artifact_kind = metadata.get("artifact_kind")
        catalog = metadata.get("marketplace_catalog")
        surfaces = metadata.get("supported_surfaces")
        if not isinstance(host_id, str) or not host_id:
            raise ValueError(f"{path}: adapter host_id is required")
        if host_id in result:
            raise ValueError(f"{path}: duplicate adapter host_id {host_id!r}")
        if metadata.get("schema_version") != 1 \
                or metadata.get("adapter_api_version") != ADAPTER_API_VERSION:
            raise ValueError(f"{path}: unsupported adapter schema or API version")
        if host_id not in SUPPORTED_HOSTS:
            raise ValueError(f"{path}: unsupported host {host_id!r}")
        if artifact_kind != "native_marketplace":
            raise ValueError(f"{path}: artifact_kind must be native_marketplace")
        if not isinstance(catalog, bool) or not isinstance(surfaces, list) \
                or not surfaces or not all(isinstance(item, str) and item for item in surfaces) \
                or len(surfaces) != len(set(surfaces)):
            raise ValueError(f"{path}: marketplace_catalog and supported_surfaces are invalid")
        if not isinstance(projection_root, str) or not projection_root.startswith("."):
            raise ValueError(f"{path}: projection_root must be a local dot directory")
        if contract["hosts"].get(host_id) is None:
            raise ValueError(f"{path}: host is absent from product.json")
        if contract["project_environment"]["projection_roots"].get(host_id) != projection_root:
            raise ValueError(f"{path}: projection_root differs from product.json")
        module_path = path.with_name("adapter.py")
        if not module_path.is_file():
            raise ValueError(f"{path}: adapter.py is missing")
        module = _load_adapter_module(module_path, host_id)
        required = ("skill_artifacts", "agent_artifacts", "native_manifest_directory",
                    "instruction_surface", "runtime_contracts")
        missing = [name for name in required if not callable(getattr(module, name, None))]
        if missing:
            raise ValueError(f"{module_path}: missing adapter functions: {', '.join(missing)}")
        result[host_id] = HostAdapter(host_id, metadata, module)
    if set(result) != set(contract["hosts"]):
        raise ValueError(
            "product host registry differs from platform adapters: "
            f"product={sorted(contract['hosts'])}, adapters={sorted(result)}"
        )
    roots = [adapter.metadata["projection_root"] for adapter in result.values()]
    if len(roots) != len(set(roots)):
        raise ValueError("platform adapters declare duplicate projection roots")
    return dict(sorted(result.items()))


HOSTS = tuple(load_adapters(_DEFAULT_ROOT))


def is_python_cache(path: Path) -> bool:
    return "__pycache__" in path.parts or path.suffix in PYTHON_CACHE_SUFFIXES


def ignore_python_cache(_directory: str, names: list[str]) -> set[str]:
    return {
        name for name in names
        if name == "__pycache__" or Path(name).suffix in PYTHON_CACHE_SUFFIXES
    }


def title_of(name: str) -> str:
    return " ".join(
        DISPLAY_TOKENS.get(part, part.capitalize()) for part in name.split("-")
    )


def parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if match is None:
        raise ValueError(f"{path}: missing YAML frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip().strip("\"'")
    return fields, text[match.end():]


def skill_metadata(path: Path) -> tuple[str, str, str, str]:
    fields, _ = parse_frontmatter(path)
    name = fields.get("name", "")
    description = fields.get("description", "")
    exposure = fields.get("exposure", "")
    project_scope = fields.get("project_scope", "project")
    if name != path.parent.name or not description:
        raise ValueError(f"{path}: name/description mismatch")
    if exposure not in {"entry", "internal"}:
        raise ValueError(f"{path}: exposure must be entry or internal")
    if project_scope not in {"project", "external"}:
        raise ValueError(f"{path}: project_scope must be project or external")
    if project_scope == "external" and exposure != "entry":
        raise ValueError(f"{path}: only entry skills may be external")
    unexpected = set(fields) - {
        "name", "description", "exposure", "project_scope"
    }
    if unexpected:
        raise ValueError(
            f"{path}: canonical frontmatter has host or unknown fields: "
            + ", ".join(sorted(unexpected))
        )
    return name, description, exposure, project_scope


def copy_canonical(source: Path, target: Path) -> None:
    def ignore(directory: str, names: list[str]) -> set[str]:
        ignored = ignore_python_cache(directory, names)
        if Path(directory) == source:
            ignored.update(name for name in names if name in SOURCE_IGNORES)
        return ignored

    shutil.copytree(source, target, ignore=ignore)


def copy_overlay(root: Path, target: Path) -> None:
    if root.is_dir():
        shutil.copytree(
            root, target, dirs_exist_ok=True, ignore=ignore_python_cache
        )


def apply_appends(root: Path, target: Path) -> None:
    if not root.is_dir():
        return
    for fragment in sorted(
        path for path in root.rglob("*")
        if path.is_file() and not is_python_cache(path)
    ):
        relative = fragment.relative_to(root)
        destination = target / relative
        if not destination.is_file():
            raise ValueError(f"{fragment}: append target does not exist: {relative}")
        base = destination.read_text(encoding="utf-8").rstrip("\n")
        extra = fragment.read_text(encoding="utf-8").strip("\n")
        destination.write_bytes(f"{base}\n\n{extra}\n".encode("utf-8"))


def write_artifacts(target: Path, artifacts: list[tuple[str, str]]) -> None:
    """Write declared adapter artifacts without allowing path escape."""
    for relative, content in artifacts:
        path = target / relative
        try:
            path.resolve().relative_to(target.resolve())
        except ValueError as exc:
            raise ValueError(f"adapter output escapes package: {relative}") from exc
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))


def skill_records(source: Path) -> list[tuple[str, str, str, str]]:
    return [skill_metadata(path) for path in sorted(
        (source / "skill-content").glob("*/SKILL.md")
    )]


def generate_skills(source: Path, target: Path, adapter: HostAdapter) -> list[tuple[str, str, str, str]]:
    records = skill_records(source)
    context = {"wrapper_marker": WRAPPER_MARKER, "title_of": title_of}
    for record in records:
        write_artifacts(
            target,
            adapter.module.skill_artifacts(context, source.name, record),
        )
    return records


def generate_agents(source: Path, target: Path, adapter: HostAdapter) -> None:
    agents = source / "agents"
    if not agents.is_dir():
        return
    context = {"parse_frontmatter": parse_frontmatter}
    for path in sorted(agents.glob("*.md")):
        write_artifacts(target, adapter.module.agent_artifacts(context, path))


def compose_project_instructions(
    root: Path, source: Path, target: Path, adapters: dict[str, HostAdapter],
) -> None:
    """Compose every portable project instruction template for a team."""
    common = (
        source / "templates"
        / "project-instructions" / "common.md"
    )
    team = source / "templates" / "project-instructions" / "team.md"
    host_deltas = {
        host_id: (
            root / "platforms" / host_id / "_team" / "overlay"
            / "templates" / "project-instructions" / "host.md"
        )
        for host_id in adapters
    }
    missing = [
        path for path in (common, team, *host_deltas.values())
        if not path.is_file()
    ]
    if missing:
        raise ValueError(
            "missing project instruction fragment: "
            + ", ".join(str(path) for path in missing)
        )
    try:
        caps = json.loads((root / "tools" / "data" / "limits.json").read_text(
            encoding="utf-8"
        ))["authoring_caps"]
        max_bytes = int(caps["project_instruction_max_bytes"])
        max_lines = int(caps["project_instruction_max_lines"])
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        raise ValueError("project instruction limits are missing or invalid") from exc
    templates = target / "templates"
    templates.mkdir(exist_ok=True)
    surfaces = []
    for template_host, host_delta in host_deltas.items():
        surface = adapters[template_host].module.instruction_surface()
        filename = surface.get("filename")
        owner_host = surface.get("owner_host")
        companion = surface.get("user_companion")
        migrations = surface.get("migrates_from_owners", [])
        if not isinstance(filename, str) or not filename or not isinstance(owner_host, str) \
                or not isinstance(companion, str) or not companion \
                or not isinstance(migrations, list) or not all(isinstance(value, str) for value in migrations):
            raise ValueError(f"{template_host}: invalid instruction surface")
        owner = (
            f"<!-- generated by agent-marketplace {source.name} for "
            f"{owner_host}; do not edit by hand -->"
        )
        sections = [
            common.read_text(encoding="utf-8").strip(),
            team.read_text(encoding="utf-8").strip(),
            host_delta.read_text(encoding="utf-8").strip(),
        ]
        rendered = owner + "\n\n" + "\n\n".join(sections) + "\n"
        size = len(rendered.encode("utf-8"))
        lines = len(rendered.splitlines())
        if size > max_bytes or lines > max_lines:
            raise ValueError(
                f"{source.name}/{template_host} generated project instructions "
                f"exceed cap: {size} bytes, {lines} lines"
            )
        (templates / filename).write_bytes(rendered.encode("utf-8"))
        surfaces.append({
            "host_id": template_host,
            "filename": filename,
            "owner_host": owner_host,
            "user_companion": companion,
            "migrates_from_owners": migrations,
        })
    (templates / "project-instruction-surfaces.json").write_bytes(
        (json.dumps(
            {"schema_version": 1, "surfaces": surfaces},
            indent=2,
            sort_keys=True,
        ) + "\n").encode("utf-8")
    )

    memory_source = source / "templates" / "memory"
    if not memory_source.is_dir():
        raise ValueError(f"missing shared memory templates: {memory_source}")
    shutil.copytree(memory_source, templates / "memory", dirs_exist_ok=True)


def normalized_content(path: Path, data: bytes) -> bytes:
    """Normalize only explicitly text-shaped generated paths to LF bytes."""
    if path.name not in GENERATED_TEXT_NAMES \
            and path.suffix.lower() not in GENERATED_TEXT_SUFFIXES:
        return data
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return data
    return text.replace("\r\n", "\n").replace("\r", "\n").encode("utf-8")


def snapshot_files(root: Path, relative_root: str) -> list[Path]:
    """List one snapshot surface in platform-neutral POSIX path order."""
    base = root / relative_root
    return sorted(
        (
            candidate for candidate in base.rglob("*")
            if candidate.is_file() and not is_python_cache(candidate)
        ),
        key=lambda candidate: candidate.relative_to(root).as_posix(),
    )


def snapshot_content(path: Path) -> bytes:
    """Hash the same canonical bytes that the generated package will contain."""
    return normalized_content(path, path.read_bytes())


def is_executable(path: Path) -> bool:
    """Return the platform package's Git-style executable-bit class."""
    return bool(path.stat().st_mode & stat.S_IXUSR)


def update_snapshot_digest(
    digest, relative: str, content: bytes,
) -> None:
    """Add one prefix-free, typed file record."""
    relative_bytes = relative.encode("utf-8")
    digest.update(b"file\0")
    digest.update(len(relative_bytes).to_bytes(8, "big"))
    digest.update(relative_bytes)
    digest.update(len(content).to_bytes(8, "big"))
    digest.update(content)


def load_package_executables(root: Path, component: str) -> set[str]:
    """Load the platform-neutral executable-mode contract for one package."""
    contract = root / "package-modes.json"
    try:
        data = json.loads(contract.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{contract}: missing or invalid package mode contract") from exc
    packages = data.get("packages") if isinstance(data, dict) else None
    expected_packages = {
        path.name for path in (root / "plugins").iterdir() if path.is_dir()
    }
    if not isinstance(data, dict) \
            or set(data) != {"schema_version", "packages"} \
            or data.get("schema_version") != 1 \
            or not isinstance(packages, dict) \
            or set(packages) != expected_packages:
        raise ValueError(f"{contract}: invalid package mode contract")
    package = packages.get(component)
    values = package.get("executables") if isinstance(package, dict) else None
    if not isinstance(package, dict) \
            or set(package) != {"executables"} \
            or not isinstance(values, list) \
            or values != sorted(values) \
            or len(values) != len(set(values)):
        raise ValueError(f"{contract}: invalid package mode contract")
    for value in values:
        path = PurePosixPath(value) if isinstance(value, str) else PurePosixPath("..")
        if path.is_absolute() or not path.parts or ".." in path.parts \
                or str(path) != value:
            raise ValueError(f"{contract}: unsafe executable path {value!r}")
    return set(values)


def apply_package_modes(target: Path, executables: set[str]) -> None:
    """Materialize the declared Git executable class independent of checkout OS."""
    present: set[str] = set()
    for path in sorted(
        (candidate for candidate in target.rglob("*") if candidate.is_file()),
        key=lambda candidate: candidate.relative_to(target).as_posix(),
    ):
        relative = path.relative_to(target).as_posix()
        present.add(relative)
        mode = path.stat().st_mode
        if relative in executables:
            path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        else:
            path.chmod(mode & ~(stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH))
    missing = executables - present
    if missing:
        raise ValueError(
            "package mode contract names missing files: " + ", ".join(sorted(missing))
        )


def normalize_generated_text(root: Path) -> None:
    for path in sorted(
        candidate for candidate in root.rglob("*")
        if candidate.is_file() and not is_python_cache(candidate)
    ):
        data = path.read_bytes()
        normalized = normalized_content(path, data)
        if normalized != data:
            path.write_bytes(normalized)


def write_provenance(
    target: Path,
    component: str,
    adapter: HostAdapter,
    version: str,
    provenance_name: str,
    snapshot: dict[str, str],
    executables: set[str],
) -> None:
    files = {}
    for path in sorted(
        (candidate for candidate in target.rglob("*") if candidate.is_file()),
        key=lambda candidate: candidate.relative_to(target).as_posix(),
    ):
        if path.name == provenance_name or is_python_cache(path):
            continue
        relative = path.relative_to(target).as_posix()
        files[relative] = hashlib.sha256(
            path.read_bytes()
        ).hexdigest()
    payload = json.dumps({
        "schema_version": 3,
        "component": component,
        "host": adapter.host_id,
        "version": version,
        **snapshot,
        "files": files,
        "executables": sorted(executables),
        "runtime_contracts": adapter.module.runtime_contracts(),
        "delivery_protocol": DELIVERY_PROTOCOL_CAPABILITY,
    }, indent=2, sort_keys=True) + "\n"
    (target / provenance_name).write_bytes(payload.encode("utf-8"))


def marketplace_snapshot(root: Path) -> dict[str, str]:
    """Return one deterministic identity shared by all host builds."""
    digest = hashlib.sha256()
    digest.update(b"agent-marketplace-snapshot-v2\0")
    for relative_root in ("plugins", "platforms"):
        for path in snapshot_files(root, relative_root):
            relative = path.relative_to(root).as_posix()
            update_snapshot_digest(
                digest, relative, snapshot_content(path),
            )
    for relative in ("package-modes.json", "product.json", "versions.json"):
        path = root / relative
        update_snapshot_digest(
            digest, relative, snapshot_content(path),
        )
    versions = json.loads((root / "versions.json").read_text(encoding="utf-8"))
    build_id = "snapshot." + digest.hexdigest()
    return {
        "build_id": build_id,
        "marketplace_release": str(versions["marketplace"]),
        "source_channel": "snapshot",
        "source_ref": build_id,
        "source_commit": "",
    }


def load_plugin_versions(root: Path) -> dict[str, str]:
    path = root / "versions.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path}: missing or invalid canonical version registry") from exc
    plugins = data.get("plugins") if isinstance(data, dict) else None
    if not isinstance(plugins, dict):
        raise ValueError(f"{path}: plugins must be an object")
    expected = {
        source.name for source in (root / "plugins").iterdir() if source.is_dir()
    }
    if set(plugins) != expected:
        raise ValueError(
            f"{path}: plugin registry differs from plugins/: "
            f"registered={sorted(plugins)}, actual={sorted(expected)}"
        )
    return plugins


def build_plugin(
    root: Path,
    source: Path,
    adapter: HostAdapter,
    target: Path,
    version: str,
    marker_name: str,
    provenance_name: str,
    snapshot: dict[str, str],
    adapters: dict[str, HostAdapter],
) -> None:
    host = adapter.host_id
    platform = root / "platforms" / host / source.name
    shared = root / "platforms" / "shared" / source.name
    contract = platform / "host-contract.md"
    if not contract.is_file():
        raise ValueError(f"{platform}: missing host-contract.md")
    copy_canonical(source, target)
    shutil.copy2(root / PRODUCT_CONTRACT_RELPATH, target / PRODUCT_CONTRACT_RELPATH)
    gitignore = target / "templates" / "gitignore"
    if gitignore.is_file():
        environment = load_product_contract(root)["project_environment"]
        roots = [environment["runtime_root"], *environment["projection_roots"].values()]
        text = gitignore.read_text(encoding="utf-8")
        text = text.replace(
            "{{project_local_ignores}}",
            "\n".join(f"/{value}/" for value in roots),
        )
        gitignore.write_bytes(text.encode("utf-8"))
    copy_overlay(root / "platforms" / "shared" / "_team" / "overlay", target)
    copy_overlay(root / "platforms" / host / "_team" / "overlay", target)
    copy_overlay(shared / "overlay", target)
    copy_overlay(platform / "overlay", target)
    apply_appends(shared / "append", target)
    apply_appends(platform / "append", target)
    shutil.copy2(contract, target / "host-contract.md")
    manifest_directory = adapter.module.native_manifest_directory(host)
    if manifest_directory is not None:
        manifest = platform / "manifest.json"
        if not manifest.is_file():
            raise ValueError(f"{platform}: native marketplace adapter requires manifest.json")
        try:
            manifest_data = json.loads(manifest.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"{manifest}: invalid JSON") from exc
        manifest_data["version"] = version
        manifest_dir = target / manifest_directory
        manifest_dir.mkdir()
        (manifest_dir / "plugin.json").write_bytes(
            (json.dumps(manifest_data, indent=2) + "\n").encode("utf-8")
        )
    generate_skills(source, target, adapter)
    generate_agents(source, target, adapter)
    compose_project_instructions(root, source, target, adapters)
    (target / marker_name).write_bytes(
        b"Generated by tools/build_distributions.py; do not edit.\n"
    )
    normalize_generated_text(target)
    executables = load_package_executables(root, source.name)
    apply_package_modes(target, executables)
    write_provenance(
        target, source.name, adapter, version, provenance_name, snapshot,
        executables,
    )


def validate_canonical(root: Path) -> None:
    problems: list[str] = []
    for child in sorted(path for path in root.iterdir() if path.is_dir()):
        if child.name not in REPOSITORY_DIRECTORIES:
            problems.append(
                f"{child}: unsupported repository top-level directory; "
                "use the declared repository layout"
            )
    for surface_name in ("plugins", "platforms"):
        surface = root / surface_name
        try:
            surface_mode = surface.lstat().st_mode
        except OSError:
            problems.append(f"{surface}: canonical surface is missing")
            continue
        if not stat.S_ISDIR(surface_mode):
            problems.append(
                f"{surface}: canonical surface must be a real directory"
            )
            continue
        for candidate in sorted(surface.rglob("*")):
            if candidate.is_symlink():
                problems.append(
                    f"{candidate}: symbolic links are forbidden in packaged sources"
                )
    for source in sorted(path for path in (root / "plugins").iterdir() if path.is_dir()):
        for child in sorted(source.iterdir()):
            if is_python_cache(child):
                continue
            if child.name not in CANONICAL_COMPONENTS:
                problems.append(
                    f"{child}: unsupported canonical top-level entry; "
                    "move host adapters under platforms/ or use a canonical component"
                )
        for skill in sorted((source / "skill-content").glob("*/SKILL.md")):
            try:
                skill_metadata(skill)
            except ValueError as exc:
                problems.append(str(exc))
        for agent in sorted((source / "agents").glob("*.md")):
            fields, _ = parse_frontmatter(agent)
            if fields.get("reasoning") not in CANONICAL_REASONING_LEVELS:
                problems.append(f"{agent}: reasoning must be high/medium/low/inherit")
            if "model" in fields:
                problems.append(f"{agent}: canonical agents use reasoning, not model")
        for path in sorted(
            candidate for candidate in source.rglob("*")
            if candidate.is_file() and not candidate.is_symlink()
            and not is_python_cache(candidate)
        ):
            try:
                text = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            for token in CANONICAL_HOST_TOKENS:
                if token in text:
                    problems.append(f"{path}: canonical content contains host token {token!r}")
    if problems:
        raise ValueError("\n".join(problems))


def build(
    root: Path, output: Path,
    *, adapters: dict[str, HostAdapter] | None = None,
) -> None:
    validate_canonical(root)
    adapters = adapters or load_adapters(root)
    if set(adapters) != set(load_product_contract(root)["hosts"]):
        raise ValueError("trusted adapter set differs from the package host contract")
    marker_name, provenance_name = packaging_names(root)
    versions = load_plugin_versions(root)
    snapshot = marketplace_snapshot(root)
    for host, adapter in adapters.items():
        host_root = output / host
        host_root.mkdir(parents=True)
        for source in sorted(path for path in (root / "plugins").iterdir() if path.is_dir()):
            build_plugin(
                root, source, adapter, host_root / source.name, versions[source.name],
                marker_name, provenance_name, snapshot, adapters,
            )


def generated_tree_owned(output: Path, marker_name: str) -> bool:
    if not output.exists():
        return True
    plugin_dirs: list[Path] = []
    host_roots = sorted(output.iterdir())
    if not host_roots or any(not path.is_dir() for path in host_roots):
        return False
    for host_root in host_roots:
        packages = [path for path in host_root.iterdir() if path.is_dir()]
        if not packages:
            return False
        plugin_dirs.extend(packages)
    return bool(plugin_dirs) and all(
        (plugin / marker_name).is_file() for plugin in plugin_dirs
    )


def replace_generated(root: Path, output: Path) -> None:
    validate_canonical(root)
    sync_marketplace_paths_sources(root)
    marker_name, _ = packaging_names(root)
    if output.exists():
        if not generated_tree_owned(output, marker_name):
            raise ValueError("refusing to replace an unmanaged dist tree")
        shutil.rmtree(output)
    build(root, output)


def compare_dirs(expected: Path, actual: Path) -> list[str]:
    """Compare generated trees without shallow stat caches or symlink following."""
    problems: list[str] = []
    try:
        expected_mode = expected.lstat().st_mode
        actual_mode = actual.lstat().st_mode
        if not stat.S_ISDIR(expected_mode) or not stat.S_ISDIR(actual_mode):
            return [f"generated tree root is not a real directory: {actual}"]
        expected_entries = {path.name: path for path in expected.iterdir()}
        actual_entries = {path.name: path for path in actual.iterdir()}
    except OSError as exc:
        return [f"cannot inspect generated tree: {actual}: {exc}"]
    expected_names = set(expected_entries)
    actual_names = set(actual_entries)
    for name in sorted(expected_names - actual_names):
        problems.append(f"missing from generated tree: {actual / name}")
    for name in sorted(actual_names - expected_names):
        problems.append(f"stale in generated tree: {actual / name}")
    for name in sorted(expected_names & actual_names):
        expected_path = expected_entries[name]
        actual_path = actual_entries[name]
        try:
            expected_mode = expected_path.lstat().st_mode
            actual_mode = actual_path.lstat().st_mode
        except OSError as exc:
            problems.append(f"cannot inspect generated entry: {actual_path}: {exc}")
            continue
        if stat.S_ISLNK(expected_mode) or stat.S_ISLNK(actual_mode):
            problems.append(f"generated tree contains a symbolic link: {actual_path}")
            continue
        if stat.S_ISDIR(expected_mode) and stat.S_ISDIR(actual_mode):
            problems.extend(compare_dirs(expected_path, actual_path))
            continue
        if not stat.S_ISREG(expected_mode) or not stat.S_ISREG(actual_mode):
            problems.append(f"out of sync entry type: {actual_path}")
            continue
        try:
            if expected_path.read_bytes() != actual_path.read_bytes():
                problems.append(f"out of sync: {actual_path}")
        except OSError as exc:
            problems.append(f"cannot read generated file: {actual_path}: {exc}")
            continue
        expected_executable = bool(expected_mode & stat.S_IXUSR)
        actual_executable = bool(actual_mode & stat.S_IXUSR)
        if expected_executable != actual_executable:
            problems.append(f"out of sync executable mode: {actual_path}")
    return problems


def check(root: Path, output: Path) -> list[str]:
    problems: list[str] = []
    try:
        problems.extend(marketplace_paths_source_drift(root))
        with tempfile.TemporaryDirectory(prefix="agent-marketplace-dist-build-") as tmp:
            expected = Path(tmp) / "dist"
            build(root, expected)
            if not output.is_dir():
                problems.append("dist/ is missing")
            else:
                problems.extend(compare_dirs(expected, output))
    except ValueError as exc:
        problems.extend(str(exc).splitlines())
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = root / "dist"
    if args.check:
        problems = check(root, output)
        for problem in problems:
            print(f"distribution-build: {problem}")
        if problems:
            return 1
        print("distribution-build: host distributions are in sync")
        return 0
    try:
        replace_generated(root, output)
    except ValueError as exc:
        raise SystemExit(f"distribution-build: {exc}") from exc
    print("distribution-build: generated host distributions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
