#!/usr/bin/env python3
"""Build deterministic Claude and Codex plugin distributions.

Canonical product behavior lives under ``plugins/`` and is host-neutral.
Host manifests, contracts, overlays, and append-only fragments live under
``platforms/``.  This builder is the only writer of ``dist/``.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import re
import shutil
import tempfile
from pathlib import Path


HOSTS = ("claude", "codex")
MARKER = ".agentrof-generated-distribution"
WRAPPER_MARKER = "<!-- generated by tools/build_distributions.py; do not edit -->"
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
DISPLAY_TOKENS = {
    "api": "API",
    "cli": "CLI",
    "devops": "DevOps",
    "fastapi": "FastAPI",
    "nosql": "NoSQL",
    "pmo": "PMO",
    "qa": "QA",
    "sql": "SQL",
    "ui": "UI",
    "ux": "UX",
}
CLAUDE_MODELS = {
    "high": "opus",
    "medium": "sonnet",
    "low": "haiku",
    "inherit": "inherit",
}
CANONICAL_HOST_TOKENS = (
    "Claude",
    "Codex",
    "claude",
    "codex",
    "AskUserQuestion",
    "CLAUDE.md",
    "AGENTS.md",
    "CLAUDE_PLUGIN_ROOT",
    "PLUGIN_ROOT",
    ".claude",
    ".codex",
)
CANONICAL_COMPONENTS = {
    "agents",
    "constitution.md",
    "dashboard",
    "flows",
    "hooks",
    "scripts",
    "skill-content",
    "templates",
}
REPOSITORY_DIRECTORIES = {
    ".changes",
    ".agents",
    ".claude",
    ".claude-plugin",
    ".git",
    ".github",
    ".release",
    "assets",
    "dist",
    "docs",
    "memory",
    "platforms",
    "plugins",
    "tools",
}
SOURCE_IGNORES = {"agents"}
PYTHON_CACHE_SUFFIXES = {".pyc", ".pyo"}


def is_python_cache(path: Path) -> bool:
    return "__pycache__" in path.parts or path.suffix in PYTHON_CACHE_SUFFIXES


def ignore_python_cache(_directory: str, names: list[str]) -> set[str]:
    return {
        name for name in names
        if name == "__pycache__" or Path(name).suffix in PYTHON_CACHE_SUFFIXES
    }


def title_of(name: str) -> str:
    return " ".join(
        DISPLAY_TOKENS.get(part, part.capitalize()) for part in name.split("-")
    )


def parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if match is None:
        raise ValueError(f"{path}: missing YAML frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip().strip("\"'")
    return fields, text[match.end():]


def skill_metadata(path: Path) -> tuple[str, str, str]:
    fields, _ = parse_frontmatter(path)
    name = fields.get("name", "")
    description = fields.get("description", "")
    exposure = fields.get("exposure", "")
    if name != path.parent.name or not description:
        raise ValueError(f"{path}: name/description mismatch")
    if exposure not in {"entry", "internal"}:
        raise ValueError(f"{path}: exposure must be entry or internal")
    unexpected = set(fields) - {"name", "description", "exposure"}
    if unexpected:
        raise ValueError(
            f"{path}: canonical frontmatter has host or unknown fields: "
            + ", ".join(sorted(unexpected))
        )
    return name, description, exposure


def claude_skill_wrapper(
    plugin: str, name: str, description: str, exposure: str
) -> str:
    policy = (
        "disable-model-invocation: true\n"
        if exposure == "entry"
        else "user-invocable: false\n"
    )
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        f"{policy}"
        "---\n\n"
        f"{WRAPPER_MARKER}\n\n"
        f"# {title_of(name)}\n\n"
        "Read `${CLAUDE_PLUGIN_ROOT}/host-contract.md` and "
        f"`${{CLAUDE_PLUGIN_ROOT}}/skill-content/{name}/SKILL.md` completely. "
        "Follow the canonical skill as the authoritative workflow and the host "
        "contract as its platform adapter.\n"
    )


def codex_skill_wrapper(name: str, description: str) -> str:
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{WRAPPER_MARKER}\n\n"
        f"# {title_of(name)}\n\n"
        "Read `../../host-contract.md` and "
        f"`../../skill-content/{name}/SKILL.md` completely, resolving both paths "
        "relative to this file. Follow the canonical skill as the authoritative "
        "workflow and the host contract as its platform adapter.\n"
    )


def openai_yaml(plugin: str, name: str) -> str:
    visible = title_of(name)
    short = f"Start the {visible} guided workflow"
    if len(short) > 64:
        short = f"Run {visible}"
    return (
        "interface:\n"
        f"  display_name: \"{visible}\"\n"
        f"  short_description: \"{short}\"\n"
        f"  default_prompt: \"Use ${plugin}:{name} to start this workflow.\"\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    )


def claude_agent(source: Path) -> str:
    fields, body = parse_frontmatter(source)
    reasoning = fields.pop("reasoning", "")
    if reasoning not in CLAUDE_MODELS:
        raise ValueError(f"{source}: invalid reasoning level {reasoning!r}")
    ordered = ["name", "description"]
    lines = ["---"]
    for key in ordered:
        if not fields.get(key):
            raise ValueError(f"{source}: missing {key}")
        lines.append(f"{key}: {fields.pop(key)}")
    lines.append(f"model: {CLAUDE_MODELS[reasoning]}")
    for key, value in fields.items():
        lines.append(f"{key}: {value}")
    lines.extend(("---", "", body.lstrip("\n")))
    return "\n".join(lines)


def copy_canonical(source: Path, target: Path) -> None:
    def ignore(directory: str, names: list[str]) -> set[str]:
        ignored = ignore_python_cache(directory, names)
        if Path(directory) == source:
            ignored.update(name for name in names if name in SOURCE_IGNORES)
        return ignored

    shutil.copytree(source, target, ignore=ignore)


def copy_overlay(root: Path, target: Path) -> None:
    if root.is_dir():
        shutil.copytree(
            root, target, dirs_exist_ok=True, ignore=ignore_python_cache
        )


def apply_appends(root: Path, target: Path) -> None:
    if not root.is_dir():
        return
    for fragment in sorted(
        path for path in root.rglob("*")
        if path.is_file() and not is_python_cache(path)
    ):
        relative = fragment.relative_to(root)
        destination = target / relative
        if not destination.is_file():
            raise ValueError(f"{fragment}: append target does not exist: {relative}")
        base = destination.read_text(encoding="utf-8").rstrip("\n")
        extra = fragment.read_text(encoding="utf-8").strip("\n")
        destination.write_text(f"{base}\n\n{extra}\n", encoding="utf-8")


def generate_skills(source: Path, target: Path, host: str) -> None:
    skills = target / "skills"
    skills.mkdir()
    for canonical in sorted((source / "skill-content").glob("*/SKILL.md")):
        name, description, exposure = skill_metadata(canonical)
        if host == "codex" and exposure != "entry":
            continue
        skill_root = skills / name
        skill_root.mkdir()
        if host == "claude":
            text = claude_skill_wrapper(source.name, name, description, exposure)
        else:
            text = codex_skill_wrapper(name, description)
            metadata = skill_root / "agents" / "openai.yaml"
            metadata.parent.mkdir()
            metadata.write_text(openai_yaml(source.name, name), encoding="utf-8")
        (skill_root / "SKILL.md").write_text(text, encoding="utf-8")


def generate_agents(source: Path, target: Path, host: str) -> None:
    agents = source / "agents"
    if not agents.is_dir():
        return
    if host == "claude":
        destination = target / "agents"
        destination.mkdir()
        for path in sorted(agents.glob("*.md")):
            (destination / path.name).write_text(claude_agent(path), encoding="utf-8")
    else:
        shutil.copytree(agents, target / "agents")


def normalize_generated_text(root: Path) -> None:
    for path in sorted(
        candidate for candidate in root.rglob("*")
        if candidate.is_file() and not is_python_cache(candidate)
    ):
        data = path.read_bytes()
        if b"\0" in data:
            continue
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            continue
        normalized = text.replace("\r\n", "\n").replace("\r", "\n")
        if normalized != text:
            path.write_text(normalized, encoding="utf-8")


def load_plugin_versions(root: Path) -> dict[str, str]:
    path = root / "versions.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path}: missing or invalid canonical version registry") from exc
    plugins = data.get("plugins") if isinstance(data, dict) else None
    if not isinstance(plugins, dict):
        raise ValueError(f"{path}: plugins must be an object")
    expected = {
        source.name for source in (root / "plugins").iterdir() if source.is_dir()
    }
    if set(plugins) != expected:
        raise ValueError(
            f"{path}: plugin registry differs from plugins/: "
            f"registered={sorted(plugins)}, actual={sorted(expected)}"
        )
    return plugins


def build_plugin(
    root: Path, source: Path, host: str, target: Path, version: str
) -> None:
    platform = root / "platforms" / host / source.name
    shared = root / "platforms" / "shared" / source.name
    manifest = platform / "manifest.json"
    contract = platform / "host-contract.md"
    if not manifest.is_file() or not contract.is_file():
        raise ValueError(f"{platform}: missing manifest.json or host-contract.md")
    copy_canonical(source, target)
    if source.name != "project-management-office":
        copy_overlay(root / "platforms" / "shared" / "_team" / "overlay", target)
        copy_overlay(root / "platforms" / host / "_team" / "overlay", target)
    copy_overlay(shared / "overlay", target)
    copy_overlay(platform / "overlay", target)
    apply_appends(shared / "append", target)
    apply_appends(platform / "append", target)
    shutil.copy2(contract, target / "host-contract.md")
    manifest_dir = target / f".{host}-plugin"
    manifest_dir.mkdir()
    try:
        manifest_data = json.loads(manifest.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{manifest}: invalid JSON") from exc
    manifest_data["version"] = version
    (manifest_dir / "plugin.json").write_text(
        json.dumps(manifest_data, indent=2) + "\n", encoding="utf-8"
    )
    generate_skills(source, target, host)
    generate_agents(source, target, host)
    if source.name == "project-management-office":
        teams = sorted(
            path.name for path in (root / "plugins").iterdir()
            if path.is_dir() and path.name != "project-management-office"
        )
        (target / "team_plugins.json").write_text(
            json.dumps({"schema_version": 1, "plugins": teams}, indent=2) + "\n",
            encoding="utf-8",
        )
    (target / MARKER).write_text(
        "Generated by tools/build_distributions.py; do not edit.\n",
        encoding="utf-8",
    )
    normalize_generated_text(target)


def validate_canonical(root: Path) -> None:
    problems: list[str] = []
    for child in sorted(path for path in root.iterdir() if path.is_dir()):
        if child.name not in REPOSITORY_DIRECTORIES:
            problems.append(
                f"{child}: unsupported repository top-level directory; "
                "use the declared repository layout"
            )
    for surface_name in ("plugins", "platforms"):
        surface = root / surface_name
        if not surface.is_dir():
            continue
        for candidate in sorted(surface.rglob("*")):
            if candidate.is_symlink():
                problems.append(
                    f"{candidate}: symbolic links are forbidden in packaged sources"
                )
    for source in sorted(path for path in (root / "plugins").iterdir() if path.is_dir()):
        for child in sorted(source.iterdir()):
            if is_python_cache(child):
                continue
            if child.name not in CANONICAL_COMPONENTS:
                problems.append(
                    f"{child}: unsupported canonical top-level entry; "
                    "move host adapters under platforms/ or use a canonical component"
                )
        for skill in sorted((source / "skill-content").glob("*/SKILL.md")):
            try:
                skill_metadata(skill)
            except ValueError as exc:
                problems.append(str(exc))
        for agent in sorted((source / "agents").glob("*.md")):
            fields, _ = parse_frontmatter(agent)
            if fields.get("reasoning") not in CLAUDE_MODELS:
                problems.append(f"{agent}: reasoning must be high/medium/low/inherit")
            if "model" in fields:
                problems.append(f"{agent}: canonical agents use reasoning, not model")
        for path in sorted(
            candidate for candidate in source.rglob("*")
            if candidate.is_file() and not candidate.is_symlink()
            and not is_python_cache(candidate)
        ):
            try:
                text = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            for token in CANONICAL_HOST_TOKENS:
                if token in text:
                    problems.append(f"{path}: canonical content contains host token {token!r}")
    if problems:
        raise ValueError("\n".join(problems))


def build(root: Path, output: Path) -> None:
    validate_canonical(root)
    versions = load_plugin_versions(root)
    for host in HOSTS:
        host_root = output / host
        host_root.mkdir(parents=True)
        for source in sorted(path for path in (root / "plugins").iterdir() if path.is_dir()):
            build_plugin(
                root, source, host, host_root / source.name, versions[source.name]
            )


def generated_tree_owned(output: Path) -> bool:
    if not output.exists():
        return True
    plugin_dirs: list[Path] = []
    for host in HOSTS:
        host_root = output / host
        if not host_root.is_dir():
            return False
        plugin_dirs.extend(plugin for plugin in host_root.iterdir() if plugin.is_dir())
    return bool(plugin_dirs) and all((plugin / MARKER).is_file() for plugin in plugin_dirs)


def replace_generated(root: Path, output: Path) -> None:
    if output.exists():
        if not generated_tree_owned(output):
            raise ValueError("refusing to replace an unmanaged dist tree")
        shutil.rmtree(output)
    build(root, output)


def compare_dirs(expected: Path, actual: Path) -> list[str]:
    problems: list[str] = []
    comparison = filecmp.dircmp(expected, actual)
    for name in comparison.left_only:
        if is_python_cache(Path(name)):
            continue
        problems.append(f"missing from generated tree: {actual / name}")
    for name in comparison.right_only:
        if is_python_cache(Path(name)):
            continue
        problems.append(f"stale in generated tree: {actual / name}")
    for name in comparison.diff_files + comparison.funny_files:
        if is_python_cache(Path(name)):
            continue
        problems.append(f"out of sync: {actual / name}")
    for name in comparison.common_dirs:
        if is_python_cache(Path(name)):
            continue
        problems.extend(compare_dirs(expected / name, actual / name))
    return problems


def check(root: Path, output: Path) -> list[str]:
    problems: list[str] = []
    try:
        with tempfile.TemporaryDirectory(prefix="agentrof-dist-build-") as tmp:
            expected = Path(tmp) / "dist"
            build(root, expected)
            if not output.is_dir():
                problems.append("dist/ is missing")
            else:
                problems.extend(compare_dirs(expected, output))
    except ValueError as exc:
        problems.extend(str(exc).splitlines())
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = root / "dist"
    if args.check:
        problems = check(root, output)
        for problem in problems:
            print(f"distribution-build: {problem}")
        if problems:
            return 1
        print("distribution-build: Claude and Codex distributions are in sync")
        return 0
    try:
        replace_generated(root, output)
    except ValueError as exc:
        raise SystemExit(f"distribution-build: {exc}") from exc
    print("distribution-build: generated Claude and Codex distributions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
