#!/usr/bin/env python3
"""Build self-contained Codex plugin archives from canonical plugin sources."""

from __future__ import annotations

import argparse
import filecmp
import shutil
import tempfile
from pathlib import Path


MARKER = ".agentrof-generated-codex-plugin"
IGNORED = {".claude-plugin", "claude-skills", ".codex-plugin"}


def normalize_generated_text(root: Path) -> None:
    """Give generated text archives stable LF endings without touching sources."""
    for path in sorted(candidate for candidate in root.rglob("*") if candidate.is_file()):
        data = path.read_bytes()
        if b"\0" in data:
            continue
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            continue
        normalized = text.replace("\r\n", "\n").replace("\r", "\n")
        if normalized != text:
            path.write_text(normalized, encoding="utf-8")


def copy_plugin(source: Path, target: Path) -> None:
    def ignore(directory: str, names: list[str]) -> set[str]:
        ignored = {name for name in names if name in IGNORED}
        if Path(directory) == source / "codex":
            ignored.add("plugin.json")
        return ignored

    shutil.copytree(source, target, ignore=ignore)
    codex_skills = target / "codex-skills"
    skills = target / "skills"
    if not codex_skills.is_dir():
        raise ValueError(f"{source}: missing generated codex-skills/")
    codex_skills.rename(skills)
    manifest = source / "codex" / "plugin.json"
    if not manifest.is_file():
        raise ValueError(f"{source}: missing codex/plugin.json")
    (target / ".codex-plugin").mkdir()
    shutil.copy2(manifest, target / ".codex-plugin" / "plugin.json")
    (target / MARKER).write_text(
        "Generated by tools/build_codex_plugins.py; do not edit.\n",
        encoding="utf-8",
    )
    normalize_generated_text(target)


def build(root: Path, output: Path) -> None:
    output.mkdir(parents=True)
    for source in sorted(path for path in (root / "plugins").iterdir() if path.is_dir()):
        copy_plugin(source, output / source.name)


def replace_generated(root: Path, output: Path) -> None:
    """Replace only an archive tree wholly owned by this generator."""
    if output.exists():
        markers = list(output.glob(f"*/{MARKER}"))
        plugin_dirs = [path for path in output.iterdir() if path.is_dir()]
        if len(markers) != len(plugin_dirs):
            raise ValueError(
                "refusing to replace an unmanaged codex-plugins tree"
            )
        shutil.rmtree(output)
    build(root, output)


def compare_dirs(expected: Path, actual: Path) -> list[str]:
    problems: list[str] = []
    comparison = filecmp.dircmp(expected, actual)
    for name in comparison.left_only:
        problems.append(f"missing from generated tree: {actual / name}")
    for name in comparison.right_only:
        problems.append(f"stale in generated tree: {actual / name}")
    for name in comparison.diff_files + comparison.funny_files:
        problems.append(f"out of sync: {actual / name}")
    for name, child in comparison.subdirs.items():
        problems.extend(compare_dirs(expected / name, actual / name))
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = root / "codex-plugins"
    if args.check:
        with tempfile.TemporaryDirectory(prefix="agentrof-codex-build-") as tmp:
            expected = Path(tmp) / "codex-plugins"
            build(root, expected)
            if not output.is_dir():
                print("codex-build: codex-plugins/ is missing")
                return 1
            problems = compare_dirs(expected, output)
            for problem in problems:
                print(f"codex-build: {problem}")
            if problems:
                return 1
        print("codex-build: generated plugins are in sync")
        return 0

    try:
        replace_generated(root, output)
    except ValueError as exc:
        raise SystemExit(f"codex-build: {exc}") from exc
    print("codex-build: generated self-contained Codex plugins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
