#!/usr/bin/env python3
"""Multi-harness artifact renderer for the Agent Marketplace.

One source tree under plugins/ (Claude Code native), many install surfaces.
Every per-harness value (paths, event routes, matcher token expansions,
frontmatter dispositions, model map, command rewrite policy) lives in
tools/data/harnesses.json; this module implements only the closed action
vocabulary, the emitters and the drift differ. Adding a harness whose needs
fit the listed vocabulary is a config edit, never a Python change.

Consumed by tools/generate.py (CLI), tools/validate.py (drift + scope) and
tools/scaffold.py (regeneration after scaffolding).

Stdlib only. Deterministic output: rendering twice is byte-identical.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

CONFIG_RELPATH = "tools/data/harnesses.json"

MATRIX_START = "<!-- harness-matrix:start -->"
MATRIX_END = "<!-- harness-matrix:end -->"
HARNESSES_DOC_RELPATH = "docs/harnesses.md"

# The one hand-authored sentence pair around the injected matrix when the
# doc does not exist yet; later prose edits around the markers survive.
HARNESSES_DOC_SKELETON = """# Harness support

The source of truth is the Claude Code tree under plugins/. Every other
install surface is generated by tools/generate.py from
tools/data/harnesses.json; generated files are never hand-edited and CI
fails on drift.

{start}
{end}
"""

FRONTMATTER_ACTIONS = {
    "keep",
    "drop",
    "rename",
    "replace_when_present",
    "map_model",
    "policy_flag",
    "nest",
}

COMMAND_TOKEN_RE = re.compile(
    r"\"\$\{CLAUDE_PLUGIN_ROOT\}\"/([A-Za-z0-9_\-./]+)"
)


class HarnessConfigError(ValueError):
    """Raised when the config cannot drive a deterministic render."""


# ---------------------------------------------------------------------------
# Loading and parsing
# ---------------------------------------------------------------------------


def load_config(root: Path) -> dict:
    path = root / CONFIG_RELPATH
    if not path.is_file():
        raise HarnessConfigError(f"missing {CONFIG_RELPATH}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise HarnessConfigError(f"{CONFIG_RELPATH}: invalid JSON: {exc}") from exc
    if not isinstance(config.get("harnesses"), dict) or not config["harnesses"]:
        raise HarnessConfigError(f"{CONFIG_RELPATH}: harnesses must be a non-empty object")
    return config


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (ordered frontmatter dict with raw values, body text)."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    fm: dict[str, str] = {}
    for i in range(1, len(lines)):
        stripped = lines[i].strip()
        if stripped == "---":
            return fm, "\n".join(lines[i + 1:])
        if not stripped or stripped.startswith("#"):
            continue
        if ":" in stripped:
            key, _, value = stripped.partition(":")
            fm[key.strip()] = value.strip()
    return {}, text


def title_of(name: str) -> str:
    return " ".join(word.capitalize() for word in name.split("-"))


def plugin_dirs(root: Path) -> list[Path]:
    plugins = root / "plugins"
    if not plugins.is_dir():
        return []
    return sorted(p for p in plugins.iterdir() if p.is_dir())


def agent_files(plugin: Path) -> list[Path]:
    agents = plugin / "agents"
    return sorted(agents.glob("*.md")) if agents.is_dir() else []


def skill_dirs(plugin: Path) -> list[Path]:
    skills = plugin / "skills"
    if not skills.is_dir():
        return []
    return sorted(d for d in skills.iterdir() if d.is_dir() and (d / "SKILL.md").is_file())


# ---------------------------------------------------------------------------
# Emit helpers (format code, not variation points)
# ---------------------------------------------------------------------------


def dumps_json(data: object) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def toml_multiline(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def rewrite_command(command: str, policy: dict) -> str:
    """Apply the harness command_rewrite policy to one hook command.

    keep_verbatim: identity. env_prefix: swap the Claude plugin-root token
    for the harness variable with a shell-level default, keeping the quoted
    path unit and any argument tail intact.
    """
    kind = policy.get("policy", "keep_verbatim")
    if kind == "keep_verbatim":
        return command
    if kind == "env_prefix":
        var = policy["var"]
        fallback = policy.get("fallback", ".")
        return COMMAND_TOKEN_RE.sub(
            lambda m: f'"${{{var}:-{fallback}}}/{m.group(1)}"', command
        )
    raise HarnessConfigError(f"unknown command_rewrite policy '{kind}'")


# ---------------------------------------------------------------------------
# Model and frontmatter dispositions
# ---------------------------------------------------------------------------


def resolve_model(harness: dict, alias: str) -> dict:
    model_map = harness.get("model_map", {})
    if alias in model_map:
        return model_map[alias]
    fallback = harness.get("model_fallback", "inherit")
    return model_map.get(fallback, {})


def _check_action(spec: dict, key: str, harness_id: str) -> str:
    action = spec.get("action", "")
    if action not in FRONTMATTER_ACTIONS:
        raise HarnessConfigError(
            f"harness '{harness_id}' frontmatter key '{key}' uses unknown"
            f" action '{action}'"
        )
    return action


# ---------------------------------------------------------------------------
# Agents
# ---------------------------------------------------------------------------


def render_cursor_agent(fm: dict[str, str], body: str, harness: dict, harness_id: str) -> str:
    lines = ["---"]
    for key, raw in fm.items():
        spec = harness.get("agent_frontmatter", {}).get(key)
        if spec is None:
            continue
        action = _check_action(spec, key, harness_id)
        if action == "drop":
            continue
        if action == "keep":
            lines.append(f"{key}: {raw}")
        elif action == "rename":
            lines.append(f"{spec['to']}: {raw}")
        elif action == "map_model":
            row = resolve_model(harness, raw)
            if "model" in row:
                lines.append(f"model: {row['model']}")
        elif action == "replace_when_present":
            value = spec["value"]
            rendered = "true" if value is True else "false" if value is False else str(value)
            lines.append(f"{spec['key']}: {rendered}")
    lines.append("---")
    return "\n".join(lines) + "\n" + body.rstrip("\n") + "\n"


def render_toml_agent(fm: dict[str, str], body: str, harness: dict, harness_id: str) -> str:
    pairs: list[tuple[str, str]] = []
    for key, raw in fm.items():
        spec = harness.get("agent_frontmatter", {}).get(key)
        if spec is None:
            continue
        action = _check_action(spec, key, harness_id)
        if action == "drop":
            continue
        if action == "keep":
            pairs.append((key, f'"{toml_escape(raw)}"'))
        elif action == "rename":
            pairs.append((spec["to"], f'"{toml_escape(raw)}"'))
        elif action == "map_model":
            row = resolve_model(harness, raw)
            for mk in ("model", "model_reasoning_effort"):
                if mk in row:
                    pairs.append((mk, f'"{toml_escape(str(row[mk]))}"'))
        elif action == "replace_when_present":
            value = spec["value"]
            rendered = ("true" if value is True else "false" if value is False
                        else f'"{toml_escape(str(value))}"')
            pairs.append((spec["key"], rendered))
    out = [f"{key} = {value}" for key, value in pairs]
    out.append('developer_instructions = """')
    out.append(toml_multiline(body.strip("\n")))
    out.append('"""')
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Skill policy files (openai.yaml)
# ---------------------------------------------------------------------------


def render_skill_policy(fm: dict[str, str], harness: dict, harness_id: str) -> str | None:
    """Render the per-skill policy file for harnesses that declare one.

    Emits the two-level interface/policy nesting; the only list-bearing
    block of the documented schema (dependencies) is never emitted, so a
    flat hand-rolled writer is sufficient.
    """
    if "skill_policy_file" not in harness:
        return None
    policy_lines: list[str] = []
    for key, spec in harness.get("skill_frontmatter", {}).items():
        action = _check_action(spec, key, harness_id)
        if action != "policy_flag":
            continue
        raw = fm.get(key, "false")
        flag = spec["when_true"] if raw == "true" else spec["when_false"]
        policy_lines.append(
            f"  {spec['policy_key']}: {'true' if flag else 'false'}"
        )
    name = fm.get("name", "")
    description = fm.get("description", "")
    lines = [
        "interface:",
        f"  display_name: {yaml_quote(title_of(name))}",
        f"  short_description: {yaml_quote(description)}",
    ]
    if policy_lines:
        lines.append("policy:")
        lines.extend(policy_lines)
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Hooks
# ---------------------------------------------------------------------------


def _matcher_tokens(matcher: str) -> list[str]:
    return [t for t in matcher.split("|") if t]


def _derive_matcher(matcher: str, route: dict, expansions: dict) -> str:
    drop = set(route.get("drop_tokens", []))
    out: list[str] = []
    for token in _matcher_tokens(matcher):
        if token in drop:
            continue
        for expanded in expansions.get(token, [token]):
            if expanded not in out:
                out.append(expanded)
    return "|".join(out)


def _is_guard_command(command: str, harness: dict) -> bool:
    return any(marker in command for marker in harness.get("guard_command_markers", []))


def render_hooks(source: dict, harness: dict, harness_id: str) -> dict:
    """Transform a source hooks.json object into the harness manifest.

    Every source entry must be claimed by at least one route or belong to
    an event listed in unsupported_events; a silently dropped entry is a
    config error, never an omission.
    """
    routes = harness.get("hook_routes", [])
    unsupported = set(harness.get("unsupported_events", []))
    expansions = harness.get("token_expansions", {})
    rewrite = harness.get("command_rewrite", {"policy": "keep_verbatim"})
    fmt = harness.get("agent_format", "")
    cursor_style = "hooks_version" in harness

    out_events: dict[str, list] = {}
    for event, entries in source.get("hooks", {}).items():
        for entry in entries:
            matcher = entry.get("matcher", "")
            tokens = set(_matcher_tokens(matcher))
            routed = False
            for route in routes:
                if route.get("source_event") != event:
                    continue
                required = route.get("requires_token")
                if required and required not in tokens:
                    continue
                routed = True
                mode = route.get("matcher", "keep")
                if mode == "none":
                    target_matcher = ""
                elif mode == "derive":
                    target_matcher = _derive_matcher(matcher, route, expansions)
                else:
                    target_matcher = matcher
                for hook in entry.get("hooks", []):
                    command = rewrite_command(hook.get("command", ""), rewrite)
                    target = route["target_event"]
                    if cursor_style:
                        item: dict = {"command": command}
                        if target_matcher:
                            item["matcher"] = target_matcher
                        if _is_guard_command(command, harness):
                            item.update(harness.get("guard_options", {}))
                        out_events.setdefault(target, []).append(item)
                    else:
                        bucket = out_events.setdefault(target, [])
                        wrapped = None
                        for existing in bucket:
                            if existing.get("matcher", "") == target_matcher:
                                wrapped = existing
                                break
                        if wrapped is None:
                            wrapped = {}
                            if target_matcher:
                                wrapped["matcher"] = target_matcher
                            wrapped["hooks"] = []
                            bucket.append(wrapped)
                        wrapped["hooks"].append({"type": "command", "command": command})
            if not routed and event not in unsupported:
                raise HarnessConfigError(
                    f"harness '{harness_id}' has no route for source event"
                    f" '{event}' (matcher '{matcher}') and does not list it"
                    f" as unsupported"
                )
    _ = fmt
    if cursor_style:
        return {"version": harness["hooks_version"], "hooks": out_events}
    return {"hooks": out_events}


# ---------------------------------------------------------------------------
# Manifests
# ---------------------------------------------------------------------------


def _read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def render_cursor_plugin_manifest(plugin: Path, source_manifest: dict,
                                  harness: dict, has_hooks: bool) -> dict:
    out: dict = {"name": source_manifest.get("name", plugin.name)}
    if source_manifest.get("description"):
        out["description"] = source_manifest["description"]
    if source_manifest.get("version"):
        out["version"] = source_manifest["version"]
    author = source_manifest.get("author") or {}
    if author.get("name"):
        out["author"] = {"name": author["name"]}
    if author.get("url"):
        out["homepage"] = author["url"]
    if source_manifest.get("license"):
        out["license"] = source_manifest["license"]
    if agent_files(plugin):
        out["agents"] = "./" + harness["agents_dir"]
    if has_hooks:
        out["hooks"] = "./" + harness["hooks_manifest"]
    return out


def render_codex_plugin_manifest(plugin: Path, source_manifest: dict,
                                 harness: dict, has_hooks: bool) -> dict:
    out: dict = {"name": source_manifest.get("name", plugin.name)}
    if source_manifest.get("version"):
        out["version"] = source_manifest["version"]
    if source_manifest.get("description"):
        out["description"] = source_manifest["description"]
    author = source_manifest.get("author") or {}
    if author.get("name"):
        out["author"] = {"name": author["name"]}
    if author.get("url"):
        out["homepage"] = author["url"]
    if source_manifest.get("license"):
        out["license"] = source_manifest["license"]
    if skill_dirs(plugin):
        out["skills"] = "./skills/"
    if has_hooks:
        out["hooks"] = "./" + harness["hooks_manifest"]
    return out


def render_cursor_marketplace(source_marketplace: dict) -> dict:
    owner = source_marketplace.get("owner") or {}
    out: dict = {"name": source_marketplace.get("name", "")}
    out["owner"] = {"name": owner.get("name", "")}
    out["plugins"] = [
        {
            "name": entry.get("name", ""),
            "source": entry.get("source", ""),
            "description": entry.get("description", ""),
            "version": entry.get("version", ""),
            "license": entry.get("license", ""),
        }
        for entry in source_marketplace.get("plugins", [])
    ]
    return out


def render_codex_marketplace(source_marketplace: dict) -> dict:
    return {
        "name": source_marketplace.get("name", ""),
        "plugins": [
            {
                "name": entry.get("name", ""),
                "description": entry.get("description", ""),
                "source": {"source": "local", "path": entry.get("source", "")},
            }
            for entry in source_marketplace.get("plugins", [])
        ],
    }


# ---------------------------------------------------------------------------
# Templates and docs
# ---------------------------------------------------------------------------


def render_agents_md(claude_md_text: str) -> str:
    """Derive templates/AGENTS.md from templates/CLAUDE.md.

    The @-import lines are a Claude Code memory mechanism; the prose
    directive that duplicates each import stays, so the derived file loses
    no instruction.
    """
    lines = [l for l in claude_md_text.splitlines() if not l.startswith("@")]
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.rstrip("\n") + "\n"


def render_matrix_block(config: dict) -> str:
    rows = config.get("docs", {}).get("matrix_rows", [])
    lines = [
        MATRIX_START,
        "| Capability | Claude Code | Cursor | Codex CLI |",
        "|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row.get('capability', '')} | {row.get('claude_code', '')} |"
            f" {row.get('cursor', '')} | {row.get('codex', '')} |"
        )
    lines.append(MATRIX_END)
    return "\n".join(lines)


def inject_matrix(existing_text: str, block: str) -> str:
    pattern = re.compile(
        re.escape(MATRIX_START) + r".*?" + re.escape(MATRIX_END), re.DOTALL
    )
    if pattern.search(existing_text):
        return pattern.sub(block, existing_text, count=1)
    return existing_text.rstrip("\n") + "\n\n" + block + "\n"


# ---------------------------------------------------------------------------
# Render everything
# ---------------------------------------------------------------------------


def render_all(root: Path, config: dict) -> dict[str, str]:
    """Return relpath -> exact file content for every generated artifact.

    docs/harnesses.md is span-managed and handled separately (see
    matrix drift helpers); it does not appear in this map.
    """
    rendered: dict[str, str] = {}
    harnesses = config["harnesses"]
    source_marketplace = _read_json(root / ".claude-plugin" / "marketplace.json")

    for harness_id in sorted(harnesses):
        harness = harnesses[harness_id]
        if harness_id == "cursor":
            rendered[harness["marketplace_path"]] = dumps_json(
                render_cursor_marketplace(source_marketplace))
        elif harness_id == "codex":
            rendered[harness["marketplace_path"]] = dumps_json(
                render_codex_marketplace(source_marketplace))

    for plugin in plugin_dirs(root):
        source_manifest = _read_json(plugin / ".claude-plugin" / "plugin.json")
        source_hooks_path = plugin / "hooks" / "hooks.json"
        source_hooks = _read_json(source_hooks_path) if source_hooks_path.is_file() else {}
        has_hooks = bool(source_hooks.get("hooks"))
        prefix = f"plugins/{plugin.name}"

        for harness_id in sorted(harnesses):
            harness = harnesses[harness_id]
            fmt = harness.get("agent_format", "markdown")

            if harness_id == "cursor":
                manifest = render_cursor_plugin_manifest(plugin, source_manifest, harness, has_hooks)
            else:
                manifest = render_codex_plugin_manifest(plugin, source_manifest, harness, has_hooks)
            rendered[f"{prefix}/{harness['plugin_manifest_path']}"] = dumps_json(manifest)

            if has_hooks:
                hooks_out = render_hooks(source_hooks, harness, harness_id)
                rendered[f"{prefix}/{harness['hooks_manifest']}"] = dumps_json(hooks_out)

            for agent in agent_files(plugin):
                fm, body = parse_frontmatter(agent.read_text(encoding="utf-8"))
                if fmt == "markdown":
                    content = render_cursor_agent(fm, body, harness, harness_id)
                    rendered[f"{prefix}/{harness['agents_dir']}/{agent.stem}.md"] = content
                elif fmt == "toml":
                    content = render_toml_agent(fm, body, harness, harness_id)
                    name = fm.get("name", agent.stem)
                    rendered[f"{prefix}/{harness['agents_dir']}/{name}.toml"] = content

            for sdir in skill_dirs(plugin):
                if "skill_policy_file" not in harness:
                    continue
                fm, _ = parse_frontmatter((sdir / "SKILL.md").read_text(encoding="utf-8"))
                policy = render_skill_policy(fm, harness, harness_id)
                if policy is not None:
                    rendered[
                        f"{prefix}/skills/{sdir.name}/{harness['skill_policy_file']}"
                    ] = policy

        claude_md = plugin / "templates" / "CLAUDE.md"
        if claude_md.is_file():
            rendered[f"{prefix}/templates/AGENTS.md"] = render_agents_md(
                claude_md.read_text(encoding="utf-8"))

    runtime = config.get("runtime")
    if runtime and runtime.get("path"):
        runtime_path = Path(runtime["path"])
        if (root / runtime_path.parent.parent).is_dir():
            payload = {k: v for k, v in runtime.items() if k != "path"}
            rendered[runtime["path"]] = dumps_json(payload)

    return rendered


# ---------------------------------------------------------------------------
# Generated-scope predicate (consumed by the validator's walkers)
# ---------------------------------------------------------------------------


def generated_roots(config: dict) -> list[str]:
    """Directory prefixes (relative to a plugin dir or the repo root) that
    the renderer owns exclusively; used for orphan scanning and for the
    validator's is_generated predicate."""
    roots: list[str] = []
    for harness in config["harnesses"].values():
        roots.append(harness["plugin_manifest_path"].split("/")[0])
        roots.append(harness["agents_dir"].split("/")[0])
        roots.append(harness["hooks_manifest"].split("/")[0])
        roots.append(harness["marketplace_path"].split("/")[0])
    return sorted(set(roots))


def is_generated(root: Path, config: dict, path: Path) -> bool:
    """True when path is a generated artifact (never content-scanned;
    proven by renderer construction plus byte-drift equality instead)."""
    try:
        relparts = path.relative_to(root).parts
    except ValueError:
        return False
    if not relparts:
        return False
    roots = set(generated_roots(config))
    if relparts[0] in roots:
        return True
    if relparts[0] == "plugins" and len(relparts) >= 3:
        if relparts[2] in roots:
            return True
        if (len(relparts) >= 5 and relparts[2] == "skills"
                and relparts[4] == "agents"):
            return True
        if relparts[2] == "templates" and relparts[-1] == "AGENTS.md":
            return True
        runtime = config.get("runtime", {})
        if runtime.get("path") and path == root / runtime["path"]:
            return True
    return False


# ---------------------------------------------------------------------------
# Drift and writing
# ---------------------------------------------------------------------------


def _orphan_scan_dirs(root: Path, config: dict) -> list[Path]:
    dirs: list[Path] = []
    roots = generated_roots(config)
    for name in roots:
        candidate = root / name
        if candidate.is_dir():
            dirs.append(candidate)
    for plugin in plugin_dirs(root):
        for name in roots:
            candidate = plugin / name
            if candidate.is_dir():
                dirs.append(candidate)
        for sdir in skill_dirs(plugin):
            candidate = sdir / "agents"
            if candidate.is_dir():
                dirs.append(candidate)
    return dirs


def diff(root: Path, config: dict, rendered: dict[str, str] | None = None) -> list[tuple[str, str]]:
    """Return [(relpath, reason)] where reason is missing | stale | orphan."""
    if rendered is None:
        rendered = render_all(root, config)
    problems: list[tuple[str, str]] = []
    for relpath, content in sorted(rendered.items()):
        target = root / relpath
        if not target.is_file():
            problems.append((relpath, "missing"))
        elif target.read_text(encoding="utf-8") != content:
            problems.append((relpath, "stale"))
    rendered_paths = {root / rp for rp in rendered}
    for scan_dir in _orphan_scan_dirs(root, config):
        for path in sorted(p for p in scan_dir.rglob("*") if p.is_file()):
            if path not in rendered_paths:
                problems.append((path.relative_to(root).as_posix(), "orphan"))
    doc = root / HARNESSES_DOC_RELPATH
    block = render_matrix_block(config)
    if not doc.is_file():
        problems.append((HARNESSES_DOC_RELPATH, "missing"))
    else:
        text = doc.read_text(encoding="utf-8")
        if inject_matrix(text, block) != text:
            problems.append((HARNESSES_DOC_RELPATH, "stale"))
    return sorted(set(problems))


def write_all(root: Path, config: dict) -> list[str]:
    """Write every artifact; idempotent. Returns relpaths written/changed."""
    rendered = render_all(root, config)
    changed: list[str] = []
    for relpath, content in sorted(rendered.items()):
        target = root / relpath
        if target.is_file() and target.read_text(encoding="utf-8") == content:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        changed.append(relpath)
    rendered_paths = {root / rp for rp in rendered}
    for scan_dir in _orphan_scan_dirs(root, config):
        for path in sorted(p for p in scan_dir.rglob("*") if p.is_file()):
            if path not in rendered_paths:
                path.unlink()
                changed.append(path.relative_to(root).as_posix() + " (removed)")
    doc = root / HARNESSES_DOC_RELPATH
    block = render_matrix_block(config)
    if not doc.is_file():
        doc.parent.mkdir(parents=True, exist_ok=True)
        skeleton = HARNESSES_DOC_SKELETON.format(start=MATRIX_START, end=MATRIX_END)
        doc.write_text(inject_matrix(skeleton, block), encoding="utf-8")
        changed.append(HARNESSES_DOC_RELPATH)
    else:
        text = doc.read_text(encoding="utf-8")
        new_text = inject_matrix(text, block)
        if new_text != text:
            doc.write_text(new_text, encoding="utf-8")
            changed.append(HARNESSES_DOC_RELPATH)
    return changed
