#!/usr/bin/env python3
"""Build the Claude and Codex skill discovery surfaces.

The complete skill packages live under ``skill-content/``.  Host-facing
``SKILL.md`` files are deliberately tiny: they preserve each host's metadata
contract and direct the agent to the one canonical package.  This script is
also the drift checker used by ``make check``.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path


GENERATED_MARKER = "<!-- generated by tools/sync_skill_surfaces.py; do not edit -->"
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
DISPLAY_TOKENS = {
    "api": "API",
    "cli": "CLI",
    "devops": "DevOps",
    "fastapi": "FastAPI",
    "nosql": "NoSQL",
    "pmo": "PMO",
    "qa": "QA",
    "sql": "SQL",
    "ui": "UI",
    "ux": "UX",
}
DISPLAY_OVERRIDES = {
    ("software-engineering-team", "build-docs-vault"):
        "Build Docs Vault (Legacy Alias)",
    ("software-engineering-team", "request"): "Request (Legacy Alias)",
}


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = FRONTMATTER_RE.match(text)
    if match is None:
        raise ValueError("SKILL.md must start with YAML frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip()
    return fields, match.group(1)


def title_of(name: str) -> str:
    return " ".join(
        DISPLAY_TOKENS.get(part, part.capitalize()) for part in name.split("-")
    )


def display_name(plugin: str, name: str) -> str:
    return DISPLAY_OVERRIDES.get((plugin, name), title_of(name))


def claude_wrapper(
    plugin: str, name: str, frontmatter: str, has_agents: bool
) -> str:
    agent_adapter = (
        " When it says to spawn a bare canonical agent id, use this plugin's "
        f"`{plugin}:<agent-id>` Claude identity."
        if has_agents else ""
    )
    return (
        f"---\n{frontmatter}\n---\n\n{GENERATED_MARKER}\n\n"
        f"# {title_of(name)}\n\n"
        f"Read `${{CLAUDE_PLUGIN_ROOT}}/skill-content/{name}/SKILL.md` completely, "
        "then follow it as the authoritative workflow. Resolve every relative resource "
        f"from that canonical skill directory.{agent_adapter}\n"
    )


def codex_wrapper(plugin: str, name: str, description: str) -> str:
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"# {title_of(name)}\n\n"
        "Read `../../codex/host-contract.md` and "
        f"`../../skill-content/{name}/SKILL.md` completely, resolving both paths "
        "relative to this file. Follow the canonical skill as the workflow and the "
        "Codex contract as the host adapter.\n"
    )


def openai_yaml(plugin: str, name: str, description: str) -> str:
    visible = display_name(plugin, name)
    short = f"Start the {visible} guided workflow"
    if len(short) > 64:
        short = f"Run {visible}"
    return (
        "interface:\n"
        f"  display_name: \"{visible}\"\n"
        f"  short_description: \"{short}\"\n"
        f"  default_prompt: \"Use ${plugin}:{name} to start this workflow.\"\n"
        "policy:\n"
        "  allow_implicit_invocation: false\n"
    )


def expected_files(plugin: Path) -> dict[Path, str]:
    canonical = plugin / "skill-content"
    if not canonical.is_dir():
        raise ValueError(f"{plugin}: missing skill-content/")
    expected: dict[Path, str] = {}
    for skill in sorted(path for path in canonical.iterdir() if path.is_dir()):
        source = skill / "SKILL.md"
        if not source.is_file():
            raise ValueError(f"{skill}: missing SKILL.md")
        fields, raw_frontmatter = parse_frontmatter(source.read_text(encoding="utf-8"))
        name = fields.get("name", "").strip("\"'")
        description = fields.get("description", "").strip("\"'")
        if name != skill.name or not description:
            raise ValueError(f"{source}: name/description mismatch")
        expected[plugin / "claude-skills" / name / "SKILL.md"] = claude_wrapper(
            plugin.name, name, raw_frontmatter,
            any((plugin / "agents").glob("*.md")),
        )
        if fields.get("disable-model-invocation", "").lower() == "true":
            expected[plugin / "codex-skills" / name / "SKILL.md"] = codex_wrapper(
                plugin.name, name, description
            )
            expected[
                plugin / "codex-skills" / name / "agents" / "openai.yaml"
            ] = openai_yaml(plugin.name, name, description)
    return expected


def migrate(plugin: Path) -> None:
    old = plugin / "skills"
    canonical = plugin / "skill-content"
    if old.is_dir() and not canonical.exists():
        shutil.move(str(old), str(canonical))
    elif old.exists():
        raise ValueError(f"{plugin}: both skills/ and skill-content/ exist")


def sync_plugin(plugin: Path, check: bool) -> list[str]:
    expected = expected_files(plugin)
    problems: list[str] = []
    for path, content in expected.items():
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual == content:
            continue
        if check:
            problems.append(f"out of sync: {path}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    expected_paths = set(expected)
    for surface in (plugin / "claude-skills", plugin / "codex-skills"):
        if not surface.is_dir():
            continue
        for path in sorted(surface.rglob("SKILL.md")):
            if path in expected_paths:
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            if GENERATED_MARKER not in text:
                problems.append(f"unmanaged stale wrapper: {path}")
                continue
            if check:
                problems.append(f"stale generated wrapper: {path}")
            else:
                shutil.rmtree(path.parent)
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    plugins = sorted(path for path in (root / "plugins").iterdir() if path.is_dir())
    if not args.check:
        for plugin in plugins:
            migrate(plugin)
    problems: list[str] = []
    for plugin in plugins:
        try:
            problems.extend(sync_plugin(plugin, args.check))
        except ValueError as exc:
            problems.append(str(exc))
    for problem in problems:
        print(f"skill-surfaces: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"skill-surfaces: {'checked' if args.check else 'synced'} {len(plugins)} plugins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
