#!/usr/bin/env python3
"""PreToolUse guard: deny direct Write/Edit access to machine-owned files.

Four families of protected targets, each with its own remediation:
  1. The PMO database files: written only through the PMO CLI.
  2. Generated views: any file whose first line carries a generated-by
     marker (pmo render, ba_compile render, future generators), and any
     path inside a _generated directory. Regenerate with the owning
     render command instead.
  3. Frozen analysis docs: paths listed in the freeze manifest
     (freeze.json) of an ACTIVE work order; a mid-order edit would fork
     the spec the order builds from.
  4. Locked records: authored files whose frontmatter carries
     'locked: true' (closed audit records; a new round is a new file).

A denial exits 2, which cancels the tool call and feeds the reason back
to the model. Everything else exits 0; a guard must never take a
session down on its own errors."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import hook_common
import pmo_cli

GENERATED_MARKER_RE = re.compile(
    r"^<!-- generated by [a-z0-9_ .-]+; do not edit by hand -->"
)
LOCKED_RE = re.compile(r"^locked:\s*true\s*$")


def deny(message: str) -> int:
    print(f"pmo guard: {message}", file=sys.stderr)
    return 2


def frontmatter_locked(target: Path) -> bool:
    """True when the file opens with a YAML frontmatter block carrying
    'locked: true'."""
    try:
        with target.open("r", encoding="utf-8", errors="replace") as fh:
            if fh.readline().strip() != "---":
                return False
            for _ in range(40):  # frontmatter blocks are small
                line = fh.readline()
                if not line or line.strip() == "---":
                    return False
                if LOCKED_RE.match(line.strip()):
                    return True
    except Exception:
        return False
    return False


def frozen_by_work_order(target: Path, cwd: str) -> str | None:
    """Return the work-order key freezing this path, or None.

    Freeze manifests live at workspace/work-orders/<key>/freeze.json and
    hold repo-relative paths (a JSON list, or an object with a
    'frozen_paths' list). A manifest binds only while its work order is
    active; the team flow writes it, pmo only enforces it."""
    resolved = hook_common.resolve_project(cwd)
    if resolved is None:
        return None
    project_key, project_root = resolved
    orders_dir = Path(project_root) / "workspace" / "work-orders"
    if not orders_dir.is_dir():
        return None
    manifests = sorted(orders_dir.glob("*/freeze.json"))
    if not manifests:
        return None
    try:
        con = pmo_cli.connect()
    except Exception:
        return None
    for manifest in manifests:
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except Exception:
            continue
        paths = data.get("frozen_paths", []) if isinstance(data, dict) else data
        if not isinstance(paths, list):
            continue
        if not any(
            isinstance(p, str) and (Path(project_root) / p).resolve() == target
            for p in paths
        ):
            continue
        key = manifest.parent.name
        try:
            row = con.execute(
                "SELECT status FROM work_orders WHERE work_order_key = ?",
                (key,),
            ).fetchone()
        except Exception:
            continue
        if row and row["status"] in pmo_cli.ACTIVE_WO_STATUSES:
            return key
    return None


def main() -> int:
    payload = hook_common.read_payload()
    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        return 0
    file_path = str(tool_input.get("file_path", "") or tool_input.get("path", ""))
    if not file_path:
        return 0
    try:
        target = Path(file_path).resolve()
        db = pmo_cli.db_path().resolve()
    except Exception:
        return 0
    if target == db or (target.parent == db.parent and target.name.startswith(db.name)):
        return deny(
            "the PMO database is written only through the PMO CLI;"
            " direct file writes are not allowed. Use the CLI subcommands."
        )
    if "_generated" in target.parts:
        return deny(
            "this path is inside a _generated directory, which is"
            " machine-owned; hand edits would be lost. Change the authored"
            " docs and re-run the owning render command."
        )
    try:
        frozen_key = frozen_by_work_order(target, str(payload.get("cwd", "")))
        if frozen_key:
            return deny(
                f"this document is frozen by active work order '{frozen_key}'"
                " (its story claims rules or criteria this file owns);"
                " a mid-order edit would fork the running spec. Finish or"
                " release the work order first."
            )
    except Exception:
        pass
    try:
        if target.is_file():
            with target.open("r", encoding="utf-8", errors="replace") as fh:
                first_line = fh.readline()
            match = GENERATED_MARKER_RE.match(first_line.strip())
            if match:
                generator = first_line.split("generated by", 1)[1].split(";", 1)[0].strip()
                return deny(
                    f"this file is a GENERATED view (owner: {generator});"
                    " hand edits are not allowed and would be lost. Change"
                    " the source data or authored docs, then re-run the"
                    f" {generator.split()[0]} render command."
                )
            if frontmatter_locked(target):
                return deny(
                    "this record is locked (frontmatter 'locked: true'):"
                    " it is closed audit history and is never edited or"
                    " reopened. Continue in a new record instead."
                )
    except Exception:
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
